-- seed_03_2_lemma.sql - Author: Stefania Julin
-- lemma part 2/3 (535 rows) + morpho_form (830 rows)
BEGIN;

INSERT INTO lemma (lemma_id, text_root, grammatical_category, frequency_rank, interference_json, variant_id) VALUES
    (536, 'child', 'noun', NULL, NULL, 3),
    (537, 'fratello', 'noun', NULL, '{"standard_translation_EN": "brother", "standard_translation_IT": "fratello", "note_culturale": "Condivide almeno un genitore."}', 1),
    (538, 'veli', 'noun', NULL, NULL, 2),
    (539, 'brother', 'noun', NULL, NULL, 3),
    (540, 'sorella', 'noun', NULL, '{"standard_translation_EN": "sister", "standard_translation_IT": "sorella", "note_culturale": "Condivide almeno un genitore."}', 1),
    (541, 'sisko', 'noun', NULL, NULL, 2),
    (542, 'sister', 'noun', NULL, NULL, 3),
    (543, 'nonno', 'noun', NULL, '{"standard_translation_EN": "grandfather", "standard_translation_IT": "nonno", "note_culturale": "Il padre di uno dei genitori."}', 1),
    (544, 'isoisä', 'noun', NULL, NULL, 2),
    (545, 'grandfather', 'noun', NULL, NULL, 3),
    (546, 'nonna', 'noun', NULL, '{"standard_translation_EN": "grandmother", "standard_translation_IT": "nonna", "note_culturale": "La madre di uno dei genitori."}', 1),
    (547, 'isoäiti', 'noun', NULL, NULL, 2),
    (548, 'grandmother', 'noun', NULL, NULL, 3),
    (549, 'zio', 'noun', NULL, '{"standard_translation_EN": "uncle", "standard_translation_IT": "zio", "note_culturale": "Il fratello di un genitore."}', 1),
    (550, 'setä', 'noun', NULL, NULL, 2),
    (551, 'uncle', 'noun', NULL, NULL, 3),
    (552, 'zia', 'noun', NULL, '{"standard_translation_EN": "aunt", "standard_translation_IT": "zia", "note_culturale": "La sorella di un genitore."}', 1),
    (553, 'täti', 'noun', NULL, NULL, 2),
    (554, 'aunt', 'noun', NULL, NULL, 3),
    (555, 'cugino', 'noun', NULL, '{"standard_translation_EN": "cousin", "standard_translation_IT": "cugino", "note_culturale": "Figlio/a di uno zio/zia."}', 1),
    (556, 'serkku', 'noun', NULL, NULL, 2),
    (557, 'cousin', 'noun', NULL, NULL, 3),
    (558, 'marito', 'noun', NULL, '{"standard_translation_EN": "husband", "standard_translation_IT": "marito", "note_culturale": "Partner maschile in un matrimonio."}', 1),
    (559, 'aviomies', 'noun', NULL, NULL, 2),
    (560, 'husband', 'noun', NULL, NULL, 3),
    (561, 'moglie', 'noun', NULL, '{"standard_translation_EN": "wife", "standard_translation_IT": "moglie", "note_culturale": "Partner femminile in un matrimonio."}', 1),
    (562, 'vaimo', 'noun', NULL, NULL, 2),
    (563, 'wife', 'noun', NULL, NULL, 3),
    (564, 'partner', 'noun', NULL, '{"standard_translation_EN": "partner", "standard_translation_IT": "partner", "note_culturale": "Persona con cui si condivide una relazione."}', 1),
    (565, 'kumppani', 'noun', NULL, NULL, 2),
    (566, 'partner', 'noun', NULL, NULL, 3),
    (567, 'convivenza', 'noun', NULL, '{"standard_translation_EN": "cohabitation", "standard_translation_IT": "convivenza", "note_culturale": "Vivere insieme senza essere sposati."}', 1),
    (568, 'avoliitto', 'noun', NULL, NULL, 2),
    (569, 'cohabitation', 'noun', NULL, NULL, 3),
    (570, 'matrimonio', 'noun', NULL, '{"standard_translation_EN": "marriage", "standard_translation_IT": "matrimonio", "note_culturale": "Unione legale tra due persone."}', 1),
    (571, 'avioliitto', 'noun', NULL, NULL, 2),
    (572, 'marriage', 'noun', NULL, NULL, 3),
    (573, 'divorzio', 'noun', NULL, '{"standard_translation_EN": "divorce", "standard_translation_IT": "divorzio", "note_culturale": "Fine legale di un matrimonio."}', 1),
    (574, 'aviero', 'noun', NULL, NULL, 2),
    (575, 'divorce', 'noun', NULL, NULL, 3),
    (576, 'genitori single', 'noun', NULL, '{"standard_translation_EN": "single parent", "standard_translation_IT": "genitori single", "note_culturale": "Genitore che cresce un figlio da solo."}', 1),
    (577, 'yksinhuoltaja', 'noun', NULL, NULL, 2),
    (578, 'single parent', 'noun', NULL, NULL, 3),
    (579, 'famiglia allargata', 'noun', NULL, '{"standard_translation_EN": "blended family", "standard_translation_IT": "famiglia allargata", "note_culturale": "Famiglia con figliastri."}', 1),
    (580, 'uusperhe', 'noun', NULL, NULL, 2),
    (581, 'blended family', 'noun', NULL, NULL, 3),
    (582, 'affidare', 'verb', NULL, '{"standard_translation_EN": "adoption", "standard_translation_IT": "affidare", "note_culturale": "Prendere legalmente un bambino come proprio."}', 1),
    (583, 'adoptio', 'verb', NULL, NULL, 2),
    (584, 'adoption', 'verb', NULL, NULL, 3),
    (585, 'parente', 'noun', NULL, '{"standard_translation_EN": "relative", "standard_translation_IT": "parente", "note_culturale": "Persona legata da vincoli familiari."}', 1),
    (586, 'sukulainen', 'noun', NULL, NULL, 2),
    (587, 'relative', 'noun', NULL, NULL, 3),
    (588, 'eredità', 'noun', NULL, '{"standard_translation_EN": "inheritance", "standard_translation_IT": "eredità", "note_culturale": "Beni ricevuti da un parente defunto."}', 1),
    (589, 'perintö', 'noun', NULL, NULL, 2),
    (590, 'inheritance', 'noun', NULL, NULL, 3),
    (591, 'andare d''accordo', 'verb', NULL, '{"standard_translation_EN": "to get along", "standard_translation_IT": "andare d''accordo", "note_culturale": "Avere un buon rapporto con qualcuno."}', 1),
    (592, 'tulla toimeen', 'verb', NULL, NULL, 2),
    (593, 'to get along', 'verb', NULL, NULL, 3),
    (594, 'litigare', 'verb', NULL, '{"standard_translation_EN": "to argue", "standard_translation_IT": "litigare", "note_culturale": "Avere un disaccordo con qualcuno."}', 1),
    (595, 'riidellä', 'verb', NULL, NULL, 2),
    (596, 'to argue', 'verb', NULL, NULL, 3),
    (597, 'riconciliarsi', 'verb', NULL, '{"standard_translation_EN": "to reconcile", "standard_translation_IT": "riconciliarsi", "note_culturale": "Tornare in buoni rapporti dopo una lite."}', 1),
    (598, 'sovittaa', 'verb', NULL, NULL, 2),
    (599, 'to reconcile', 'verb', NULL, NULL, 3),
    (600, 'coinquilino', 'noun', NULL, '{"standard_translation_EN": "roommate", "standard_translation_IT": "coinquilino", "note_culturale": "Persona con cui si condivide un appartamento."}', 1),
    (601, 'kämppis', 'noun', NULL, NULL, 2),
    (602, 'roommate', 'noun', NULL, NULL, 3),
    (603, 'convivere', 'verb', NULL, '{"standard_translation_EN": "to live together", "standard_translation_IT": "convivere", "note_culturale": "Condividere una casa con qualcuno."}', 1),
    (604, 'asua yhdessä', 'verb', NULL, NULL, 2),
    (605, 'to live together', 'verb', NULL, NULL, 3),
    (606, 'legame', 'noun', NULL, '{"standard_translation_EN": "bond", "standard_translation_IT": "legame", "note_culturale": "Un forte sentimento di unione."}', 1),
    (607, 'side', 'noun', NULL, NULL, 2),
    (608, 'bond', 'noun', NULL, NULL, 3),
    (609, 'supporto', 'noun', NULL, '{"standard_translation_EN": "support", "standard_translation_IT": "supporto", "note_culturale": "Offrire aiuto e incoraggiamento."}', 1),
    (610, 'tuki', 'noun', NULL, NULL, 2),
    (611, 'support', 'noun', NULL, NULL, 3),
    (612, 'cura', 'noun', NULL, '{"standard_translation_EN": "care", "standard_translation_IT": "cura", "note_culturale": "Prendersi cura di qualcuno."}', 1),
    (613, 'hoito', 'noun', NULL, NULL, 2),
    (614, 'care', 'noun', NULL, NULL, 3),
    (615, 'tradimento', 'noun', NULL, '{"standard_translation_EN": "betrayal", "standard_translation_IT": "tradimento", "note_culturale": "Violazione della fiducia."}', 1),
    (616, 'petos', 'noun', NULL, NULL, 2),
    (617, 'betrayal', 'noun', NULL, NULL, 3),
    (618, 'fidanzato', 'noun', NULL, '{"standard_translation_EN": "fiancé", "standard_translation_IT": "fidanzato", "note_culturale": "Persona promessa in matrimonio."}', 1),
    (619, 'kihlattu', 'noun', NULL, NULL, 2),
    (620, 'fiancé', 'noun', NULL, NULL, 3),
    (621, 'fidanzata', 'noun', NULL, '{"standard_translation_EN": "fiancée", "standard_translation_IT": "fidanzata", "note_culturale": "Persona promessa in matrimonio."}', 1),
    (622, 'fiancée', 'noun', NULL, NULL, 3),
    (623, 'rispetto', 'noun', NULL, '{"standard_translation_EN": "respect", "standard_translation_IT": "rispetto", "note_culturale": "Considerazione e apprezzamento per qualcuno."}', 1),
    (624, 'kunnioitus', 'noun', NULL, NULL, 2),
    (625, 'respect', 'noun', NULL, NULL, 3),
    (626, 'affetto', 'noun', NULL, '{"standard_translation_EN": "affection", "standard_translation_IT": "affetto", "note_culturale": "Sentimento di amore e cura."}', 1),
    (627, 'kiintymys', 'noun', NULL, NULL, 2),
    (628, 'affection', 'noun', NULL, NULL, 3),
    (629, 'Poikaystävä', 'noun', NULL, NULL, 2),
    (630, 'Boyfriend', 'noun', NULL, NULL, 3),
    (631, 'Tyttöystävä', 'noun', NULL, NULL, 2),
    (632, 'Girlfriend', 'noun', NULL, NULL, 3),
    (633, 'Avioero', 'noun', NULL, NULL, 2),
    (634, 'Häät', 'noun', NULL, NULL, 2),
    (635, 'Wedding', 'noun', NULL, NULL, 3),
    (636, 'Bollette', 'noun', NULL, '{"standard_translation_EN": "Bills", "standard_translation_IT": "Bollette", "note_culturale": "Spese per elettricità, acqua, gas, internet."}', 1),
    (637, 'Laskut', 'noun', NULL, NULL, 2),
    (638, 'Bills', 'noun', NULL, NULL, 3),
    (639, 'Condividere', 'verb', NULL, '{"standard_translation_EN": "Share", "standard_translation_IT": "Condividere", "note_culturale": "Usare qualcosa insieme ad altri."}', 1),
    (640, 'Jakaa', 'verb', NULL, NULL, 2),
    (641, 'Share', 'verb', NULL, NULL, 3),
    (642, 'Responsabilità', 'noun', NULL, '{"standard_translation_EN": "Responsibility", "standard_translation_IT": "Responsabilità", "note_culturale": "Obbligo di fare qualcosa."}', 1),
    (643, 'Vastuu', 'noun', NULL, NULL, 2),
    (644, 'Responsibility', 'noun', NULL, NULL, 3),
    (645, 'Compromesso', 'noun', NULL, '{"standard_translation_EN": "Compromise", "standard_translation_IT": "Compromesso", "note_culturale": "Trovare una soluzione accettabile per tutti."}', 1),
    (646, 'Kompromissi', 'noun', NULL, NULL, 2),
    (647, 'Compromise', 'noun', NULL, NULL, 3),
    (648, 'Argue', 'verb', NULL, NULL, 3),
    (649, 'Rispettare', 'verb', NULL, '{"standard_translation_EN": "Respect", "standard_translation_IT": "Rispettare", "note_culturale": "Avere considerazione per qualcuno."}', 1),
    (650, 'Kunnioittaa', 'verb', NULL, NULL, 2),
    (651, 'Supportare', 'verb', NULL, '{"standard_translation_EN": "Support", "standard_translation_IT": "Supportare", "note_culturale": "Dare aiuto e incoraggiamento."}', 1),
    (652, 'Tukea', 'verb', NULL, NULL, 2),
    (653, 'Generazione', 'noun', NULL, '{"standard_translation_EN": "Generation", "standard_translation_IT": "Generazione", "note_culturale": "Insieme di persone nate nello stesso periodo."}', 1),
    (654, 'Sukupolvi', 'noun', NULL, NULL, 2),
    (655, 'Generation', 'noun', NULL, NULL, 3),
    (656, 'Sidos', 'noun', NULL, NULL, 2),
    (657, 'Educare', 'verb', NULL, '{"standard_translation_EN": "Raise", "standard_translation_IT": "Educare", "note_culturale": "Allevare e istruire un bambino."}', 1),
    (658, 'Kasvattaa', 'verb', NULL, NULL, 2),
    (659, 'Raise', 'verb', NULL, NULL, 3),
    (660, 'Valori', 'noun', NULL, '{"standard_translation_EN": "Values", "standard_translation_IT": "Valori", "note_culturale": "Ideali e credenze importanti per una persona o famiglia."}', 1),
    (661, 'Arvot', 'noun', NULL, NULL, 2),
    (662, 'Values', 'noun', NULL, NULL, 3),
    (663, 'Tradizioni', 'noun', NULL, '{"standard_translation_EN": "Traditions", "standard_translation_IT": "Tradizioni", "note_culturale": "Usanze e rituali tramandati di generazione in generazione."}', 1),
    (664, 'Perinteet', 'noun', NULL, NULL, 2),
    (665, 'Traditions', 'noun', NULL, NULL, 3),
    (666, 'Parenti', 'noun', NULL, '{"standard_translation_EN": "Relatives", "standard_translation_IT": "Parenti", "note_culturale": "Membri della famiglia allargata."}', 1),
    (667, 'Sukulaiset', 'noun', NULL, NULL, 2),
    (668, 'Relatives', 'noun', NULL, NULL, 3),
    (669, 'Generoso', 'adjective', NULL, '{"standard_translation_EN": "Generous", "standard_translation_IT": "Generoso", "note_culturale": "Disposto a condividere e dare agli altri."}', 1),
    (670, 'Antelias', 'adjective', NULL, NULL, 2),
    (671, 'Generous', 'adjective', NULL, NULL, 3),
    (672, 'Affettuoso', 'adjective', NULL, '{"standard_translation_EN": "Affectionate", "standard_translation_IT": "Affettuoso", "note_culturale": "Che mostra amore e tenerezza."}', 1),
    (673, 'Hellä', 'adjective', NULL, NULL, 2),
    (674, 'Affectionate', 'adjective', NULL, NULL, 3),
    (675, 'Geloso', 'adjective', NULL, '{"standard_translation_EN": "Jealous", "standard_translation_IT": "Geloso", "note_culturale": "Che prova risentimento per il successo o i beni altrui."}', 1),
    (676, 'Mustasukkainen', 'adjective', NULL, NULL, 2),
    (677, 'Jealous', 'adjective', NULL, NULL, 3),
    (678, 'Divorziare', 'verb', NULL, '{"standard_translation_EN": "To divorce", "standard_translation_IT": "Divorziare", "note_culturale": "Terminare un matrimonio legalmente."}', 1),
    (679, 'Erota', 'verb', NULL, NULL, 2),
    (680, 'To divorce', 'verb', NULL, NULL, 3),
    (681, 'Adottare', 'verb', NULL, '{"standard_translation_EN": "To adopt", "standard_translation_IT": "Adottare", "note_culturale": "Accogliere legalmente un bambino come proprio."}', 1),
    (682, 'Adoptoida', 'verb', NULL, NULL, 2),
    (683, 'To adopt', 'verb', NULL, NULL, 3),
    (684, 'Huostaanottaa', 'verb', NULL, NULL, 2),
    (685, 'To foster', 'verb', NULL, NULL, 3),
    (686, 'Single', 'adj', NULL, '{"standard_translation_EN": "Single", "standard_translation_IT": "Single", "note_culturale": "Non avere una relazione sentimentale."}', 1),
    (687, 'Sinkku', 'adj', NULL, NULL, 2),
    (688, 'Single', 'adj', NULL, NULL, 3),
    (689, 'Laajennettu perhe', 'noun', NULL, NULL, 2),
    (690, 'Extended family', 'noun', NULL, NULL, 3),
    (691, 'Essere innamorati', 'verb', NULL, '{"standard_translation_EN": "To be in love", "standard_translation_IT": "Essere innamorati", "note_culturale": "Provare un forte sentimento di affetto."}', 1),
    (692, 'Olla rakastunut', 'verb', NULL, NULL, 2),
    (693, 'To be in love', 'verb', NULL, NULL, 3),
    (694, 'Famiglia arcobaleno', 'noun', NULL, '{"standard_translation_EN": "Rainbow family", "standard_translation_IT": "Famiglia arcobaleno", "note_culturale": "Una famiglia con genitori dello stesso sesso."}', 1),
    (695, 'Sateenkaariperhe', 'noun', NULL, NULL, 2),
    (696, 'Rainbow family', 'noun', NULL, NULL, 3),
    (697, 'Suoceri', 'noun', NULL, '{"standard_translation_EN": "In-laws", "standard_translation_IT": "Suoceri", "note_culturale": "I genitori del tuo coniuge."}', 1),
    (698, 'Appivanhemmat', 'noun', NULL, NULL, 2),
    (699, 'In-laws', 'noun', NULL, NULL, 3),
    (700, 'Nipote', 'noun', NULL, '{"standard_translation_EN": "Grandchild", "standard_translation_IT": "Nipote", "note_culturale": "Il figlio o la figlia di tuo figlio o figlia."}', 1),
    (701, 'Lapsenlapsi', 'noun', NULL, NULL, 2),
    (702, 'Grandchild', 'noun', NULL, NULL, 3),
    (703, 'Orfano', 'noun', NULL, '{"standard_translation_EN": "Orphan", "standard_translation_IT": "Orfano", "note_culturale": "Un bambino che ha perso entrambi i genitori."}', 1),
    (704, 'Orpo', 'noun', NULL, NULL, 2),
    (705, 'Orphan', 'noun', NULL, NULL, 3),
    (706, 'Crescere', 'verb', NULL, '{"standard_translation_EN": "To grow up", "standard_translation_IT": "Crescere", "note_culturale": "Passare dall''infanzia all''età adulta."}', 1),
    (707, 'Kasvaa', 'verb', NULL, NULL, 2),
    (708, 'To grow up', 'verb', NULL, NULL, 3),
    (709, 'Essere in dolce attesa', 'verb', NULL, '{"standard_translation_EN": "To be pregnant", "standard_translation_IT": "Essere in dolce attesa", "note_culturale": "Aspettare un bambino."}', 1),
    (710, 'Olla raskaana', 'verb', NULL, NULL, 2),
    (711, 'To be pregnant', 'verb', NULL, NULL, 3),
    (712, 'Natale', 'noun', NULL, '{"standard_translation_EN": "Christmas", "standard_translation_IT": "Natale", "note_culturale": "Il Natale è una festa cristiana che celebra la nascita di Gesù. (Importante in entrambi i paesi)."}', 1),
    (713, 'Joulu', 'noun', NULL, NULL, 2),
    (714, 'Christmas', 'noun', NULL, NULL, 3),
    (715, 'Pasqua', 'noun', NULL, '{"standard_translation_EN": "Easter", "standard_translation_IT": "Pasqua", "note_culturale": "La Pasqua celebra la resurrezione di Gesù Cristo."}', 1),
    (716, 'Pääsiäinen', 'noun', NULL, NULL, 2),
    (717, 'Easter', 'noun', NULL, NULL, 3),
    (718, 'Ferragosto', 'noun', NULL, '{"standard_translation_EN": "Mid-August Holiday", "standard_translation_IT": "Ferragosto", "note_culturale": "Ferragosto è una festa italiana che celebra l''Assunzione di Maria e segna l''inizio delle vacanze estive."}', 1),
    (719, 'Elokuun puoliväli', 'noun', NULL, NULL, 2),
    (720, 'Mid-August Holiday', 'noun', NULL, NULL, 3),
    (721, 'Carnevale', 'noun', NULL, '{"standard_translation_EN": "Carnival", "standard_translation_IT": "Carnevale", "note_culturale": "Festa con sfilate, maschere e divertimento prima della Quaresima."}', 1),
    (722, 'Laskiainen', 'noun', NULL, NULL, 2),
    (723, 'Carnival', 'noun', NULL, NULL, 3),
    (724, 'Befana', 'noun', NULL, '{"standard_translation_EN": "Epiphany", "standard_translation_IT": "Befana", "note_culturale": "La Befana è una figura folkloristica che porta dolci ai bambini buoni."}', 1),
    (725, 'Loppiainen', 'noun', NULL, NULL, 2),
    (726, 'Epiphany', 'noun', NULL, NULL, 3),
    (727, 'Tradizione', 'noun', NULL, '{"standard_translation_EN": "Tradition", "standard_translation_IT": "Tradizione", "note_culturale": "Un''usanza che viene tramandata di generazione in generazione."}', 1),
    (728, 'Perinne', 'noun', NULL, NULL, 2),
    (729, 'Tradition', 'noun', NULL, NULL, 3),
    (730, 'Celebrazione', 'noun', NULL, '{"standard_translation_EN": "Celebration", "standard_translation_IT": "Celebrazione", "note_culturale": "Un evento sociale per celebrare qualcosa."}', 1),
    (731, 'Juhla', 'noun', NULL, NULL, 2),
    (732, 'Celebration', 'noun', NULL, NULL, 3),
    (733, 'Cenone', 'noun', NULL, '{"standard_translation_EN": "Festive Dinner", "standard_translation_IT": "Cenone", "note_culturale": "Un pasto abbondante e sontuoso tipico della sera della Vigilia."}', 1),
    (734, 'Juhlaillallinen', 'noun', NULL, NULL, 2),
    (735, 'Festive Dinner', 'noun', NULL, NULL, 3),
    (736, 'Fuochi d''artificio', 'noun', NULL, '{"standard_translation_EN": "Fireworks", "standard_translation_IT": "Fuochi d''artificio", "note_culturale": "Spettacolo pirotecnico usato per festeggiare."}', 1),
    (737, 'Ilotulitus', 'noun', NULL, NULL, 2),
    (738, 'Fireworks', 'noun', NULL, NULL, 3),
    (739, 'Sagra', 'noun', NULL, '{"standard_translation_EN": "Local Festival", "standard_translation_IT": "Sagra", "note_culturale": "Festa locale italiana dedicata alla celebrazione di un prodotto tipico o di un santo."}', 1),
    (740, 'Paikallinen juhla', 'noun', NULL, NULL, 2),
    (741, 'Local Festival', 'noun', NULL, NULL, 3),
    (742, 'Tombola', 'noun', NULL, '{"standard_translation_EN": "Bingo", "standard_translation_IT": "Tombola", "note_culturale": "Gioco tradizionale italiano, popolare durante il periodo natalizio."}', 1),
    (743, 'Bingo', 'noun', NULL, NULL, 2),
    (744, 'Bingo', 'noun', NULL, NULL, 3),
    (745, 'lavoro', 'noun', NULL, '{"standard_translation_EN": "job", "standard_translation_IT": "lavoro", "note_culturale": "Concetto fondamentale per l''indipendenza economica."}', 1),
    (746, 'työ', 'noun', NULL, NULL, 2),
    (747, 'job', 'noun', NULL, NULL, 3),
    (748, 'colloquio', 'noun', NULL, '{"standard_translation_EN": "interview", "standard_translation_IT": "colloquio", "note_culturale": "Incontro formale per valutare un candidato."}', 1),
    (749, 'haastattelu', 'noun', NULL, NULL, 2),
    (750, 'interview', 'noun', NULL, NULL, 3),
    (751, 'stipendio', 'noun', NULL, '{"standard_translation_EN": "salary", "standard_translation_IT": "stipendio", "note_culturale": "Pagamento regolare per il lavoro svolto."}', 1),
    (752, 'palkka', 'noun', NULL, NULL, 2),
    (753, 'salary', 'noun', NULL, NULL, 3),
    (754, 'carriera', 'noun', NULL, '{"standard_translation_EN": "career", "standard_translation_IT": "carriera", "note_culturale": "Progressione nel mondo del lavoro."}', 1),
    (755, 'ura', 'noun', NULL, NULL, 2),
    (756, 'career', 'noun', NULL, NULL, 3),
    (757, 'datore di lavoro', 'noun', NULL, '{"standard_translation_EN": "employer", "standard_translation_IT": "datore di lavoro", "note_culturale": "Persona o azienda che assume dipendenti."}', 1),
    (758, 'työnantaja', 'noun', NULL, NULL, 2),
    (759, 'employer', 'noun', NULL, NULL, 3),
    (760, 'dipendente', 'noun', NULL, '{"standard_translation_EN": "employee", "standard_translation_IT": "dipendente", "note_culturale": "Persona che lavora per un datore di lavoro."}', 1),
    (761, 'työntekijä', 'noun', NULL, NULL, 2),
    (762, 'employee', 'noun', NULL, NULL, 3),
    (763, 'contratto', 'noun', NULL, '{"standard_translation_EN": "contract", "standard_translation_IT": "contratto", "note_culturale": "Documento che stabilisce i termini dell''impiego."}', 1),
    (764, 'sopimus', 'noun', NULL, NULL, 2),
    (765, 'contract', 'noun', NULL, NULL, 3),
    (766, 'curriculum', 'noun', NULL, '{"standard_translation_EN": "resume", "standard_translation_IT": "curriculum", "note_culturale": "Documento che riassume l''esperienza e le qualifiche."}', 1),
    (767, 'ansioluettelo', 'noun', NULL, NULL, 2),
    (768, 'resume', 'noun', NULL, NULL, 3),
    (769, 'mansione', 'noun', NULL, '{"standard_translation_EN": "task", "standard_translation_IT": "mansione", "note_culturale": "Attività specifica da svolgere sul lavoro."}', 1),
    (770, 'tehtävä', 'noun', NULL, NULL, 2),
    (771, 'task', 'noun', NULL, NULL, 3),
    (772, 'promozione', 'noun', NULL, '{"standard_translation_EN": "promotion", "standard_translation_IT": "promozione", "note_culturale": "Avanzamento di grado o posizione all''interno dell''azienda."}', 1),
    (773, 'ylennys', 'noun', NULL, NULL, 2),
    (774, 'promotion', 'noun', NULL, NULL, 3),
    (775, 'licenziamento', 'noun', NULL, '{"standard_translation_EN": "dismissal", "standard_translation_IT": "licenziamento", "note_culturale": "Cessazione del rapporto di lavoro da parte del datore di lavoro."}', 1),
    (776, 'irtisanominen', 'noun', NULL, NULL, 2),
    (777, 'dismissal', 'noun', NULL, NULL, 3),
    (778, 'dimissioni', 'noun', NULL, '{"standard_translation_EN": "resignation", "standard_translation_IT": "dimissioni", "note_culturale": "Cessazione volontaria del rapporto di lavoro da parte del dipendente."}', 1),
    (779, 'eroaminen', 'noun', NULL, NULL, 2),
    (780, 'collega', 'noun', NULL, '{"standard_translation_EN": "colleague", "standard_translation_IT": "collega", "note_culturale": "Persona con cui si lavora."}', 1),
    (781, 'kollega', 'noun', NULL, NULL, 2),
    (782, 'colleague', 'noun', NULL, NULL, 3),
    (783, 'scrivania', 'noun', NULL, '{"standard_translation_EN": "desk", "standard_translation_IT": "scrivania", "note_culturale": "Mobile utilizzato per lavorare o studiare."}', 1),
    (784, 'työpöytä', 'noun', NULL, NULL, 2),
    (785, 'desk', 'noun', NULL, NULL, 3),
    (786, 'riunione', 'noun', NULL, '{"standard_translation_EN": "meeting", "standard_translation_IT": "riunione", "note_culturale": "Incontro per discutere argomenti di lavoro."}', 1),
    (787, 'kokous', 'noun', NULL, NULL, 2),
    (788, 'meeting', 'noun', NULL, NULL, 3),
    (789, 'määräaika', 'noun', NULL, NULL, 2),
    (790, 'deadline', 'noun', NULL, NULL, 3),
    (791, 'obiettivo', 'noun', NULL, '{"standard_translation_EN": "goal", "standard_translation_IT": "obiettivo", "note_culturale": "Risultato desiderato da raggiungere."}', 1),
    (792, 'tavoite', 'noun', NULL, NULL, 2),
    (793, 'goal', 'noun', NULL, NULL, 3),
    (794, 'settore', 'noun', NULL, '{"standard_translation_EN": "sector", "standard_translation_IT": "settore", "note_culturale": "Area specifica di attività economica."}', 1),
    (795, 'ala', 'noun', NULL, NULL, 2),
    (796, 'sector', 'noun', NULL, NULL, 3),
    (797, 'risorse umane', 'noun', NULL, '{"standard_translation_EN": "human resources", "standard_translation_IT": "risorse umane", "note_culturale": "Dipartimento che si occupa del personale."}', 1),
    (798, 'henkilöstöhallinto', 'noun', NULL, NULL, 2),
    (799, 'human resources', 'noun', NULL, NULL, 3),
    (800, 'azienda', 'noun', NULL, '{"standard_translation_EN": "company", "standard_translation_IT": "azienda", "note_culturale": "Organizzazione che produce beni o servizi."}', 1),
    (801, 'yritys', 'noun', NULL, NULL, 2),
    (802, 'company', 'noun', NULL, NULL, 3),
    (803, 'orario di lavoro', 'noun', NULL, '{"standard_translation_EN": "working hours", "standard_translation_IT": "orario di lavoro", "note_culturale": "Periodo di tempo dedicato al lavoro."}', 1),
    (804, 'työaika', 'noun', NULL, NULL, 2),
    (805, 'working hours', 'noun', NULL, NULL, 3),
    (806, 'benefit', 'noun', NULL, '{"standard_translation_EN": "benefit", "standard_translation_IT": "benefit", "note_culturale": "Vantaggi aggiuntivi allo stipendio."}', 1),
    (807, 'etu', 'noun', NULL, NULL, 2),
    (808, 'benefit', 'noun', NULL, NULL, 3),
    (809, 'rete', 'noun', NULL, '{"standard_translation_EN": "network", "standard_translation_IT": "rete", "note_culturale": "Insieme di contatti professionali."}', 1),
    (810, 'verkosto', 'noun', NULL, NULL, 2),
    (811, 'network', 'noun', NULL, NULL, 3),
    (812, 'orario', 'noun', NULL, '{"standard_translation_EN": "schedule", "standard_translation_IT": "orario", "note_culturale": "Distribuzione del tempo di lavoro."}', 1),
    (813, 'aikataulu', 'noun', NULL, NULL, 2),
    (814, 'schedule', 'noun', NULL, NULL, 3),
    (815, 'formazione', 'noun', NULL, '{"standard_translation_EN": "training", "standard_translation_IT": "formazione", "note_culturale": "Processo di apprendimento di nuove competenze."}', 1),
    (816, 'koulutus', 'noun', NULL, NULL, 2),
    (817, 'training', 'noun', NULL, NULL, 3),
    (818, 'professione', 'noun', NULL, '{"standard_translation_EN": "profession", "standard_translation_IT": "professione", "note_culturale": "Attività lavorativa specializzata."}', 1),
    (819, 'ammatti', 'noun', NULL, NULL, 2),
    (820, 'profession', 'noun', NULL, NULL, 3),
    (821, 'competenza', 'noun', NULL, '{"standard_translation_EN": "skill", "standard_translation_IT": "competenza", "note_culturale": "Capacità di svolgere un compito."}', 1),
    (822, 'osaaminen', 'noun', NULL, NULL, 2),
    (823, 'skill', 'noun', NULL, NULL, 3),
    (824, 'team', 'noun', NULL, '{"standard_translation_EN": "team", "standard_translation_IT": "team", "note_culturale": "Gruppo di persone che lavorano insieme."}', 1),
    (825, 'tiimi', 'noun', NULL, NULL, 2),
    (826, 'team', 'noun', NULL, NULL, 3),
    (827, 'gerarchia', 'noun', NULL, '{"standard_translation_EN": "hierarchy", "standard_translation_IT": "gerarchia", "note_culturale": "Sistema di livelli di autorità in un''organizzazione."}', 1),
    (828, 'hierarkia', 'noun', NULL, NULL, 2),
    (829, 'hierarchy', 'noun', NULL, NULL, 3),
    (830, 'collaborazione', 'noun', NULL, '{"standard_translation_EN": "collaboration", "standard_translation_IT": "collaborazione", "note_culturale": "Lavorare insieme per raggiungere un obiettivo comune."}', 1),
    (831, 'yhteistyö', 'noun', NULL, NULL, 2),
    (832, 'collaboration', 'noun', NULL, NULL, 3),
    (833, 'albero', 'noun', NULL, '{"standard_translation_EN": "tree", "standard_translation_IT": "albero", "note_culturale": "Gli alberi sono essenziali per l''ecosistema."}', 1),
    (834, 'puu', 'noun', NULL, NULL, 2),
    (835, 'tree', 'noun', NULL, NULL, 3),
    (836, 'fiume', 'noun', NULL, '{"standard_translation_EN": "river", "standard_translation_IT": "fiume", "note_culturale": "I fiumi sono importanti vie di trasporto e fonti di acqua."}', 1),
    (837, 'joki', 'noun', NULL, NULL, 2),
    (838, 'river', 'noun', NULL, NULL, 3),
    (839, 'animale', 'noun', NULL, '{"standard_translation_EN": "animal", "standard_translation_IT": "animale", "note_culturale": "Gli animali svolgono ruoli cruciali negli ecosistemi."}', 1),
    (840, 'eläin', 'noun', NULL, NULL, 2),
    (841, 'animal', 'noun', NULL, NULL, 3),
    (842, 'fiore', 'noun', NULL, '{"standard_translation_EN": "flower", "standard_translation_IT": "fiore", "note_culturale": "I fiori sono importanti per l''impollinazione."}', 1),
    (843, 'kukka', 'noun', NULL, NULL, 2),
    (844, 'flower', 'noun', NULL, NULL, 3),
    (845, 'estate', 'noun', NULL, '{"standard_translation_EN": "summer", "standard_translation_IT": "estate", "note_culturale": "L''estate è spesso associata alle vacanze."}', 1),
    (846, 'kesä', 'noun', NULL, NULL, 2),
    (847, 'summer', 'noun', NULL, NULL, 3),
    (848, 'inverno', 'noun', NULL, '{"standard_translation_EN": "winter", "standard_translation_IT": "inverno", "note_culturale": "L''inverno porta spesso neve e ghiaccio."}', 1),
    (849, 'talvi', 'noun', NULL, NULL, 2),
    (850, 'winter', 'noun', NULL, NULL, 3),
    (851, 'ecologia', 'noun', NULL, '{"standard_translation_EN": "ecology", "standard_translation_IT": "ecologia", "note_culturale": "L''ecologia studia le interazioni tra gli organismi e il loro ambiente."}', 1),
    (852, 'ekologia', 'noun', NULL, NULL, 2),
    (853, 'ecology', 'noun', NULL, NULL, 3),
    (854, 'biodiversità', 'noun', NULL, '{"standard_translation_EN": "biodiversity", "standard_translation_IT": "biodiversità", "note_culturale": "La biodiversità è essenziale per la salute del pianeta."}', 1),
    (855, 'biodiversiteetti', 'noun', NULL, NULL, 2),
    (856, 'biodiversity', 'noun', NULL, NULL, 3),
    (857, 'ecosistema', 'noun', NULL, '{"standard_translation_EN": "ecosystem", "standard_translation_IT": "ecosistema", "note_culturale": "Un ecosistema è una comunità di organismi interagenti."}', 1),
    (858, 'ekosysteemi', 'noun', NULL, NULL, 2),
    (859, 'ecosystem', 'noun', NULL, NULL, 3),
    (860, 'prato', 'noun', NULL, '{"standard_translation_EN": "meadow", "standard_translation_IT": "prato", "note_culturale": "I prati sono spesso pieni di fiori selvatici."}', 1),
    (861, 'niitty', 'noun', NULL, NULL, 2),
    (862, 'meadow', 'noun', NULL, NULL, 3),
    (863, 'foresta', 'noun', NULL, '{"standard_translation_EN": "forest", "standard_translation_IT": "foresta", "note_culturale": "Le foreste sono importanti per la produzione di ossigeno."}', 1),
    (864, 'metsä', 'noun', NULL, NULL, 2),
    (865, 'forest', 'noun', NULL, NULL, 3),
    (866, 'autunno', 'noun', NULL, '{"standard_translation_EN": "autumn", "standard_translation_IT": "autunno", "note_culturale": "L''autunno è noto per i suoi colori vivaci."}', 1),
    (867, 'syksy', 'noun', NULL, NULL, 2),
    (868, 'autumn', 'noun', NULL, NULL, 3),
    (869, 'primavera', 'noun', NULL, '{"standard_translation_EN": "spring", "standard_translation_IT": "primavera", "note_culturale": "La primavera è il momento della rinascita della natura."}', 1),
    (870, 'kevät', 'noun', NULL, NULL, 2),
    (871, 'spring', 'noun', NULL, NULL, 3),
    (872, 'clima', 'noun', NULL, '{"standard_translation_EN": "climate", "standard_translation_IT": "clima", "note_culturale": "Il clima influenza la flora e la fauna di una regione."}', 1),
    (873, 'ilmasto', 'noun', NULL, NULL, 2),
    (874, 'climate', 'noun', NULL, NULL, 3),
    (875, 'inquinamento', 'noun', NULL, '{"standard_translation_EN": "pollution", "standard_translation_IT": "inquinamento", "note_culturale": "L''inquinamento danneggia l''ambiente e la salute umana."}', 1),
    (876, 'saastuminen', 'noun', NULL, NULL, 2),
    (877, 'pollution', 'noun', NULL, NULL, 3),
    (878, 'energia solare', 'noun', NULL, '{"standard_translation_EN": "solar energy", "standard_translation_IT": "energia solare", "note_culturale": "L''energia solare è una fonte di energia rinnovabile."}', 1),
    (879, 'aurinkoenergia', 'noun', NULL, NULL, 2),
    (880, 'solar energy', 'noun', NULL, NULL, 3),
    (881, 'riscaldamento globale', 'noun', NULL, '{"standard_translation_EN": "global warming", "standard_translation_IT": "riscaldamento globale", "note_culturale": "Il riscaldamento globale è una grave minaccia per il pianeta."}', 1),
    (882, 'ilmaston lämpeneminen', 'noun', NULL, NULL, 2),
    (883, 'global warming', 'noun', NULL, NULL, 3),
    (884, 'conservazione', 'noun', NULL, '{"standard_translation_EN": "conservation", "standard_translation_IT": "conservazione", "note_culturale": "La conservazione è essenziale per proteggere le risorse naturali."}', 1),
    (885, 'luonnonsuojelu', 'noun', NULL, NULL, 2),
    (886, 'conservation', 'noun', NULL, NULL, 3),
    (887, 'fauna', 'noun', NULL, '{"standard_translation_EN": "fauna", "standard_translation_IT": "fauna", "note_culturale": "La fauna di una regione è l''insieme degli animali che la abitano."}', 1),
    (888, 'eläimistö', 'noun', NULL, NULL, 2),
    (889, 'fauna', 'noun', NULL, NULL, 3),
    (890, 'Sole', 'noun', NULL, '{"standard_translation_EN": "Sun", "standard_translation_IT": "Sole", "note_culturale": "Fonte di luce e calore essenziale per la vita."}', 1),
    (891, 'Aurinko', 'noun', NULL, NULL, 2),
    (892, 'Sun', 'noun', NULL, NULL, 3),
    (893, 'Pioggia', 'noun', NULL, '{"standard_translation_EN": "Rain", "standard_translation_IT": "Pioggia", "note_culturale": "Necessaria per l''agricoltura e la vita."}', 1),
    (894, 'Sade', 'noun', NULL, NULL, 2),
    (895, 'Rain', 'noun', NULL, NULL, 3),
    (896, 'Terra', 'noun', NULL, '{"standard_translation_EN": "Earth", "standard_translation_IT": "Terra", "note_culturale": "Il nostro pianeta, fonte di vita."}', 1),
    (897, 'Maa', 'noun', NULL, NULL, 2),
    (898, 'Earth', 'noun', NULL, NULL, 3),
    (899, 'Vento', 'noun', NULL, '{"standard_translation_EN": "Wind", "standard_translation_IT": "Vento", "note_culturale": "Può essere sia dolce che impetuoso."}', 1),
    (900, 'Tuuli', 'noun', NULL, NULL, 2),
    (901, 'Wind', 'noun', NULL, NULL, 3),
    (902, 'Lago', 'noun', NULL, '{"standard_translation_EN": "Lake", "standard_translation_IT": "Lago", "note_culturale": "Luogo di relax e habitat per molte specie."}', 1),
    (903, 'Järvi', 'noun', NULL, NULL, 2),
    (904, 'Lake', 'noun', NULL, NULL, 3),
    (905, 'Sostenibilità', 'noun', NULL, '{"standard_translation_EN": "Sustainability", "standard_translation_IT": "Sostenibilità", "note_culturale": "La capacità di soddisfare i bisogni del presente senza compromettere quelli del futuro."}', 1),
    (906, 'Kestävyys', 'noun', NULL, NULL, 2),
    (907, 'Sustainability', 'noun', NULL, NULL, 3),
    (908, 'Risorsa', 'noun', NULL, '{"standard_translation_EN": "Resource", "standard_translation_IT": "Risorsa", "note_culturale": "Qualcosa di utile o prezioso, come l''acqua o il petrolio."}', 1),
    (909, 'Resurssi', 'noun', NULL, NULL, 2),
    (910, 'Resource', 'noun', NULL, NULL, 3),
    (911, 'Suojelu', 'noun', NULL, NULL, 2),
    (912, 'raffreddore', 'noun', NULL, '{"standard_translation_EN": "cold", "standard_translation_IT": "raffreddore", "note_culturale": "Comune soprattutto in inverno."}', 1),
    (913, 'vilustuminen', 'noun', NULL, NULL, 2),
    (914, 'cold', 'noun', NULL, NULL, 3),
    (915, 'febbre', 'noun', NULL, '{"standard_translation_EN": "fever", "standard_translation_IT": "febbre", "note_culturale": "Misurata con un termometro."}', 1),
    (916, 'kuume', 'noun', NULL, NULL, 2),
    (917, 'fever', 'noun', NULL, NULL, 3),
    (918, 'medico', 'noun', NULL, '{"standard_translation_EN": "doctor", "standard_translation_IT": "medico", "note_culturale": "Professionista della salute."}', 1),
    (919, 'lääkäri', 'noun', NULL, NULL, 2),
    (920, 'doctor', 'noun', NULL, NULL, 3),
    (921, 'farmaco', 'noun', NULL, '{"standard_translation_EN": "medicine", "standard_translation_IT": "farmaco", "note_culturale": "Utilizzato per curare le malattie."}', 1),
    (922, 'lääke', 'noun', NULL, NULL, 2),
    (923, 'medicine', 'noun', NULL, NULL, 3),
    (924, 'stress', 'noun', NULL, '{"standard_translation_EN": "stress", "standard_translation_IT": "stress", "note_culturale": "Può influire negativamente sulla salute."}', 1),
    (925, 'stressi', 'noun', NULL, NULL, 2),
    (926, 'stress', 'noun', NULL, NULL, 3),
    (927, 'relax', 'noun', NULL, '{"standard_translation_EN": "relaxation", "standard_translation_IT": "relax", "note_culturale": "Importante per ridurre lo stress."}', 1),
    (928, 'rentoutuminen', 'noun', NULL, NULL, 2),
    (929, 'relaxation', 'noun', NULL, NULL, 3),
    (930, 'sintomo', 'noun', NULL, '{"standard_translation_EN": "symptom", "standard_translation_IT": "sintomo", "note_culturale": "Indicazione di una malattia."}', 1),
    (931, 'oire', 'noun', NULL, NULL, 2),
    (932, 'symptom', 'noun', NULL, NULL, 3),
    (933, 'terapia', 'noun', NULL, '{"standard_translation_EN": "therapy", "standard_translation_IT": "terapia", "note_culturale": "Insieme di trattamenti per una malattia."}', 1),
    (934, 'terapia', 'noun', NULL, NULL, 2),
    (935, 'therapy', 'noun', NULL, NULL, 3),
    (936, 'prevenzione', 'noun', NULL, '{"standard_translation_EN": "prevention", "standard_translation_IT": "prevenzione", "note_culturale": "Misure per evitare una malattia."}', 1),
    (937, 'ehkäisy', 'noun', NULL, NULL, 2),
    (938, 'prevention', 'noun', NULL, NULL, 3),
    (939, 'insonnia', 'noun', NULL, '{"standard_translation_EN": "insomnia", "standard_translation_IT": "insonnia", "note_culturale": "Difficoltà ad addormentarsi."}', 1),
    (940, 'unettomuus', 'noun', NULL, NULL, 2),
    (941, 'insomnia', 'noun', NULL, NULL, 3),
    (942, 'integratore', 'noun', NULL, '{"standard_translation_EN": "supplement", "standard_translation_IT": "integratore", "note_culturale": "Utilizzato per integrare la dieta."}', 1),
    (943, 'ravintolisä', 'noun', NULL, NULL, 2),
    (944, 'supplement', 'noun', NULL, NULL, 3),
    (945, 'massaggio', 'noun', NULL, '{"standard_translation_EN": "massage", "standard_translation_IT": "massaggio", "note_culturale": "Tecnica per rilassare i muscoli."}', 1),
    (946, 'hieronta', 'noun', NULL, NULL, 2),
    (947, 'massage', 'noun', NULL, NULL, 3),
    (948, 'vaccino', 'noun', NULL, '{"standard_translation_EN": "vaccine", "standard_translation_IT": "vaccino", "note_culturale": "Protegge dalle malattie infettive."}', 1),
    (949, 'rokote', 'noun', NULL, NULL, 2),
    (950, 'vaccine', 'noun', NULL, NULL, 3),
    (951, 'dieta', 'noun', NULL, '{"standard_translation_EN": "diet", "standard_translation_IT": "dieta", "note_culturale": "Alimentazione controllata."}', 1),
    (952, 'ruokavalio', 'noun', NULL, NULL, 2),
    (953, 'diet', 'noun', NULL, NULL, 3),
    (954, 'esercizio fisico', 'noun', NULL, '{"standard_translation_EN": "exercise", "standard_translation_IT": "esercizio fisico", "note_culturale": "Importante per la salute."}', 1),
    (955, 'liikunta', 'noun', NULL, NULL, 2),
    (956, 'exercise', 'noun', NULL, NULL, 3),
    (957, 'pronto soccorso', 'noun', NULL, '{"standard_translation_EN": "first aid", "standard_translation_IT": "pronto soccorso", "note_culturale": "Assistenza medica immediata."}', 1),
    (958, 'ensiapu', 'noun', NULL, NULL, 2),
    (959, 'first aid', 'noun', NULL, NULL, 3),
    (960, 'postura', 'noun', NULL, '{"standard_translation_EN": "posture", "standard_translation_IT": "postura", "note_culturale": "Corretta posizione del corpo."}', 1),
    (961, 'ryhti', 'noun', NULL, NULL, 2),
    (962, 'posture', 'noun', NULL, NULL, 3),
    (963, 'meditazione', 'noun', NULL, '{"standard_translation_EN": "meditation", "standard_translation_IT": "meditazione", "note_culturale": "Aiuta a ridurre lo stress."}', 1),
    (964, 'meditaatio', 'noun', NULL, NULL, 2),
    (965, 'meditation', 'noun', NULL, NULL, 3),
    (966, 'diagnosi', 'noun', NULL, '{"standard_translation_EN": "diagnosis", "standard_translation_IT": "diagnosi", "note_culturale": "Identificazione di una malattia."}', 1),
    (967, 'diagnoosi', 'noun', NULL, NULL, 2),
    (968, 'diagnosis', 'noun', NULL, NULL, 3),
    (969, 'prescription', 'noun', NULL, NULL, 3),
    (970, 'dolore', 'noun', NULL, '{"standard_translation_EN": "pain", "standard_translation_IT": "dolore", "note_culturale": "Sensazione spiacevole."}', 1),
    (971, 'kipu', 'noun', NULL, NULL, 2),
    (972, 'pain', 'noun', NULL, NULL, 3),
    (973, 'burnout', 'noun', NULL, '{"standard_translation_EN": "burnout", "standard_translation_IT": "burnout", "note_culturale": "Causato da stress prolungato."}', 1),
    (974, 'loppuunpalaminen', 'noun', NULL, NULL, 2),
    (975, 'burnout', 'noun', NULL, NULL, 3),
    (976, 'yoga', 'noun', NULL, '{"standard_translation_EN": "yoga", "standard_translation_IT": "yoga", "note_culturale": "Pratica per corpo e mente."}', 1),
    (977, 'jooga', 'noun', NULL, NULL, 2),
    (978, 'yoga', 'noun', NULL, NULL, 3),
    (979, 'antibiotico', 'noun', NULL, '{"standard_translation_EN": "antibiotic", "standard_translation_IT": "antibiotico", "note_culturale": "Farmaco contro le infezioni batteriche."}', 1),
    (980, 'antibiootti', 'noun', NULL, NULL, 2),
    (981, 'antibiotic', 'noun', NULL, NULL, 3),
    (982, 'tosse', 'noun', NULL, '{"standard_translation_EN": "cough", "standard_translation_IT": "tosse", "note_culturale": "Espulsione improvvisa e rumorosa di aria dai polmoni."}', 1),
    (983, 'yskä', 'noun', NULL, NULL, 2),
    (984, 'cough', 'noun', NULL, NULL, 3),
    (985, 'dermatologo', 'noun', NULL, '{"standard_translation_EN": "dermatologist", "standard_translation_IT": "dermatologo", "note_culturale": "Medico specializzato nella cura della pelle."}', 1),
    (986, 'ihotautilääkäri', 'noun', NULL, NULL, 2),
    (987, 'dermatologist', 'noun', NULL, NULL, 3),
    (988, 'antinfiammatorio', 'noun', NULL, '{"standard_translation_EN": "anti-inflammatory", "standard_translation_IT": "antinfiammatorio", "note_culturale": "Farmaco che riduce l''infiammazione."}', 1),
    (989, 'tulehduskipulääke', 'noun', NULL, NULL, 2),
    (990, 'anti-inflammatory', 'noun', NULL, NULL, 3),
    (991, 'cardiologo', 'noun', NULL, '{"standard_translation_EN": "cardiologist", "standard_translation_IT": "cardiologo", "note_culturale": "Medico specializzato nel cuore e nel sistema circolatorio."}', 1),
    (992, 'kardiologi', 'noun', NULL, NULL, 2),
    (993, 'cardiologist', 'noun', NULL, NULL, 3),
    (994, 'pressione alta', 'noun', NULL, '{"standard_translation_EN": "high blood pressure", "standard_translation_IT": "pressione alta", "note_culturale": "Condizione in cui la pressione del sangue è elevata."}', 1),
    (995, 'korkea verenpaine', 'noun', NULL, NULL, 2),
    (996, 'high blood pressure', 'noun', NULL, NULL, 3),
    (997, 'spa', 'noun', NULL, '{"standard_translation_EN": "spa", "standard_translation_IT": "spa", "note_culturale": "Luogo per trattamenti rilassanti e rigeneranti."}', 1),
    (998, 'kylpylä', 'noun', NULL, NULL, 2),
    (999, 'spa', 'noun', NULL, NULL, 3),
    (1000, 'pillola', 'noun', NULL, '{"standard_translation_EN": "pill", "standard_translation_IT": "pillola", "note_culturale": "La pillola è una forma comune di farmaco."}', 1),
    (1001, 'pilleri', 'noun', NULL, NULL, 2),
    (1002, 'pill', 'noun', NULL, NULL, 3),
    (1003, 'antidolorifico', 'noun', NULL, '{"standard_translation_EN": "painkiller", "standard_translation_IT": "antidolorifico", "note_culturale": "L''antidolorifico allevia il dolore."}', 1),
    (1004, 'kipulääke', 'noun', NULL, NULL, 2),
    (1005, 'painkiller', 'noun', NULL, NULL, 3),
    (1006, 'iperventilazione', 'noun', NULL, '{"standard_translation_EN": "hyperventilation", "standard_translation_IT": "iperventilazione", "note_culturale": "L''iperventilazione può essere causata dall''ansia."}', 1),
    (1007, 'hyperventilaatio', 'noun', NULL, NULL, 2),
    (1008, 'hyperventilation', 'noun', NULL, NULL, 3),
    (1009, 'infermiere', 'noun', NULL, '{"standard_translation_EN": "nurse", "standard_translation_IT": "infermiere", "note_culturale": "Professionista che assiste i medici e cura i pazienti."}', 1),
    (1010, 'sairaanhoitaja', 'noun', NULL, NULL, 2),
    (1011, 'nurse', 'noun', NULL, NULL, 3),
    (1012, 'analgesico', 'noun', NULL, '{"standard_translation_EN": "painkiller", "standard_translation_IT": "analgesico", "note_culturale": "Farmaco usato per alleviare il dolore."}', 1),
    (1013, 'resilienza', 'noun', NULL, '{"standard_translation_EN": "resilience", "standard_translation_IT": "resilienza", "note_culturale": "Capacità di superare le difficoltà."}', 1),
    (1014, 'resilienssi', 'noun', NULL, NULL, 2),
    (1015, 'resilience', 'noun', NULL, NULL, 3),
    (1016, 'mindfulness', 'noun', NULL, '{"standard_translation_EN": "mindfulness", "standard_translation_IT": "mindfulness", "note_culturale": "Pratica di prestare attenzione al momento presente."}', 1),
    (1017, 'tietoisuustaidot', 'noun', NULL, NULL, 2),
    (1018, 'mindfulness', 'noun', NULL, NULL, 3),
    (1019, 'esame', 'noun', NULL, '{"standard_translation_EN": "exam", "standard_translation_IT": "esame", "note_culturale": "In Italia, gli esami universitari possono essere orali o scritti."}', 1),
    (1020, 'tentti', 'noun', NULL, NULL, 2),
    (1021, 'exam', 'noun', NULL, NULL, 3),
    (1022, 'lezione', 'noun', NULL, '{"standard_translation_EN": "lecture", "standard_translation_IT": "lezione", "note_culturale": "Le lezioni universitarie possono essere molto affollate."}', 1),
    (1023, 'luento', 'noun', NULL, NULL, 2),
    (1024, 'lecture', 'noun', NULL, NULL, 3),
    (1025, 'mensa', 'noun', NULL, '{"standard_translation_EN": "canteen", "standard_translation_IT": "mensa", "note_culturale": "La mensa universitaria offre pasti a prezzi ridotti."}', 1),
    (1026, 'ruokala', 'noun', NULL, NULL, 2),
    (1027, 'canteen', 'noun', NULL, NULL, 3),
    (1028, 'Erasmus', 'noun', NULL, '{"standard_translation_EN": "Erasmus", "standard_translation_IT": "Erasmus", "note_culturale": "Erasmus è un programma di scambio studentesco europeo."}', 1),
    (1029, 'Erasmus', 'noun', NULL, NULL, 2),
    (1030, 'Erasmus', 'noun', NULL, NULL, 3),
    (1031, 'professore', 'noun', NULL, '{"standard_translation_EN": "professor", "standard_translation_IT": "professore", "note_culturale": "I professori universitari spesso conducono ricerche."}', 1),
    (1032, 'professori', 'noun', NULL, NULL, 2),
    (1033, 'professor', 'noun', NULL, NULL, 3),
    (1034, 'tesi', 'noun', NULL, '{"standard_translation_EN": "thesis", "standard_translation_IT": "tesi", "note_culturale": "La tesi è un lavoro di ricerca originale."}', 1),
    (1035, 'opinnäytetyö', 'noun', NULL, NULL, 2),
    (1036, 'thesis', 'noun', NULL, NULL, 3),
    (1037, 'appunti', 'noun', NULL, '{"standard_translation_EN": "notes", "standard_translation_IT": "appunti", "note_culturale": "Prendere appunti è utile per ricordare le informazioni."}', 1),
    (1038, 'muistiinpanot', 'noun', NULL, NULL, 2),
    (1039, 'notes', 'noun', NULL, NULL, 3),
    (1040, 'iscriversi', 'verb', NULL, '{"standard_translation_EN": "to enroll", "standard_translation_IT": "iscriversi", "note_culturale": "L''iscrizione all''università richiede spesso documenti specifici."}', 1),
    (1041, 'ilmoittautua', 'verb', NULL, NULL, 2),
    (1042, 'to enroll', 'verb', NULL, NULL, 3),
    (1043, 'sessione', 'noun', NULL, '{"standard_translation_EN": "semester", "standard_translation_IT": "sessione", "note_culturale": "La sessione invernale inizia a gennaio."}', 1),
    (1044, 'lukukausi', 'noun', NULL, NULL, 2),
    (1045, 'semester', 'noun', NULL, NULL, 3),
    (1046, 'ripetizioni', 'noun', NULL, '{"standard_translation_EN": "tutoring", "standard_translation_IT": "ripetizioni", "note_culturale": "Le ripetizioni possono aiutare a superare le difficoltà."}', 1),
    (1047, 'tukiopetus', 'noun', NULL, NULL, 2),
    (1048, 'tutoring', 'noun', NULL, NULL, 3),
    (1049, 'fuori corso', 'adj', NULL, '{"standard_translation_EN": "overdue (studies)", "standard_translation_IT": "fuori corso", "note_culturale": "Essere fuori corso significa non aver terminato gli studi nei tempi previsti."}', 1),
    (1050, 'jäljessä opinnoista', 'adj', NULL, NULL, 2),
    (1051, 'overdue (studies)', 'adj', NULL, NULL, 3),
    (1052, 'matricola', 'noun', NULL, '{"standard_translation_EN": "freshman", "standard_translation_IT": "matricola", "note_culturale": "La matricola è uno studente al primo anno di università."}', 1),
    (1053, 'fuksi', 'noun', NULL, NULL, 2),
    (1054, 'freshman', 'noun', NULL, NULL, 3),
    (1055, 'laurea', 'noun', NULL, '{"standard_translation_EN": "degree", "standard_translation_IT": "laurea", "note_culturale": "La laurea triennale dura tre anni."}', 1),
    (1056, 'tutkinto', 'noun', NULL, NULL, 2),
    (1057, 'degree', 'noun', NULL, NULL, 3),
    (1058, 'borsa di studio', 'noun', NULL, '{"standard_translation_EN": "scholarship", "standard_translation_IT": "borsa di studio", "note_culturale": "Le borse di studio aiutano gli studenti a pagare le tasse universitarie."}', 1),
    (1059, 'apuraha', 'noun', NULL, NULL, 2),
    (1060, 'scholarship', 'noun', NULL, NULL, 3),
    (1061, 'aula', 'noun', NULL, '{"standard_translation_EN": "classroom", "standard_translation_IT": "aula", "note_culturale": "Le aule sono dotate di lavagna e banchi."}', 1),
    (1062, 'luokkahuone', 'noun', NULL, NULL, 2),
    (1063, 'classroom', 'noun', NULL, NULL, 3),
    (1064, 'compito', 'noun', NULL, '{"standard_translation_EN": "assignment", "standard_translation_IT": "compito", "note_culturale": "I compiti a casa sono importanti per l''apprendimento."}', 1),
    (1065, 'assignment', 'noun', NULL, NULL, 3),
    (1066, 'iscrizione', 'noun', NULL, '{"standard_translation_EN": "registration", "standard_translation_IT": "iscrizione", "note_culturale": "L''iscrizione all''università è obbligatoria."}', 1),
    (1067, 'rekisteröinti', 'noun', NULL, NULL, 2),
    (1068, 'registration', 'noun', NULL, NULL, 3),
    (1069, 'sessione di laurea', 'noun', NULL, '{"standard_translation_EN": "graduation ceremony", "standard_translation_IT": "sessione di laurea", "note_culturale": "La sessione di laurea è un momento importante per gli studenti."}', 1),
    (1070, 'valmistumisistunto', 'noun', NULL, NULL, 2)
ON CONFLICT DO NOTHING;
SELECT setval('lemma_lemma_id_seq', 1070);

INSERT INTO morpho_form (surface_form, grammar_json, lemma_id) VALUES
    ('Totuudenjälkeinen', NULL, 487),
    ('aika', NULL, 487),
    ('Tunteet', NULL, 487),
    ('>', NULL, 487),
    ('faktat', NULL, 487),
    ('Emotions', NULL, 488),
    ('>', NULL, 488),
    ('facts', NULL, 488),
    ('Echo', NULL, 489),
    ('chamber', NULL, 489),
    ('Camera', NULL, 489),
    ('di', NULL, 489),
    ('risonanza', NULL, 489),
    ('Vahvistuskupla', NULL, 490),
    ('Echo', NULL, 491),
    ('chamber', NULL, 491),
    ('Confirmation', NULL, 491),
    ('bias', NULL, 491),
    ('Provocatore', NULL, 492),
    ('online', NULL, 492),
    ('Provosoija', NULL, 493),
    ('verkossa', NULL, 493),
    ('Online', NULL, 494),
    ('provoker', NULL, 494),
    ('Rivelazione', NULL, 495),
    ('dati', NULL, 495),
    ('personali', NULL, 495),
    ('Henkilötietojen', NULL, 496),
    ('paljastaminen', NULL, 496),
    ('Revealing', NULL, 497),
    ('personal', NULL, 497),
    ('data', NULL, 497),
    ('Falsa', NULL, 498),
    ('identità', NULL, 498),
    ('online', NULL, 498),
    ('Väärä', NULL, 499),
    ('henkilöllisyys', NULL, 499),
    ('verkossa', NULL, 499),
    ('Fake', NULL, 500),
    ('online', NULL, 500),
    ('identity', NULL, 500),
    ('Falsificazione', NULL, 501),
    ('digitale', NULL, 501),
    ('Digitaalinen', NULL, 502),
    ('väärennös', NULL, 502),
    ('Digital', NULL, 503),
    ('forgery', NULL, 503),
    ('Permesso', NULL, 504),
    ('Lupa', NULL, 505),
    ('Permission', NULL, 506),
    ('Chiave', NULL, 507),
    ('d''accesso', NULL, 507),
    ('Pääsyavain', NULL, 508),
    ('Access', NULL, 509),
    ('key', NULL, 509),
    ('Controllo', NULL, 510),
    ('Tarkistus', NULL, 511),
    ('Check', NULL, 512),
    ('Non', NULL, 513),
    ('identificabilità', NULL, 513),
    ('Nimettömyys', NULL, 514),
    ('Unidentifiability', NULL, 515),
    ('Intelligenza', NULL, 516),
    ('artificiale', NULL, 516),
    ('IA', NULL, 516),
    ('AI', NULL, 517),
    ('Artificial', NULL, 518),
    ('intelligence', NULL, 518),
    ('AI', NULL, 518),
    ('Filter', NULL, 519),
    ('bubble', NULL, 519),
    ('Bolla', NULL, 519),
    ('di', NULL, 519),
    ('filtraggio', NULL, 519),
    ('Suodatinvääristymä', NULL, 520),
    ('Filter', NULL, 521),
    ('bubble', NULL, 521),
    ('Filtering', NULL, 521),
    ('bubble', NULL, 521),
    ('Condivisione', NULL, 522),
    ('eccessiva', NULL, 522),
    ('genitori', NULL, 522),
    ('Liiallinen', NULL, 523),
    ('jakaminen', NULL, 523),
    ('vanhempien', NULL, 523),
    ('toimesta', NULL, 523),
    ('Excessive', NULL, 524),
    ('sharing', NULL, 524),
    ('by', NULL, 524),
    ('parents', NULL, 524),
    ('Open', NULL, 525),
    ('source', NULL, 525),
    ('Codice', NULL, 525),
    ('aperto', NULL, 525),
    ('Avoin', NULL, 526),
    ('lähdekoodi', NULL, 526),
    ('Avoimen', NULL, 526),
    ('lähdekoodin', NULL, 526),
    ('Open', NULL, 527),
    ('source', NULL, 527),
    ('Open', NULL, 527),
    ('code', NULL, 527),
    ('nucleo', NULL, 528),
    ('familiare', NULL, 528),
    ('parenti', NULL, 528),
    ('suku', NULL, 529),
    ('lähipiiri', NULL, 529),
    ('kin', NULL, 530),
    ('relatives', NULL, 530),
    ('padre', NULL, 531),
    ('madre', NULL, 531),
    ('isä', NULL, 532),
    ('äiti', NULL, 532),
    ('father', NULL, 533),
    ('mother', NULL, 533),
    ('bambino', NULL, 534),
    ('prole', NULL, 534),
    ('tenava', NULL, 535),
    ('mukula', NULL, 535),
    ('kid', NULL, 536),
    ('offspring', NULL, 536),
    ('germanello', NULL, 537),
    ('fra''', NULL, 537),
    ('isoveli', NULL, 538),
    ('pikkuveli', NULL, 538),
    ('bro', NULL, 539),
    ('sibling', NULL, 539),
    ('germanella', NULL, 540),
    ('socia', NULL, 540),
    ('isosko', NULL, 541),
    ('pikkusisko', NULL, 541),
    ('sis', NULL, 542),
    ('sibling', NULL, 542),
    ('avo', NULL, 543),
    ('nonnino', NULL, 543),
    ('ukki', NULL, 544),
    ('vaari', NULL, 544),
    ('grandpa', NULL, 545),
    ('gramps', NULL, 545),
    ('ava', NULL, 546),
    ('nonnina', NULL, 546),
    ('mummo', NULL, 547),
    ('mummi', NULL, 547),
    ('grandma', NULL, 548),
    ('grannie', NULL, 548),
    ('ziozzo', NULL, 549),
    ('eno', NULL, 550),
    ('unky', NULL, 551),
    ('ziazza', NULL, 552),
    ('tante', NULL, 553),
    ('aunty', NULL, 554),
    ('di', NULL, 555),
    ('primo', NULL, 555),
    ('grado', NULL, 555),
    ('pikkuserkku', NULL, 556),
    ('first', NULL, 557),
    ('sposo', NULL, 558),
    ('consorte', NULL, 558),
    ('mies', NULL, 559),
    ('puoliso', NULL, 559),
    ('hubby', NULL, 560),
    ('spouse', NULL, 560),
    ('sposa', NULL, 561),
    ('consorte', NULL, 561),
    ('emäntä', NULL, 562),
    ('puoliso', NULL, 562),
    ('wifey', NULL, 563),
    ('spouse', NULL, 563),
    ('compagno', NULL, 564),
    ('socio', NULL, 564),
    ('kaveri', NULL, 565),
    ('ystävä', NULL, 565),
    ('mate', NULL, 566),
    ('companion', NULL, 566),
    ('vivere', NULL, 567),
    ('insieme', NULL, 567),
    ('yhdessä', NULL, 568),
    ('asuminen', NULL, 568),
    ('living', NULL, 569),
    ('together', NULL, 569),
    ('nozze', NULL, 570),
    ('sposalizio', NULL, 570),
    ('vihkiminen', NULL, 571),
    ('naimisiinmeno', NULL, 571),
    ('wedding', NULL, 572),
    ('matrimony', NULL, 572),
    ('separazione', NULL, 573),
    ('eron', NULL, 574),
    ('ottaminen', NULL, 574),
    ('separation', NULL, 575),
    ('genitore', NULL, 576),
    ('solo', NULL, 576),
    ('yksinäinen', NULL, 577),
    ('vanhempi', NULL, 577),
    ('lone', NULL, 578),
    ('parent', NULL, 578),
    ('famiglia', NULL, 579),
    ('ricostituita', NULL, 579),
    ('yhdistetty', NULL, 580),
    ('perhe', NULL, 580),
    ('stepfamily', NULL, 581),
    ('adottare', NULL, 582),
    ('ottaa', NULL, 583),
    ('lapsekseen', NULL, 583),
    ('to', NULL, 584),
    ('adopt', NULL, 584),
    ('congiunto', NULL, 585),
    ('heimolainen', NULL, 586),
    ('kin', NULL, 587),
    ('lascito', NULL, 588),
    ('jättö', NULL, 589),
    ('legacy', NULL, 590),
    ('capirsi', NULL, 591),
    ('sopia', NULL, 592),
    ('to', NULL, 593),
    ('agree', NULL, 593),
    ('discutere', NULL, 594),
    ('väitellä', NULL, 595),
    ('to', NULL, 596),
    ('quarrel', NULL, 596),
    ('fare', NULL, 597),
    ('pace', NULL, 597),
    ('tehdä', NULL, 598),
    ('sovinto', NULL, 598),
    ('to', NULL, 599),
    ('make', NULL, 599),
    ('up', NULL, 599),
    ('collega', NULL, 600),
    ('di', NULL, 600),
    ('appartamento', NULL, 600),
    ('asuntokaveri', NULL, 601),
    ('flatmate', NULL, 602),
    ('coabitare', NULL, 603),
    ('yhdessäolo', NULL, 604),
    ('to', NULL, 605),
    ('cohabit', NULL, 605),
    ('vincolo', NULL, 606),
    ('suhde', NULL, 607),
    ('tie', NULL, 608),
    ('aiuto', NULL, 609),
    ('apu', NULL, 610),
    ('help', NULL, 611),
    ('assistenza', NULL, 612),
    ('huolenpito', NULL, 613),
    ('nurturing', NULL, 614),
    ('infedeltà', NULL, 615),
    ('uskottomuus', NULL, 616),
    ('infidelity', NULL, 617),
    ('promesso', NULL, 618),
    ('sposo', NULL, 618),
    ('sulhanen', NULL, 619),
    ('betrothed', NULL, 620),
    ('promessa', NULL, 621),
    ('sposa', NULL, 621),
    ('betrothed', NULL, 622),
    ('stima', NULL, 623),
    ('arvostus', NULL, 624),
    ('esteem', NULL, 625),
    ('tenerezza', NULL, 626),
    ('hellyys', NULL, 627),
    ('tenderness', NULL, 628),
    ('Kulta', NULL, 629),
    ('BF', NULL, 630),
    ('Beibe', NULL, 631),
    ('GF', NULL, 632),
    ('Ero', NULL, 633),
    ('Bileet', NULL, 634),
    ('Nuptials', NULL, 635),
    ('Spese', NULL, 636),
    ('Kulut', NULL, 637),
    ('Expenses', NULL, 638),
    ('Dividere', NULL, 639),
    ('Osallistua', NULL, 640),
    ('Split', NULL, 641),
    ('Dovere', NULL, 642),
    ('Velvollisuus', NULL, 643),
    ('Duty', NULL, 644),
    ('Accordo', NULL, 645),
    ('Sopu', NULL, 646),
    ('Agreement', NULL, 647),
    ('Quarrel', NULL, 648),
    ('Stimare', NULL, 649),
    ('Arvostaa', NULL, 650),
    ('Aiutare', NULL, 651),
    ('Auttaa', NULL, 652),
    ('Età', NULL, 653),
    ('Ikäpolvi', NULL, 654),
    ('Age', NULL, 655),
    ('group', NULL, 655),
    ('Yhteys', NULL, 656),
    ('Crescere', NULL, 657),
    ('Hoitaa', NULL, 658),
    ('Bring', NULL, 659),
    ('up', NULL, 659),
    ('Principi', NULL, 660),
    ('Periaatteet', NULL, 661),
    ('Principles', NULL, 662),
    ('Usi', NULL, 663),
    ('Tavat', NULL, 664),
    ('Customs', NULL, 665),
    ('Congiunti', NULL, 666),
    ('Heimo', NULL, 667),
    ('Kin', NULL, 668),
    ('Altruista', NULL, 669),
    ('Avokätinen', NULL, 670),
    ('Giving', NULL, 671),
    ('Caloroso', NULL, 672),
    ('Lämmin', NULL, 673),
    ('Loving', NULL, 674),
    ('Invidioso', NULL, 675),
    ('Kateellinen', NULL, 676),
    ('Envious', NULL, 677),
    ('Lasciarsi', NULL, 678),
    ('Separarsi', NULL, 678),
    ('Jättää', NULL, 679),
    ('Hylätä', NULL, 679),
    ('Split', NULL, 680),
    ('up', NULL, 680),
    ('Break', NULL, 680),
    ('up', NULL, 680),
    ('Prendere', NULL, 681),
    ('in', NULL, 681),
    ('adozione', NULL, 681),
    ('Ottaa', NULL, 682),
    ('lapseksi', NULL, 682),
    ('Take', NULL, 683),
    ('in', NULL, 683),
    ('Sijoittaa', NULL, 684),
    ('Take', NULL, 685),
    ('into', NULL, 685),
    ('care', NULL, 685),
    ('Libero', NULL, 686),
    ('Solo', NULL, 686),
    ('Yksin', NULL, 687),
    ('Vapaa', NULL, 687),
    ('Free', NULL, 688),
    ('Unattached', NULL, 688),
    ('Sukulaiset', NULL, 689),
    ('Relatives', NULL, 690),
    ('Amare', NULL, 691),
    ('Rakastaa', NULL, 692),
    ('To', NULL, 693),
    ('love', NULL, 693),
    ('Famiglia', NULL, 694),
    ('omogenitoriale', NULL, 694),
    ('Homoperhe', NULL, 695),
    ('Same-sex', NULL, 696),
    ('family', NULL, 696),
    ('Genitori', NULL, 697),
    ('del', NULL, 697),
    ('coniuge', NULL, 697),
    ('Apuvanhemmat', NULL, 698),
    ('Parents-in-law', NULL, 699),
    ('Figlio', NULL, 700),
    ('del', NULL, 700),
    ('figlio/a', NULL, 700),
    ('Lasten', NULL, 701),
    ('lapsi', NULL, 701),
    ('Child', NULL, 702),
    ('of', NULL, 702),
    ('a', NULL, 702),
    ('child', NULL, 702),
    ('Senza', NULL, 703),
    ('genitori', NULL, 703),
    ('Vanhempien', NULL, 704),
    ('menettänyt', NULL, 704),
    ('Parentless', NULL, 705),
    ('Diventare', NULL, 706),
    ('adulto', NULL, 706),
    ('Aikuistua', NULL, 707),
    ('To', NULL, 708),
    ('become', NULL, 708),
    ('an', NULL, 708),
    ('adult', NULL, 708),
    ('Incinta', NULL, 709),
    ('Odottava', NULL, 710),
    ('Expecting', NULL, 711),
    ('Festività', NULL, 712),
    ('natalizia', NULL, 712),
    ('Jouluaatto', NULL, 713),
    ('Xmas', NULL, 714),
    ('Resurrezione', NULL, 715),
    ('Pääsiäissunnuntai', NULL, 716),
    ('Sunday', NULL, 717),
    ('Assunzione', NULL, 718),
    ('Elokuun', NULL, 719),
    ('puoliväli', NULL, 719),
    ('Marian', NULL, 719),
    ('taivaaseenastumisen', NULL, 719),
    ('päivä', NULL, 719),
    ('Mid-August', NULL, 720),
    ('holiday', NULL, 720),
    ('Assumption', NULL, 720),
    ('of', NULL, 720),
    ('Mary', NULL, 720),
    ('Martedì', NULL, 721),
    ('Grasso', NULL, 721),
    ('Laskiaistiistai', NULL, 722),
    ('Mardi', NULL, 723),
    ('Gras', NULL, 723),
    ('Epifania', NULL, 724),
    ('Kolmen', NULL, 725),
    ('kuninkaan', NULL, 725),
    ('päivä', NULL, 725),
    ('Twelfth', NULL, 726),
    ('Night', NULL, 726),
    ('Usanza', NULL, 727),
    ('Tapa', NULL, 728),
    ('Custom', NULL, 729),
    ('Festeggiamento', NULL, 730),
    ('Tilaisuus', NULL, 731),
    ('Festivity', NULL, 732),
    ('Grande', NULL, 733),
    ('cena', NULL, 733),
    ('Jouluateria', NULL, 734),
    ('Festive', NULL, 735),
    ('Dinner', NULL, 735),
    ('Christmas', NULL, 735),
    ('Supper', NULL, 735),
    ('Fuochi', NULL, 736),
    ('d''artificio', NULL, 736),
    ('Spettacolo', NULL, 736),
    ('pirotecnico', NULL, 736),
    ('Raketit', NULL, 737),
    ('Pyrotechnics', NULL, 738),
    ('Festa', NULL, 739),
    ('paesana', NULL, 739),
    ('Paikallinen', NULL, 740),
    ('juhla', NULL, 740),
    ('Kyläjuhla', NULL, 740),
    ('Local', NULL, 741),
    ('Festival', NULL, 741),
    ('Village', NULL, 741),
    ('Fair', NULL, 741),
    ('Gioco', NULL, 742),
    ('di', NULL, 742),
    ('Natale', NULL, 742),
    ('Joulupeli', NULL, 743),
    ('Christmas', NULL, 744),
    ('game', NULL, 744),
    ('impiego', NULL, 745),
    ('virka', NULL, 746),
    ('work', NULL, 747),
    ('intervista', NULL, 748),
    ('työhaastattelu', NULL, 749),
    ('meeting', NULL, 750),
    ('salario', NULL, 751),
    ('kuukausipalkka', NULL, 752),
    ('wage', NULL, 753),
    ('percorso', NULL, 754),
    ('professionale', NULL, 754),
    ('työura', NULL, 755),
    ('profession', NULL, 756),
    ('datore', NULL, 757),
    ('di', NULL, 757),
    ('lavoro', NULL, 757),
    ('principale', NULL, 757),
    ('työntekijän', NULL, 758),
    ('palkkaaja', NULL, 758),
    ('boss', NULL, 759),
    ('impiegato', NULL, 760),
    ('työssäkäyvä', NULL, 761),
    ('worker', NULL, 762),
    ('accordo', NULL, 763),
    ('työsopimus', NULL, 764),
    ('agreement', NULL, 765),
    ('CV', NULL, 766),
    ('CV', NULL, 767),
    ('CV', NULL, 768),
    ('compito', NULL, 769),
    ('työtehtävä', NULL, 770),
    ('duty', NULL, 771),
    ('avanzamento', NULL, 772),
    ('eteneminen', NULL, 773),
    ('advancement', NULL, 774),
    ('espulsione', NULL, 775),
    ('potkut', NULL, 776),
    ('firing', NULL, 777),
    ('abbandono', NULL, 778),
    ('virasta', NULL, 779),
    ('collaboratore', NULL, 780),
    ('työtoveri', NULL, 781),
    ('coworker', NULL, 782),
    ('tavolo', NULL, 783),
    ('da', NULL, 783),
    ('lavoro', NULL, 783),
    ('kirjoituspöytä', NULL, 784),
    ('work', NULL, 785),
    ('table', NULL, 785),
    ('incontro', NULL, 786),
    ('tapaaminen', NULL, 787),
    ('gathering', NULL, 788),
    ('takaraja', NULL, 789),
    ('due', NULL, 790),
    ('date', NULL, 790),
    ('scopo', NULL, 791),
    ('päämäärä', NULL, 792),
    ('aim', NULL, 793),
    ('ambito', NULL, 794),
    ('toimiala', NULL, 795),
    ('field', NULL, 796),
    ('risorse', NULL, 797),
    ('umane', NULL, 797),
    ('personale', NULL, 797),
    ('HR', NULL, 798),
    ('human', NULL, 799),
    ('resources', NULL, 799),
    ('HR', NULL, 799),
    ('impresa', NULL, 800),
    ('firma', NULL, 801),
    ('firm', NULL, 802),
    ('orario', NULL, 803),
    ('di', NULL, 803),
    ('lavoro', NULL, 803),
    ('ore', NULL, 803),
    ('lavorative', NULL, 803),
    ('työvuoro', NULL, 804),
    ('working', NULL, 805),
    ('hours', NULL, 805),
    ('work', NULL, 805),
    ('schedule', NULL, 805),
    ('vantaggio', NULL, 806),
    ('lisäetu', NULL, 807),
    ('perk', NULL, 808),
    ('network', NULL, 809),
    ('kontaktiverkosto', NULL, 810),
    ('connections', NULL, 811),
    ('programma', NULL, 812),
    ('työaika', NULL, 813),
    ('timetable', NULL, 814),
    ('addestramento', NULL, 815),
    ('harjoittelu', NULL, 816),
    ('education', NULL, 817),
    ('mestiere', NULL, 818),
    ('toimi', NULL, 819),
    ('occupation', NULL, 820),
    ('abilità', NULL, 821),
    ('taito', NULL, 822),
    ('ability', NULL, 823),
    ('gruppo', NULL, 824),
    ('di', NULL, 824),
    ('lavoro', NULL, 824),
    ('työryhmä', NULL, 825),
    ('work', NULL, 826),
    ('group', NULL, 826),
    ('ordine', NULL, 827),
    ('arvojärjestys', NULL, 828),
    ('ranking', NULL, 829),
    ('cooperazione', NULL, 830),
    ('avunanto', NULL, 831),
    ('cooperation', NULL, 832),
    ('pianta', NULL, 833),
    ('kasvi', NULL, 834),
    ('plant', NULL, 835),
    ('corso', NULL, 836),
    ('d''acqua', NULL, 836),
    ('virta', NULL, 837),
    ('stream', NULL, 838),
    ('creatura', NULL, 839),
    ('olento', NULL, 840),
    ('creature', NULL, 841),
    ('bocciolo', NULL, 842),
    ('kukkanen', NULL, 843),
    ('blossom', NULL, 844),
    ('stagione', NULL, 845),
    ('calda', NULL, 845),
    ('lämmin', NULL, 846),
    ('vuodenaika', NULL, 846),
    ('warm', NULL, 847),
    ('season', NULL, 847),
    ('stagione', NULL, 848),
    ('fredda', NULL, 848),
    ('kylmä', NULL, 849),
    ('vuodenaika', NULL, 849),
    ('cold', NULL, 850),
    ('season', NULL, 850),
    ('scienza', NULL, 851),
    ('ambientale', NULL, 851),
    ('ympäristötiede', NULL, 852),
    ('environmental', NULL, 853),
    ('science', NULL, 853),
    ('varietà', NULL, 854),
    ('biologica', NULL, 854),
    ('biologinen', NULL, 855),
    ('monimuotoisuus', NULL, 855),
    ('biological', NULL, 856),
    ('diversity', NULL, 856),
    ('sistema', NULL, 857),
    ('ecologico', NULL, 857),
    ('ekologinen', NULL, 858),
    ('järjestelmä', NULL, 858),
    ('ecological', NULL, 859),
    ('system', NULL, 859),
    ('pascolo', NULL, 860),
    ('laidun', NULL, 861),
    ('pasture', NULL, 862),
    ('bosco', NULL, 863),
    ('korpi', NULL, 864),
    ('woods', NULL, 865),
    ('stagione', NULL, 866),
    ('delle', NULL, 866),
    ('foglie', NULL, 866),
    ('cadenti', NULL, 866),
    ('lehtien', NULL, 867),
    ('putoamisen', NULL, 867),
    ('aika', NULL, 867),
    ('fall', NULL, 868),
    ('season', NULL, 868),
    ('stagione', NULL, 869),
    ('del', NULL, 869),
    ('risveglio', NULL, 869),
    ('heräämisen', NULL, 870),
    ('aika', NULL, 870),
    ('awakening', NULL, 871),
    ('season', NULL, 871),
    ('condizioni', NULL, 872),
    ('atmosferiche', NULL, 872),
    ('sääolosuhteet', NULL, 873),
    ('weather', NULL, 874),
    ('conditions', NULL, 874),
    ('contaminazione', NULL, 875),
    ('likaantuminen', NULL, 876),
    ('contamination', NULL, 877),
    ('energia', NULL, 878),
    ('solare', NULL, 878),
    ('energia', NULL, 878),
    ('del', NULL, 878),
    ('sole', NULL, 878),
    ('auringon', NULL, 879),
    ('energia', NULL, 879),
    ('solar', NULL, 880),
    ('energy', NULL, 880),
    ('sun''s', NULL, 880),
    ('energy', NULL, 880),
    ('riscaldamento', NULL, 881),
    ('globale', NULL, 881),
    ('surriscaldamento', NULL, 881),
    ('climatico', NULL, 881),
    ('ilmaston', NULL, 882),
    ('lämpeneminen', NULL, 882),
    ('globaali', NULL, 882),
    ('lämpeneminen', NULL, 882),
    ('global', NULL, 883),
    ('warming', NULL, 883),
    ('climate', NULL, 883),
    ('change', NULL, 883),
    ('tutela', NULL, 884),
    ('ambientale', NULL, 884),
    ('ympäristönsuojelu', NULL, 885),
    ('environmental', NULL, 886),
    ('protection', NULL, 886),
    ('vita', NULL, 887),
    ('animale', NULL, 887),
    ('eläinkunta', NULL, 888),
    ('animal', NULL, 889),
    ('life', NULL, 889),
    ('Astro', NULL, 890),
    ('Päivä', NULL, 891),
    ('Star', NULL, 892),
    ('Acquazzone', NULL, 893),
    ('Vesisade', NULL, 894),
    ('Shower', NULL, 895),
    ('Suolo', NULL, 896),
    ('Maaperä', NULL, 897),
    ('Soil', NULL, 898),
    ('Aria', NULL, 899),
    ('Ilmavirta', NULL, 900),
    ('Airflow', NULL, 901),
    ('Bacino', NULL, 902),
    ('Lampare', NULL, 903),
    ('Basin', NULL, 904),
    ('Ecocompatibilità', NULL, 905),
    ('Ympäristöystävällisyys', NULL, 906),
    ('Eco-friendliness', NULL, 907),
    ('Fonte', NULL, 908),
    ('Lähde', NULL, 909),
    ('Source', NULL, 910),
    ('Säilyttäminen', NULL, 911),
    ('Congestione', NULL, 912),
    ('nasale', NULL, 912),
    ('Nuha', NULL, 913),
    ('Common', NULL, 914),
    ('Temperatura', NULL, 915),
    ('alta', NULL, 915),
    ('Lämpö', NULL, 916),
    ('High', NULL, 917),
    ('temperature', NULL, 917),
    ('Dottore', NULL, 918),
    ('Tohtori', NULL, 919),
    ('Physician', NULL, 920),
    ('Medicina', NULL, 921),
    ('Rohdos', NULL, 922),
    ('Drug', NULL, 923),
    ('Tensione', NULL, 924),
    ('Jännitys', NULL, 925),
    ('Strain', NULL, 926),
    ('Rilassamento', NULL, 927),
    ('Lepo', NULL, 928),
    ('Rest', NULL, 929),
    ('Segnale', NULL, 930),
    ('Merkki', NULL, 931),
    ('Sign', NULL, 932),
    ('Cura', NULL, 933),
    ('Hoito', NULL, 934),
    ('Treatment', NULL, 935),
    ('Profilassi', NULL, 936),
    ('Ennaltaehkäisy', NULL, 937),
    ('Prophylaxis', NULL, 938),
    ('Mancanza', NULL, 939),
    ('di', NULL, 939),
    ('sonno', NULL, 939),
    ('Unihäiriö', NULL, 940),
    ('Sleeplessness', NULL, 941),
    ('Supplemento', NULL, 942),
    ('Lisäravinne', NULL, 943),
    ('Dietary', NULL, 944),
    ('Terapia', NULL, 945),
    ('manuale', NULL, 945),
    ('Hively', NULL, 946),
    ('Bodywork', NULL, 947),
    ('Immunizzazione', NULL, 948),
    ('Immunisaatio', NULL, 949),
    ('Immunization', NULL, 950),
    ('Regime', NULL, 951),
    ('alimentare', NULL, 951),
    ('Dieetti', NULL, 952),
    ('Eating', NULL, 953),
    ('plan', NULL, 953),
    ('Esercizio', NULL, 954),
    ('fisico', NULL, 954),
    ('Attività', NULL, 954),
    ('fisica', NULL, 954),
    ('Urheilu', NULL, 955),
    ('Physical', NULL, 956),
    ('activity', NULL, 956),
    ('Pronto', NULL, 957),
    ('soccorso', NULL, 957),
    ('Emergenza', NULL, 957),
    ('medica', NULL, 957),
    ('Hätäapu', NULL, 958),
    ('First', NULL, 959),
    ('aid', NULL, 959),
    ('Emergency', NULL, 959),
    ('care', NULL, 959),
    ('Portamento', NULL, 960),
    ('Asento', NULL, 961),
    ('Stance', NULL, 962),
    ('contemplazione', NULL, 963),
    ('mietiskely', NULL, 964),
    ('contemplation', NULL, 965),
    ('accertamento', NULL, 966),
    ('toteaminen', NULL, 967),
    ('assessment', NULL, 968),
    ('script', NULL, 969),
    ('sofferenza', NULL, 970),
    ('särky', NULL, 971),
    ('ache', NULL, 972),
    ('esaurimento', NULL, 973),
    ('uupumus', NULL, 974),
    ('exhaustion', NULL, 975),
    ('hatha', NULL, 976),
    ('hathajooga', NULL, 977),
    ('hatha', NULL, 978),
    ('farmaco', NULL, 979),
    ('lääke', NULL, 980),
    ('medicine', NULL, 981),
    ('colpo', NULL, 982),
    ('di', NULL, 982),
    ('yskänkohtaus', NULL, 983),
    ('hacking', NULL, 984),
    ('specialista', NULL, 985),
    ('della', NULL, 985),
    ('pelle', NULL, 985),
    ('ihotauti', NULL, 986),
    ('spesialisti', NULL, 986),
    ('skin', NULL, 987),
    ('specialist', NULL, 987),
    ('analgesico', NULL, 988),
    ('kipulääke', NULL, 989),
    ('painkiller', NULL, 990),
    ('specialista', NULL, 991),
    ('del', NULL, 991),
    ('cuore', NULL, 991),
    ('sydänspesialisti', NULL, 992),
    ('heart', NULL, 993),
    ('specialist', NULL, 993),
    ('pressione', NULL, 994),
    ('alta', NULL, 994),
    ('ipertensione', NULL, 994),
    ('korkea', NULL, 995),
    ('verenpaine', NULL, 995),
    ('hypertensio', NULL, 995),
    ('high', NULL, 996),
    ('blood', NULL, 996),
    ('pressure', NULL, 996),
    ('hypertension', NULL, 996),
    ('centro', NULL, 997),
    ('benessere', NULL, 997),
    ('hyvinvointikeskus', NULL, 998),
    ('wellness', NULL, 999),
    ('center', NULL, 999),
    ('Compressa', NULL, 1000),
    ('Tabletti', NULL, 1001),
    ('Tablet', NULL, 1002),
    ('Analgesico', NULL, 1003),
    ('Särkylääke', NULL, 1004),
    ('Analgesic', NULL, 1005),
    ('Respirazione', NULL, 1006),
    ('accelerata', NULL, 1006),
    ('Nopea', NULL, 1007),
    ('hengitys', NULL, 1007),
    ('Rapid', NULL, 1008),
    ('breathing', NULL, 1008),
    ('assistente', NULL, 1009),
    ('medico', NULL, 1009),
    ('hoitaja', NULL, 1010),
    ('medical', NULL, 1011),
    ('assistant', NULL, 1011),
    ('antidolorifico', NULL, 1012),
    ('capacità', NULL, 1013),
    ('di', NULL, 1013),
    ('recupero', NULL, 1013),
    ('palautumiskyky', NULL, 1014),
    ('recovery', NULL, 1015),
    ('ability', NULL, 1015),
    ('consapevolezza', NULL, 1016),
    ('läsnäolo', NULL, 1017),
    ('awareness', NULL, 1018),
    ('prova', NULL, 1019),
    ('interrogazione', NULL, 1019)
ON CONFLICT DO NOTHING;

COMMIT;