-- seed_03_1_lemma.sql - Author: Stefania Julin
-- lemma part 1/3 (535 rows) + morpho_form (830 rows)
BEGIN;

INSERT INTO lemma (lemma_id, text_root, grammatical_category, frequency_rank, interference_json, variant_id) VALUES
    (1, 'Montagna', 'noun', NULL, '{"standard_translation_EN": "Mountain", "standard_translation_IT": "Montagna", "note_culturale": "Elevazione naturale del terreno."}', 1),
    (2, 'Vuori', 'noun', NULL, NULL, 2),
    (3, 'Mountain', 'noun', NULL, NULL, 3),
    (4, 'appartamento', 'noun', NULL, '{"standard_translation_EN": "apartment", "standard_translation_IT": "appartamento", "note_culturale": "In Italia, la dimensione degli appartamenti varia molto a seconda della città."}', 1),
    (5, 'asunto', 'noun', NULL, NULL, 2),
    (6, 'apartment', 'noun', NULL, NULL, 3),
    (7, 'affitto', 'noun', NULL, '{"standard_translation_EN": "rent", "standard_translation_IT": "affitto", "note_culturale": "Il costo dell''affitto può variare notevolmente a seconda della zona."}', 1),
    (8, 'vuokra', 'noun', NULL, NULL, 2),
    (9, 'rent', 'noun', NULL, NULL, 3),
    (10, 'bolletta', 'noun', NULL, '{"standard_translation_EN": "bill", "standard_translation_IT": "bolletta", "note_culturale": "Le bollette includono spese per luce, gas, acqua, etc."}', 1),
    (11, 'lasku', 'noun', NULL, NULL, 2),
    (12, 'bill', 'noun', NULL, NULL, 3),
    (13, 'lavatrice', 'noun', NULL, '{"standard_translation_EN": "washing machine", "standard_translation_IT": "lavatrice", "note_culturale": "La lavatrice è un elettrodomestico essenziale in molte case."}', 1),
    (14, 'pesukone', 'noun', NULL, NULL, 2),
    (15, 'washing machine', 'noun', NULL, NULL, 3),
    (16, 'frigorifero', 'noun', NULL, '{"standard_translation_EN": "refrigerator", "standard_translation_IT": "frigorifero", "note_culturale": "Il frigorifero mantiene il cibo fresco."}', 1),
    (17, 'jääkaappi', 'noun', NULL, NULL, 2),
    (18, 'refrigerator', 'noun', NULL, NULL, 3),
    (19, 'fornello', 'noun', NULL, '{"standard_translation_EN": "stove", "standard_translation_IT": "fornello", "note_culturale": "Si usa il fornello per cucinare."}', 1),
    (20, 'liesi', 'noun', NULL, NULL, 2),
    (21, 'stove', 'noun', NULL, NULL, 3),
    (22, 'tavolo', 'noun', NULL, '{"standard_translation_EN": "table", "standard_translation_IT": "tavolo", "note_culturale": "Il tavolo è un elemento essenziale in sala da pranzo."}', 1),
    (23, 'pöytä', 'noun', NULL, NULL, 2),
    (24, 'table', 'noun', NULL, NULL, 3),
    (25, 'sedia', 'noun', NULL, '{"standard_translation_EN": "chair", "standard_translation_IT": "sedia", "note_culturale": "Ci si siede sulla sedia."}', 1),
    (26, 'tuoli', 'noun', NULL, NULL, 2),
    (27, 'chair', 'noun', NULL, NULL, 3),
    (28, 'letto', 'noun', NULL, '{"standard_translation_EN": "bed", "standard_translation_IT": "letto", "note_culturale": "Si dorme nel letto."}', 1),
    (29, 'sänky', 'noun', NULL, NULL, 2),
    (30, 'bed', 'noun', NULL, NULL, 3),
    (31, 'cuscino', 'noun', NULL, '{"standard_translation_EN": "pillow", "standard_translation_IT": "cuscino", "note_culturale": "Si appoggia la testa sul cuscino."}', 1),
    (32, 'tyyny', 'noun', NULL, NULL, 2),
    (33, 'pillow', 'noun', NULL, NULL, 3),
    (34, 'coperta', 'noun', NULL, '{"standard_translation_EN": "blanket", "standard_translation_IT": "coperta", "note_culturale": "La coperta tiene caldo."}', 1),
    (35, 'peitto', 'noun', NULL, NULL, 2),
    (36, 'blanket', 'noun', NULL, NULL, 3),
    (37, 'finestra', 'noun', NULL, '{"standard_translation_EN": "window", "standard_translation_IT": "finestra", "note_culturale": "La finestra permette alla luce di entrare."}', 1),
    (38, 'ikkuna', 'noun', NULL, NULL, 2),
    (39, 'window', 'noun', NULL, NULL, 3),
    (40, 'porta', 'noun', NULL, '{"standard_translation_EN": "door", "standard_translation_IT": "porta", "note_culturale": "La porta permette di entrare e uscire."}', 1),
    (41, 'ovi', 'noun', NULL, NULL, 2),
    (42, 'door', 'noun', NULL, NULL, 3),
    (43, 'scopa', 'noun', NULL, '{"standard_translation_EN": "broom", "standard_translation_IT": "scopa", "note_culturale": "Si usa la scopa per pulire il pavimento."}', 1),
    (44, 'luuta', 'noun', NULL, NULL, 2),
    (45, 'broom', 'noun', NULL, NULL, 3),
    (46, 'aspirapolvere', 'noun', NULL, '{"standard_translation_EN": "vacuum cleaner", "standard_translation_IT": "aspirapolvere", "note_culturale": "L''aspirapolvere aspira la polvere."}', 1),
    (47, 'imuri', 'noun', NULL, NULL, 2),
    (48, 'vacuum cleaner', 'noun', NULL, NULL, 3),
    (49, 'spugna', 'noun', NULL, '{"standard_translation_EN": "sponge", "standard_translation_IT": "spugna", "note_culturale": "Si usa la spugna per lavare i piatti."}', 1),
    (50, 'sieni', 'noun', NULL, NULL, 2),
    (51, 'sponge', 'noun', NULL, NULL, 3),
    (52, 'detersivo', 'noun', NULL, '{"standard_translation_EN": "detergent", "standard_translation_IT": "detersivo", "note_culturale": "Si usa il detersivo per pulire."}', 1),
    (53, 'pesuaine', 'noun', NULL, NULL, 2),
    (54, 'detergent', 'noun', NULL, NULL, 3),
    (55, 'asciugamano', 'noun', NULL, '{"standard_translation_EN": "towel", "standard_translation_IT": "asciugamano", "note_culturale": "Si usa l''asciugamano per asciugarsi."}', 1),
    (56, 'pyyhe', 'noun', NULL, NULL, 2),
    (57, 'towel', 'noun', NULL, NULL, 3),
    (58, 'spazzolino', 'noun', NULL, '{"standard_translation_EN": "toothbrush", "standard_translation_IT": "spazzolino", "note_culturale": "Si usa lo spazzolino per lavarsi i denti."}', 1),
    (59, 'hammasharja', 'noun', NULL, NULL, 2),
    (60, 'toothbrush', 'noun', NULL, NULL, 3),
    (61, 'specchio', 'noun', NULL, '{"standard_translation_EN": "mirror", "standard_translation_IT": "specchio", "note_culturale": "Ci si guarda allo specchio."}', 1),
    (62, 'peili', 'noun', NULL, NULL, 2),
    (63, 'mirror', 'noun', NULL, NULL, 3),
    (64, 'Spazzare', 'verb', NULL, '{"standard_translation_EN": "Sweep", "standard_translation_IT": "Spazzare", "note_culturale": "Spazzare è l''atto di pulire il pavimento con una scopa."}', 1),
    (65, 'Lakaista', 'verb', NULL, NULL, 2),
    (66, 'Sweep', 'verb', NULL, NULL, 3),
    (67, 'Pyykinpesukone', 'noun', NULL, NULL, 2),
    (68, 'Stendino', 'noun', NULL, '{"standard_translation_EN": "Clothes rack", "standard_translation_IT": "Stendino", "note_culturale": "Lo stendino serve per asciugare i vestiti all''aria aperta o in casa."}', 1),
    (69, 'Kuivausteline', 'noun', NULL, NULL, 2),
    (70, 'Clothes rack', 'noun', NULL, NULL, 3),
    (71, 'Cucina', 'noun', NULL, '{"standard_translation_EN": "Kitchen", "standard_translation_IT": "Cucina", "note_culturale": "La cucina è la stanza dove si preparano i cibi."}', 1),
    (72, 'Keittiö', 'noun', NULL, NULL, 2),
    (73, 'Kitchen', 'noun', NULL, NULL, 3),
    (74, 'Forno', 'noun', NULL, '{"standard_translation_EN": "Oven", "standard_translation_IT": "Forno", "note_culturale": "Il forno è un elettrodomestico per cuocere o riscaldare i cibi."}', 1),
    (75, 'Uuni', 'noun', NULL, NULL, 2),
    (76, 'Oven', 'noun', NULL, NULL, 3),
    (77, 'Pentola', 'noun', NULL, '{"standard_translation_EN": "Pot", "standard_translation_IT": "Pentola", "note_culturale": "La pentola è un recipiente usato per cucinare cibi."}', 1),
    (78, 'Kattila', 'noun', NULL, NULL, 2),
    (79, 'Pot', 'noun', NULL, NULL, 3),
    (80, 'Piatti', 'noun', NULL, '{"standard_translation_EN": "Plates", "standard_translation_IT": "Piatti", "note_culturale": "I piatti sono usati per servire e mangiare il cibo."}', 1),
    (81, 'Lautaset', 'noun', NULL, NULL, 2),
    (82, 'Plates', 'noun', NULL, NULL, 3),
    (83, 'Posate', 'noun', NULL, '{"standard_translation_EN": "Cutlery", "standard_translation_IT": "Posate", "note_culturale": "Le posate includono forchette, coltelli e cucchiai."}', 1),
    (84, 'Ruokailuvälineet', 'noun', NULL, NULL, 2),
    (85, 'Cutlery', 'noun', NULL, NULL, 3),
    (86, 'Soggiorno', 'noun', NULL, '{"standard_translation_EN": "Living room", "standard_translation_IT": "Soggiorno", "note_culturale": "Il soggiorno è la stanza dove ci si rilassa e si ricevono gli ospiti."}', 1),
    (87, 'Olohuone', 'noun', NULL, NULL, 2),
    (88, 'Living room', 'noun', NULL, NULL, 3),
    (89, 'Divano', 'noun', NULL, '{"standard_translation_EN": "Sofa", "standard_translation_IT": "Divano", "note_culturale": "Il divano è un mobile imbottito per sedersi o sdraiarsi."}', 1),
    (90, 'Sohva', 'noun', NULL, NULL, 2),
    (91, 'Sofa', 'noun', NULL, NULL, 3),
    (92, 'Lampada', 'noun', NULL, '{"standard_translation_EN": "Lamp", "standard_translation_IT": "Lampada", "note_culturale": "La lampada serve per illuminare una stanza."}', 1),
    (93, 'Lamppu', 'noun', NULL, NULL, 2),
    (94, 'Lamp', 'noun', NULL, NULL, 3),
    (95, 'Camera da letto', 'noun', NULL, '{"standard_translation_EN": "Bedroom", "standard_translation_IT": "Camera da letto", "note_culturale": "La camera da letto è la stanza dove si dorme."}', 1),
    (96, 'Makuuhuone', 'noun', NULL, NULL, 2),
    (97, 'Bedroom', 'noun', NULL, NULL, 3),
    (98, 'Armadio', 'noun', NULL, '{"standard_translation_EN": "Wardrobe", "standard_translation_IT": "Armadio", "note_culturale": "L''armadio serve per riporre i vestiti."}', 1),
    (99, 'Vaatekaappi', 'noun', NULL, NULL, 2),
    (100, 'Wardrobe', 'noun', NULL, NULL, 3),
    (101, 'spazzatura', 'noun', NULL, '{"standard_translation_EN": "garbage", "standard_translation_IT": "spazzatura", "note_culturale": "È importante separare la spazzatura per il riciclo."}', 1),
    (102, 'roskat', 'noun', NULL, NULL, 2),
    (103, 'garbage', 'noun', NULL, NULL, 3),
    (104, 'chiave', 'noun', NULL, '{"standard_translation_EN": "key", "standard_translation_IT": "chiave", "note_culturale": "Si usa per aprire la porta."}', 1),
    (105, 'avain', 'noun', NULL, NULL, 2),
    (106, 'key', 'noun', NULL, NULL, 3),
    (107, 'mocio', 'noun', NULL, '{"standard_translation_EN": "mop", "standard_translation_IT": "mocio", "note_culturale": "Si usa per lavare il pavimento."}', 1),
    (108, 'moppi', 'noun', NULL, NULL, 2),
    (109, 'mop', 'noun', NULL, NULL, 3),
    (110, 'sapone', 'noun', NULL, '{"standard_translation_EN": "soap", "standard_translation_IT": "sapone", "note_culturale": "Si usa per lavarsi."}', 1),
    (111, 'saippua', 'noun', NULL, NULL, 2),
    (112, 'soap', 'noun', NULL, NULL, 3),
    (113, 'Cucinare', 'verb', NULL, '{"standard_translation_EN": "To cook", "standard_translation_IT": "Cucinare", "note_culturale": "Cucinare è l''azione di preparare il cibo."}', 1),
    (114, 'Laittaa ruokaa', 'verb', NULL, NULL, 2),
    (115, 'To cook', 'verb', NULL, NULL, 3),
    (116, 'Piatto', 'noun', NULL, '{"standard_translation_EN": "Plate", "standard_translation_IT": "Piatto", "note_culturale": "Il piatto è un recipiente per servire il cibo."}', 1),
    (117, 'Lautanen', 'noun', NULL, NULL, 2),
    (118, 'Plate', 'noun', NULL, NULL, 3),
    (119, 'Pulire', 'verb', NULL, '{"standard_translation_EN": "To clean", "standard_translation_IT": "Pulire", "note_culturale": "Pulire è l''azione di rimuovere lo sporco."}', 1),
    (120, 'Siivota', 'verb', NULL, NULL, 2),
    (121, 'To clean', 'verb', NULL, NULL, 3),
    (122, 'Luumu', 'noun', NULL, NULL, 2),
    (123, 'Pölynimuri', 'noun', NULL, NULL, 2),
    (124, 'Stendere', 'verb', NULL, '{"standard_translation_EN": "To hang out the laundry", "standard_translation_IT": "Stendere", "note_culturale": "Stendere è l''azione di appendere i vestiti per farli asciugare."}', 1),
    (125, 'Ripustaa pyykit', 'verb', NULL, NULL, 2),
    (126, 'To hang out the laundry', 'verb', NULL, NULL, 3),
    (127, 'Stendibiancheria', 'noun', NULL, '{"standard_translation_EN": "Clothes rack", "standard_translation_IT": "Stendibiancheria", "note_culturale": "Lo stendibiancheria è utilizzato per asciugare i vestiti dopo il lavaggio."}', 1),
    (128, 'Pyykkiteline', 'noun', NULL, NULL, 2),
    (129, 'Lenzuola', 'noun', NULL, '{"standard_translation_EN": "Sheets", "standard_translation_IT": "Lenzuola", "note_culturale": "Le lenzuola sono tessuti utilizzati per coprire il letto e dormire comodamente."}', 1),
    (130, 'Lakanat', 'noun', NULL, NULL, 2),
    (131, 'Sheets', 'noun', NULL, NULL, 3),
    (132, 'Forchetta', 'noun', NULL, '{"standard_translation_EN": "Fork", "standard_translation_IT": "Forchetta", "note_culturale": "La forchetta è una posata con rebbi utilizzata per mangiare."}', 1),
    (133, 'Haarukka', 'noun', NULL, NULL, 2),
    (134, 'Fork', 'noun', NULL, NULL, 3),
    (135, 'Coltello', 'noun', NULL, '{"standard_translation_EN": "Knife", "standard_translation_IT": "Coltello", "note_culturale": "Il coltello è una posata con una lama affilata utilizzata per tagliare."}', 1),
    (136, 'Veitsi', 'noun', NULL, NULL, 2),
    (137, 'Knife', 'noun', NULL, NULL, 3),
    (138, 'Cucchiaio', 'noun', NULL, '{"standard_translation_EN": "Spoon", "standard_translation_IT": "Cucchiaio", "note_culturale": "Il cucchiaio è una posata concava utilizzata per mangiare cibi liquidi o semisolidi."}', 1),
    (139, 'Lusikka', 'noun', NULL, NULL, 2),
    (140, 'Spoon', 'noun', NULL, NULL, 3),
    (141, 'Padella', 'noun', NULL, '{"standard_translation_EN": "Frying pan", "standard_translation_IT": "Padella", "note_culturale": "La padella è un recipiente utilizzato per friggere o saltare cibi."}', 1),
    (142, 'Paistinpannu', 'noun', NULL, NULL, 2),
    (143, 'Frying pan', 'noun', NULL, NULL, 3),
    (144, 'aperitivo', 'noun', NULL, '{"standard_translation_EN": "aperitif", "standard_translation_IT": "aperitivo", "note_culturale": "Un momento di relax prima di cena."}', 1),
    (145, 'aperitiivi', 'noun', NULL, NULL, 2),
    (146, 'aperitif', 'noun', NULL, NULL, 3),
    (147, 'ristorante', 'noun', NULL, '{"standard_translation_EN": "restaurant", "standard_translation_IT": "ristorante", "note_culturale": "Luogo dove si consumano pasti preparati."}', 1),
    (148, 'ravintola', 'noun', NULL, NULL, 2),
    (149, 'restaurant', 'noun', NULL, NULL, 3),
    (150, 'menu', 'noun', NULL, '{"standard_translation_EN": "menu", "standard_translation_IT": "menu", "note_culturale": "Elenco delle pietanze disponibili."}', 1),
    (151, 'ruokalista', 'noun', NULL, NULL, 2),
    (152, 'menu', 'noun', NULL, NULL, 3),
    (153, 'cameriere', 'noun', NULL, '{"standard_translation_EN": "waiter", "standard_translation_IT": "cameriere", "note_culturale": "Persona che serve ai tavoli."}', 1),
    (154, 'tarjoilija', 'noun', NULL, NULL, 2),
    (155, 'waiter', 'noun', NULL, NULL, 3),
    (156, 'conto', 'noun', NULL, '{"standard_translation_EN": "bill", "standard_translation_IT": "conto", "note_culturale": "Documento con il totale da pagare."}', 1),
    (157, 'spesa', 'noun', NULL, '{"standard_translation_EN": "grocery shopping", "standard_translation_IT": "spesa", "note_culturale": "Acquisto di beni alimentari."}', 1),
    (158, 'ostokset', 'noun', NULL, NULL, 2),
    (159, 'grocery shopping', 'noun', NULL, NULL, 3),
    (160, 'supermercato', 'noun', NULL, '{"standard_translation_EN": "supermarket", "standard_translation_IT": "supermercato", "note_culturale": "Negozio di grandi dimensioni con vari prodotti."}', 1),
    (161, 'supermarket', 'noun', NULL, NULL, 2),
    (162, 'supermarket', 'noun', NULL, NULL, 3),
    (163, 'ingrediente', 'noun', NULL, '{"standard_translation_EN": "ingredient", "standard_translation_IT": "ingrediente", "note_culturale": "Elemento che compone una ricetta."}', 1),
    (164, 'ainesosa', 'noun', NULL, NULL, 2),
    (165, 'ingredient', 'noun', NULL, NULL, 3),
    (166, 'ricetta', 'noun', NULL, '{"standard_translation_EN": "recipe", "standard_translation_IT": "ricetta", "note_culturale": "Istruzioni per preparare un piatto."}', 1),
    (167, 'resepti', 'noun', NULL, NULL, 2),
    (168, 'recipe', 'noun', NULL, NULL, 3),
    (169, 'intolleranza', 'noun', NULL, '{"standard_translation_EN": "intolerance", "standard_translation_IT": "intolleranza", "note_culturale": "Reazione avversa a un alimento."}', 1),
    (170, 'intoleranssi', 'noun', NULL, NULL, 2),
    (171, 'intolerance', 'noun', NULL, NULL, 3),
    (172, 'lattosio', 'noun', NULL, '{"standard_translation_EN": "lactose", "standard_translation_IT": "lattosio", "note_culturale": "Zucchero presente nel latte."}', 1),
    (173, 'laktoosi', 'noun', NULL, NULL, 2),
    (174, 'lactose', 'noun', NULL, NULL, 3),
    (175, 'glutine', 'noun', NULL, '{"standard_translation_EN": "gluten", "standard_translation_IT": "glutine", "note_culturale": "Proteina presente in alcuni cereali."}', 1),
    (176, 'gluteeni', 'noun', NULL, NULL, 2),
    (177, 'gluten', 'noun', NULL, NULL, 3),
    (178, 'vegano', 'noun', NULL, '{"standard_translation_EN": "vegan", "standard_translation_IT": "vegano", "note_culturale": "Chi non consuma prodotti animali."}', 1),
    (179, 'vegaani', 'noun', NULL, NULL, 2),
    (180, 'vegan', 'noun', NULL, NULL, 3),
    (181, 'cocktail', 'noun', NULL, '{"standard_translation_EN": "cocktail", "standard_translation_IT": "cocktail", "note_culturale": "Bevanda alcolica miscelata."}', 1),
    (182, 'cocktail', 'noun', NULL, NULL, 2),
    (183, 'cocktail', 'noun', NULL, NULL, 3),
    (184, 'birra', 'noun', NULL, '{"standard_translation_EN": "beer", "standard_translation_IT": "birra", "note_culturale": "Bevanda alcolica a base di orzo."}', 1),
    (185, 'olut', 'noun', NULL, NULL, 2),
    (186, 'beer', 'noun', NULL, NULL, 3),
    (187, 'vino', 'noun', NULL, '{"standard_translation_EN": "wine", "standard_translation_IT": "vino", "note_culturale": "Bevanda alcolica a base di uva."}', 1),
    (188, 'viini', 'noun', NULL, NULL, 2),
    (189, 'wine', 'noun', NULL, NULL, 3),
    (190, 'cuoco', 'noun', NULL, '{"standard_translation_EN": "cook", "standard_translation_IT": "cuoco", "note_culturale": "Persona che prepara i cibi."}', 1),
    (191, 'kokki', 'noun', NULL, NULL, 2),
    (192, 'cook', 'noun', NULL, NULL, 3),
    (193, 'caffè', 'noun', NULL, '{"standard_translation_EN": "coffee", "standard_translation_IT": "caffè", "note_culturale": "Bevanda eccitante."}', 1),
    (194, 'kahvi', 'noun', NULL, NULL, 2),
    (195, 'coffee', 'noun', NULL, NULL, 3),
    (196, 'carrello', 'noun', NULL, '{"standard_translation_EN": "shopping cart", "standard_translation_IT": "carrello", "note_culturale": "Usato per trasportare la spesa."}', 1),
    (197, 'ostoskärry', 'noun', NULL, NULL, 2),
    (198, 'shopping cart', 'noun', NULL, NULL, 3),
    (199, 'offerta', 'noun', NULL, '{"standard_translation_EN": "offer", "standard_translation_IT": "offerta", "note_culturale": "Prezzo ridotto."}', 1),
    (200, 'tarjous', 'noun', NULL, NULL, 2),
    (201, 'offer', 'noun', NULL, NULL, 3),
    (202, 'scadenza', 'noun', NULL, '{"standard_translation_EN": "expiration date", "standard_translation_IT": "scadenza", "note_culturale": "Data limite per il consumo."}', 1),
    (203, 'viimeinen käyttöpäivä', 'noun', NULL, NULL, 2),
    (204, 'expiration date', 'noun', NULL, NULL, 3),
    (205, 'allergia', 'noun', NULL, '{"standard_translation_EN": "allergy", "standard_translation_IT": "allergia", "note_culturale": "Reazione avversa a un alimento."}', 1),
    (206, 'allergia', 'noun', NULL, NULL, 2),
    (207, 'allergy', 'noun', NULL, NULL, 3),
    (208, 'celiachia', 'noun', NULL, '{"standard_translation_EN": "celiac disease", "standard_translation_IT": "celiachia", "note_culturale": "Intolleranza al glutine."}', 1),
    (209, 'keliakia', 'noun', NULL, NULL, 2),
    (210, 'celiac disease', 'noun', NULL, NULL, 3),
    (211, 'barista', 'noun', NULL, '{"standard_translation_EN": "bartender", "standard_translation_IT": "barista", "note_culturale": "Persona che lavora in un bar."}', 1),
    (212, 'baarimikko', 'noun', NULL, NULL, 2),
    (213, 'bartender', 'noun', NULL, NULL, 3),
    (214, 'biologico', 'adjective', NULL, '{"standard_translation_EN": "organic", "standard_translation_IT": "biologico", "note_culturale": "Prodotto senza pesticidi."}', 1),
    (215, 'luomu', 'adjective', NULL, NULL, 2),
    (216, 'organic', 'adjective', NULL, NULL, 3),
    (217, 'assaggiare', 'verb', NULL, '{"standard_translation_EN": "to taste", "standard_translation_IT": "assaggiare", "note_culturale": "Provare un cibo per valutarne il sapore."}', 1),
    (218, 'maistaa', 'verb', NULL, NULL, 2),
    (219, 'to taste', 'verb', NULL, NULL, 3),
    (220, 'chef', 'noun', NULL, '{"standard_translation_EN": "chef", "standard_translation_IT": "chef", "note_culturale": "Cuoco professionista."}', 1),
    (221, 'chef', 'noun', NULL, NULL, 3),
    (222, 'sommelier', 'noun', NULL, '{"standard_translation_EN": "sommelier", "standard_translation_IT": "sommelier", "note_culturale": "Esperto di vini."}', 1),
    (223, 'sommelier', 'noun', NULL, NULL, 2),
    (224, 'sommelier', 'noun', NULL, NULL, 3),
    (225, 'degustazione', 'noun', NULL, '{"standard_translation_EN": "wine tasting", "standard_translation_IT": "degustazione", "note_culturale": "Assaggio di vini."}', 1),
    (226, 'viininmaistelu', 'noun', NULL, NULL, 2),
    (227, 'wine tasting', 'noun', NULL, NULL, 3),
    (228, 'chilometro zero', 'noun', NULL, '{"standard_translation_EN": "local produce", "standard_translation_IT": "chilometro zero", "note_culturale": "Prodotti del territorio."}', 1),
    (229, 'lähiruoka', 'noun', NULL, NULL, 2),
    (230, 'local produce', 'noun', NULL, NULL, 3),
    (231, 'senza glutine', 'adjective', NULL, '{"standard_translation_EN": "gluten-free", "standard_translation_IT": "senza glutine", "note_culturale": "Privo di glutine."}', 1),
    (232, 'gluteeniton', 'adjective', NULL, NULL, 2),
    (233, 'gluten-free', 'adjective', NULL, NULL, 3),
    (234, 'birra artigianale', 'noun', NULL, '{"standard_translation_EN": "craft beer", "standard_translation_IT": "birra artigianale", "note_culturale": "Birra prodotta da piccoli birrifici."}', 1),
    (235, 'pienpanimo olut', 'noun', NULL, NULL, 2),
    (236, 'craft beer', 'noun', NULL, NULL, 3),
    (237, 'ordinare', 'verb', NULL, '{"standard_translation_EN": "to order", "standard_translation_IT": "ordinare", "note_culturale": "Chiedere qualcosa al ristorante."}', 1),
    (238, 'tilata', 'verb', NULL, NULL, 2),
    (239, 'to order', 'verb', NULL, NULL, 3),
    (240, 'cuocere', 'verb', NULL, '{"standard_translation_EN": "to cook", "standard_translation_IT": "cuocere", "note_culturale": "Preparare il cibo con il calore."}', 1),
    (241, 'keittää', 'verb', NULL, NULL, 2),
    (242, 'bere', 'verb', NULL, '{"standard_translation_EN": "to drink", "standard_translation_IT": "bere", "note_culturale": "Ingerire un liquido."}', 1),
    (243, 'juoda', 'verb', NULL, NULL, 2),
    (244, 'to drink', 'verb', NULL, NULL, 3),
    (245, 'pagare', 'verb', NULL, '{"standard_translation_EN": "to pay", "standard_translation_IT": "pagare", "note_culturale": "Dare denaro in cambio di qualcosa."}', 1),
    (246, 'maksaa', 'verb', NULL, NULL, 2),
    (247, 'to pay', 'verb', NULL, NULL, 3),
    (248, 'negozio', 'noun', NULL, '{"standard_translation_EN": "shop", "standard_translation_IT": "negozio", "note_culturale": "Luogo dove si acquistano beni."}', 1),
    (249, 'kauppa', 'noun', NULL, NULL, 2),
    (250, 'shop', 'noun', NULL, NULL, 3),
    (251, 'posta', 'noun', NULL, '{"standard_translation_EN": "post office", "standard_translation_IT": "posta", "note_culturale": "Ufficio per spedire e ricevere lettere e pacchi."}', 1),
    (252, 'posti', 'noun', NULL, NULL, 2),
    (253, 'post office', 'noun', NULL, NULL, 3),
    (254, 'banca', 'noun', NULL, '{"standard_translation_EN": "bank", "standard_translation_IT": "banca", "note_culturale": "Luogo dove si depositano e prelevano soldi."}', 1),
    (255, 'pankki', 'noun', NULL, NULL, 2),
    (256, 'bank', 'noun', NULL, NULL, 3),
    (257, 'municipio', 'noun', NULL, '{"standard_translation_EN": "town hall", "standard_translation_IT": "municipio", "note_culturale": "Sede dell''amministrazione comunale."}', 1),
    (258, 'kunta', 'noun', NULL, NULL, 2),
    (259, 'town hall', 'noun', NULL, NULL, 3),
    (260, 'farmacia', 'noun', NULL, '{"standard_translation_EN": "pharmacy", "standard_translation_IT": "farmacia", "note_culturale": "Luogo dove si acquistano medicinali."}', 1),
    (261, 'apteekki', 'noun', NULL, NULL, 2),
    (262, 'pharmacy', 'noun', NULL, NULL, 3),
    (263, 'biblioteca', 'noun', NULL, '{"standard_translation_EN": "library", "standard_translation_IT": "biblioteca", "note_culturale": "Luogo dove si prendono in prestito libri."}', 1),
    (264, 'kirjasto', 'noun', NULL, NULL, 2),
    (265, 'library', 'noun', NULL, NULL, 3),
    (266, 'ufficio', 'noun', NULL, '{"standard_translation_EN": "office", "standard_translation_IT": "ufficio", "note_culturale": "Luogo dove si svolge un''attività lavorativa."}', 1),
    (267, 'toimisto', 'noun', NULL, NULL, 2),
    (268, 'office', 'noun', NULL, NULL, 3),
    (269, 'mercato', 'noun', NULL, '{"standard_translation_EN": "market", "standard_translation_IT": "mercato", "note_culturale": "Luogo dove si vendono prodotti alimentari e non."}', 1),
    (270, 'tori', 'noun', NULL, NULL, 2),
    (271, 'market', 'noun', NULL, NULL, 3),
    (272, 'bar', 'noun', NULL, '{"standard_translation_EN": "bar", "standard_translation_IT": "bar", "note_culturale": "Luogo dove si consumano bevande e snack."}', 1),
    (273, 'baari', 'noun', NULL, NULL, 2),
    (274, 'bar', 'noun', NULL, NULL, 3),
    (275, 'stazione', 'noun', NULL, '{"standard_translation_EN": "station", "standard_translation_IT": "stazione", "note_culturale": "Luogo di partenza e arrivo di treni o autobus."}', 1),
    (276, 'asema', 'noun', NULL, NULL, 2),
    (277, 'station', 'noun', NULL, NULL, 3),
    (278, 'ospedale', 'noun', NULL, '{"standard_translation_EN": "hospital", "standard_translation_IT": "ospedale", "note_culturale": "Luogo dove si curano i malati."}', 1),
    (279, 'sairaala', 'noun', NULL, NULL, 2),
    (280, 'hospital', 'noun', NULL, NULL, 3),
    (281, 'scuola', 'noun', NULL, '{"standard_translation_EN": "school", "standard_translation_IT": "scuola", "note_culturale": "Luogo dove si impara."}', 1),
    (282, 'koulu', 'noun', NULL, NULL, 2),
    (283, 'school', 'noun', NULL, NULL, 3),
    (284, 'parco', 'noun', NULL, '{"standard_translation_EN": "park", "standard_translation_IT": "parco", "note_culturale": "Area verde pubblica."}', 1),
    (285, 'puisto', 'noun', NULL, NULL, 2),
    (286, 'park', 'noun', NULL, NULL, 3),
    (287, 'cinema', 'noun', NULL, '{"standard_translation_EN": "cinema", "standard_translation_IT": "cinema", "note_culturale": "Luogo dove si proiettano film."}', 1),
    (288, 'elokuvateatteri', 'noun', NULL, NULL, 2),
    (289, 'cinema', 'noun', NULL, NULL, 3),
    (290, 'teatro', 'noun', NULL, '{"standard_translation_EN": "theater", "standard_translation_IT": "teatro", "note_culturale": "Luogo dove si rappresentano opere teatrali."}', 1),
    (291, 'teatteri', 'noun', NULL, NULL, 2),
    (292, 'theater', 'noun', NULL, NULL, 3),
    (293, 'piscina', 'noun', NULL, '{"standard_translation_EN": "swimming pool", "standard_translation_IT": "piscina", "note_culturale": "Luogo dove si nuota."}', 1),
    (294, 'uima-allas', 'noun', NULL, NULL, 2),
    (295, 'swimming pool', 'noun', NULL, NULL, 3),
    (296, 'palestra', 'noun', NULL, '{"standard_translation_EN": "gym", "standard_translation_IT": "palestra", "note_culturale": "Luogo dove si fa esercizio fisico."}', 1),
    (297, 'kuntosali', 'noun', NULL, NULL, 2),
    (298, 'gym', 'noun', NULL, NULL, 3),
    (299, 'lavanderia', 'noun', NULL, '{"standard_translation_EN": "laundry", "standard_translation_IT": "lavanderia", "note_culturale": "Luogo dove si lavano i vestiti."}', 1),
    (300, 'pesula', 'noun', NULL, NULL, 2),
    (301, 'laundry', 'noun', NULL, NULL, 3),
    (302, 'agenzia di viaggi', 'noun', NULL, '{"standard_translation_EN": "travel agency", "standard_translation_IT": "agenzia di viaggi", "note_culturale": "Luogo dove si organizzano viaggi."}', 1),
    (303, 'matkatoimisto', 'noun', NULL, NULL, 2),
    (304, 'travel agency', 'noun', NULL, NULL, 3),
    (305, 'palazzo di giustizia', 'noun', NULL, '{"standard_translation_EN": "courthouse", "standard_translation_IT": "palazzo di giustizia", "note_culturale": "Edificio dove si amministra la giustizia."}', 1),
    (306, 'oikeustalo', 'noun', NULL, NULL, 2),
    (307, 'courthouse', 'noun', NULL, NULL, 3),
    (308, 'caserma dei pompieri', 'noun', NULL, '{"standard_translation_EN": "fire station", "standard_translation_IT": "caserma dei pompieri", "note_culturale": "Luogo dove risiedono i pompieri."}', 1),
    (309, 'paloasema', 'noun', NULL, NULL, 2),
    (310, 'fire station', 'noun', NULL, NULL, 3),
    (311, 'commissariato di polizia', 'noun', NULL, '{"standard_translation_EN": "police station", "standard_translation_IT": "commissariato di polizia", "note_culturale": "Luogo dove lavora la polizia."}', 1),
    (312, 'poliisiasema', 'noun', NULL, NULL, 2),
    (313, 'police station', 'noun', NULL, NULL, 3),
    (314, 'aeroporto', 'noun', NULL, '{"standard_translation_EN": "airport", "standard_translation_IT": "aeroporto", "note_culturale": "Luogo di arrivo e partenza degli aerei."}', 1),
    (315, 'lentokenttä', 'noun', NULL, NULL, 2),
    (316, 'airport', 'noun', NULL, NULL, 3),
    (317, 'chiesa', 'noun', NULL, '{"standard_translation_EN": "church", "standard_translation_IT": "chiesa", "note_culturale": "Luogo di culto cristiano."}', 1),
    (318, 'kirkko', 'noun', NULL, NULL, 2),
    (319, 'church', 'noun', NULL, NULL, 3),
    (320, 'parcheggio', 'noun', NULL, '{"standard_translation_EN": "parking lot", "standard_translation_IT": "parcheggio", "note_culturale": "Area designata per parcheggiare le auto."}', 1),
    (321, 'pysäköintialue', 'noun', NULL, NULL, 2),
    (322, 'parking lot', 'noun', NULL, NULL, 3),
    (323, 'piazza', 'noun', NULL, '{"standard_translation_EN": "square", "standard_translation_IT": "piazza", "note_culturale": "Spazio aperto in una città."}', 1),
    (324, 'aukio', 'noun', NULL, NULL, 2),
    (325, 'square', 'noun', NULL, NULL, 3),
    (326, 'vigili del fuoco', 'noun', NULL, '{"standard_translation_EN": "fire station", "standard_translation_IT": "vigili del fuoco", "note_culturale": "Luogo dove operano i pompieri."}', 1),
    (327, 'palokunta', 'noun', NULL, NULL, 2),
    (328, 'commissariato', 'noun', NULL, '{"standard_translation_EN": "police station", "standard_translation_IT": "commissariato", "note_culturale": "Sede della polizia."}', 1),
    (329, 'centro commerciale', 'noun', NULL, '{"standard_translation_EN": "shopping mall", "standard_translation_IT": "centro commerciale", "note_culturale": "Luogo con molti negozi."}', 1),
    (330, 'ostoskeskus', 'noun', NULL, NULL, 2),
    (331, 'shopping mall', 'noun', NULL, NULL, 3),
    (332, 'parrucchiere', 'noun', NULL, '{"standard_translation_EN": "hairdresser", "standard_translation_IT": "parrucchiere", "note_culturale": "Luogo dove si tagliano i capelli."}', 1),
    (333, 'kampaamo', 'noun', NULL, NULL, 2),
    (334, 'hairdresser', 'noun', NULL, NULL, 3),
    (335, 'amore', 'noun', NULL, '{"standard_translation_EN": "love", "standard_translation_IT": "amore", "note_culturale": "L''amore è un sentimento universale."}', 1),
    (336, 'rakkaus', 'noun', NULL, NULL, 2),
    (337, 'love', 'noun', NULL, NULL, 3),
    (338, 'felicità', 'noun', NULL, '{"standard_translation_EN": "happiness", "standard_translation_IT": "felicità", "note_culturale": "La felicità è uno stato d''animo desiderabile."}', 1),
    (339, 'onnellisuus', 'noun', NULL, NULL, 2),
    (340, 'happiness', 'noun', NULL, NULL, 3),
    (341, 'tristezza', 'noun', NULL, '{"standard_translation_EN": "sadness", "standard_translation_IT": "tristezza", "note_culturale": "La tristezza è una parte naturale della vita."}', 1),
    (342, 'suru', 'noun', NULL, NULL, 2),
    (343, 'sadness', 'noun', NULL, NULL, 3),
    (344, 'rabbia', 'noun', NULL, '{"standard_translation_EN": "anger", "standard_translation_IT": "rabbia", "note_culturale": "La rabbia può essere distruttiva se non controllata."}', 1),
    (345, 'viha', 'noun', NULL, NULL, 2),
    (346, 'anger', 'noun', NULL, NULL, 3),
    (347, 'paura', 'noun', NULL, '{"standard_translation_EN": "fear", "standard_translation_IT": "paura", "note_culturale": "La paura è una reazione istintiva al pericolo."}', 1),
    (348, 'pelko', 'noun', NULL, NULL, 2),
    (349, 'fear', 'noun', NULL, NULL, 3),
    (350, 'sorpresa', 'noun', NULL, '{"standard_translation_EN": "surprise", "standard_translation_IT": "sorpresa", "note_culturale": "La sorpresa può essere positiva o negativa."}', 1),
    (351, 'yllätys', 'noun', NULL, NULL, 2),
    (352, 'surprise', 'noun', NULL, NULL, 3),
    (353, 'ansia', 'noun', NULL, '{"standard_translation_EN": "anxiety", "standard_translation_IT": "ansia", "note_culturale": "L''ansia può influenzare la vita quotidiana."}', 1),
    (354, 'ahdistus', 'noun', NULL, NULL, 2),
    (355, 'anxiety', 'noun', NULL, NULL, 3),
    (356, 'speranza', 'noun', NULL, '{"standard_translation_EN": "hope", "standard_translation_IT": "speranza", "note_culturale": "La speranza aiuta a superare le difficoltà."}', 1),
    (357, 'toivo', 'noun', NULL, NULL, 2),
    (358, 'hope', 'noun', NULL, NULL, 3),
    (359, 'delusione', 'noun', NULL, '{"standard_translation_EN": "disappointment", "standard_translation_IT": "delusione", "note_culturale": "La delusione è comune quando le aspettative non sono soddisfatte."}', 1),
    (360, 'pettymys', 'noun', NULL, NULL, 2),
    (361, 'disappointment', 'noun', NULL, NULL, 3),
    (362, 'empatia', 'noun', NULL, '{"standard_translation_EN": "empathy", "standard_translation_IT": "empatia", "note_culturale": "L''empatia è la capacità di comprendere i sentimenti degli altri."}', 1),
    (363, 'empatia', 'noun', NULL, NULL, 2),
    (364, 'empathy', 'noun', NULL, NULL, 3),
    (365, 'passione', 'noun', NULL, '{"standard_translation_EN": "passion", "standard_translation_IT": "passione", "note_culturale": "La passione alimenta la creatività e la determinazione."}', 1),
    (366, 'into', 'noun', NULL, NULL, 2),
    (367, 'passion', 'noun', NULL, NULL, 3),
    (368, 'rimpianto', 'noun', NULL, '{"standard_translation_EN": "regret", "standard_translation_IT": "rimpianto", "note_culturale": "Il rimpianto può derivare da decisioni passate."}', 1),
    (369, 'katumus', 'noun', NULL, NULL, 2),
    (370, 'regret', 'noun', NULL, NULL, 3),
    (371, 'fiducia', 'noun', NULL, '{"standard_translation_EN": "trust", "standard_translation_IT": "fiducia", "note_culturale": "La fiducia è fondamentale nelle relazioni interpersonali."}', 1),
    (372, 'luottamus', 'noun', NULL, NULL, 2),
    (373, 'trust', 'noun', NULL, NULL, 3),
    (374, 'gelosia', 'noun', NULL, '{"standard_translation_EN": "jealousy", "standard_translation_IT": "gelosia", "note_culturale": "La gelosia può danneggiare le relazioni."}', 1),
    (375, 'mustasukkaisuus', 'noun', NULL, NULL, 2),
    (376, 'jealousy', 'noun', NULL, NULL, 3),
    (377, 'soddisfazione', 'noun', NULL, '{"standard_translation_EN": "satisfaction", "standard_translation_IT": "soddisfazione", "note_culturale": "La soddisfazione deriva dal raggiungimento di un obiettivo."}', 1),
    (378, 'tyytyväisyys', 'noun', NULL, NULL, 2),
    (379, 'satisfaction', 'noun', NULL, NULL, 3),
    (380, 'orgoglio', 'noun', NULL, '{"standard_translation_EN": "pride", "standard_translation_IT": "orgoglio", "note_culturale": "L''orgoglio può essere positivo o negativo a seconda del contesto."}', 1),
    (381, 'ylpeys', 'noun', NULL, NULL, 2),
    (382, 'pride', 'noun', NULL, NULL, 3),
    (383, 'solitudine', 'noun', NULL, '{"standard_translation_EN": "loneliness", "standard_translation_IT": "solitudine", "note_culturale": "La solitudine può influire sulla salute mentale."}', 1),
    (384, 'yksinäisyys', 'noun', NULL, NULL, 2),
    (385, 'loneliness', 'noun', NULL, NULL, 3),
    (386, 'entusiasmo', 'noun', NULL, '{"standard_translation_EN": "enthusiasm", "standard_translation_IT": "entusiasmo", "note_culturale": "L''entusiasmo è contagioso e motivante."}', 1),
    (387, 'innostus', 'noun', NULL, NULL, 2),
    (388, 'enthusiasm', 'noun', NULL, NULL, 3),
    (389, 'preoccupazione', 'noun', NULL, '{"standard_translation_EN": "worry", "standard_translation_IT": "preoccupazione", "note_culturale": "La preoccupazione può essere legata a problemi reali o immaginari."}', 1),
    (390, 'huoli', 'noun', NULL, NULL, 2),
    (391, 'worry', 'noun', NULL, NULL, 3),
    (392, 'gratitudine', 'noun', NULL, '{"standard_translation_EN": "gratitude", "standard_translation_IT": "gratitudine", "note_culturale": "La gratitudine migliora il benessere emotivo."}', 1),
    (393, 'kiitollisuus', 'noun', NULL, NULL, 2),
    (394, 'gratitude', 'noun', NULL, NULL, 3),
    (395, 'gioia', 'noun', NULL, '{"standard_translation_EN": "joy", "standard_translation_IT": "gioia", "note_culturale": "La gioia è un''emozione di grande felicità."}', 1),
    (396, 'ilo', 'noun', NULL, NULL, 2),
    (397, 'joy', 'noun', NULL, NULL, 3),
    (398, 'frustrazione', 'noun', NULL, '{"standard_translation_EN": "frustration", "standard_translation_IT": "frustrazione", "note_culturale": "La frustrazione è un sentimento di insoddisfazione causato dall''impossibilità di raggiungere un obiettivo."}', 1),
    (399, 'frustraatio', 'noun', NULL, NULL, 2),
    (400, 'frustration', 'noun', NULL, NULL, 3),
    (401, 'nostalgia', 'noun', NULL, '{"standard_translation_EN": "nostalgia", "standard_translation_IT": "nostalgia", "note_culturale": "La nostalgia è un sentimento di malinconia per un passato idealizzato."}', 1),
    (402, 'nostalgia', 'noun', NULL, NULL, 2),
    (403, 'nostalgia', 'noun', NULL, NULL, 3),
    (404, 'rassegnazione', 'noun', NULL, '{"standard_translation_EN": "resignation", "standard_translation_IT": "rassegnazione", "note_culturale": "La rassegnazione è l''accettazione di una situazione inevitabile."}', 1),
    (405, 'alistuminen', 'noun', NULL, NULL, 2),
    (406, 'resignation', 'noun', NULL, NULL, 3),
    (407, 'serenità', 'noun', NULL, '{"standard_translation_EN": "serenity", "standard_translation_IT": "serenità", "note_culturale": "La serenità è uno stato di calma e pace interiore."}', 1),
    (408, 'tyyneys', 'noun', NULL, NULL, 2),
    (409, 'serenity', 'noun', NULL, NULL, 3),
    (410, 'invidia', 'noun', NULL, '{"standard_translation_EN": "envy", "standard_translation_IT": "invidia", "note_culturale": "L''invidia è un sentimento di risentimento verso chi possiede qualcosa che si desidera."}', 1),
    (411, 'kateus', 'noun', NULL, NULL, 2),
    (412, 'envy', 'noun', NULL, NULL, 3),
    (413, 'rimorso', 'noun', NULL, '{"standard_translation_EN": "remorse", "standard_translation_IT": "rimorso", "note_culturale": "Il rimorso è un sentimento di colpa per qualcosa che si è fatto."}', 1),
    (414, 'remorse', 'noun', NULL, NULL, 3),
    (415, 'ammirazione', 'noun', NULL, '{"standard_translation_EN": "admiration", "standard_translation_IT": "ammirazione", "note_culturale": "L''ammirazione è un sentimento di rispetto e apprezzamento."}', 1),
    (416, 'ihailu', 'noun', NULL, NULL, 2),
    (417, 'admiration', 'noun', NULL, NULL, 3),
    (418, 'odio', 'noun', NULL, '{"standard_translation_EN": "hatred", "standard_translation_IT": "odio", "note_culturale": "L''odio è un sentimento di forte avversione e repulsione."}', 1),
    (419, 'hatred', 'noun', NULL, NULL, 3),
    (420, 'Netiquette', 'noun', NULL, '{"standard_translation_EN": "Netiquette", "standard_translation_IT": "Netiquette", "note_culturale": "Insieme di regole per una buona comunicazione online."}', 1),
    (421, 'Nettietiketti', 'noun', NULL, NULL, 2),
    (422, 'Netiquette', 'noun', NULL, NULL, 3),
    (423, 'Privacy', 'noun', NULL, '{"standard_translation_EN": "Privacy", "standard_translation_IT": "Privacy", "note_culturale": "Diritto alla riservatezza dei dati personali."}', 1),
    (424, 'Yksityisyys', 'noun', NULL, NULL, 2),
    (425, 'Privacy', 'noun', NULL, NULL, 3),
    (426, 'Cyberbullismo', 'noun', NULL, '{"standard_translation_EN": "Cyberbullying", "standard_translation_IT": "Cyberbullismo", "note_culturale": "Forma di bullismo attuata tramite strumenti digitali."}', 1),
    (427, 'Nettikiusaaminen', 'noun', NULL, NULL, 2),
    (428, 'Cyberbullying', 'noun', NULL, NULL, 3),
    (429, 'Identità digitale', 'noun', NULL, '{"standard_translation_EN": "Digital identity", "standard_translation_IT": "Identità digitale", "note_culturale": "Rappresentazione di una persona nel mondo digitale."}', 1),
    (430, 'Digitaalinen identiteetti', 'noun', NULL, NULL, 2),
    (431, 'Digital identity', 'noun', NULL, NULL, 3),
    (432, 'Fake news', 'noun', NULL, '{"standard_translation_EN": "Fake news", "standard_translation_IT": "Fake news", "note_culturale": "Notizie false diffuse intenzionalmente."}', 1),
    (433, 'Valeuutiset', 'noun', NULL, NULL, 2),
    (434, 'Fake news', 'noun', NULL, NULL, 3),
    (435, 'Consenso', 'noun', NULL, '{"standard_translation_EN": "Consent", "standard_translation_IT": "Consenso", "note_culturale": "Autorizzazione al trattamento dei dati personali."}', 1),
    (436, 'Suostumus', 'noun', NULL, NULL, 2),
    (437, 'Consent', 'noun', NULL, NULL, 3),
    (438, 'Responsabilità digitale', 'noun', NULL, '{"standard_translation_EN": "Digital responsibility", "standard_translation_IT": "Responsabilità digitale", "note_culturale": "Essere consapevoli delle proprie azioni online."}', 1),
    (439, 'Digitaalinen vastuu', 'noun', NULL, NULL, 2),
    (440, 'Digital responsibility', 'noun', NULL, NULL, 3),
    (441, 'Copyright', 'noun', NULL, '{"standard_translation_EN": "Copyright", "standard_translation_IT": "Copyright", "note_culturale": "Protezione legale delle opere creative."}', 1),
    (442, 'Tekijänoikeus', 'noun', NULL, NULL, 2),
    (443, 'Copyright', 'noun', NULL, NULL, 3),
    (444, 'Hate speech', 'noun', NULL, '{"standard_translation_EN": "Hate speech", "standard_translation_IT": "Hate speech", "note_culturale": "Discorso che incita all''odio verso un gruppo."}', 1),
    (445, 'Vihapuhe', 'noun', NULL, NULL, 2),
    (446, 'Hate speech', 'noun', NULL, NULL, 3),
    (447, 'Sicurezza informatica', 'noun', NULL, '{"standard_translation_EN": "Cybersecurity", "standard_translation_IT": "Sicurezza informatica", "note_culturale": "Misure per proteggere i sistemi informatici."}', 1),
    (448, 'Tietoturva', 'noun', NULL, NULL, 2),
    (449, 'Cybersecurity', 'noun', NULL, NULL, 3),
    (450, 'Trasparenza', 'noun', NULL, '{"standard_translation_EN": "Transparency", "standard_translation_IT": "Trasparenza", "note_culturale": "Accessibilità e chiarezza delle informazioni."}', 1),
    (451, 'Avoimuus', 'noun', NULL, NULL, 2),
    (452, 'Transparency', 'noun', NULL, NULL, 3),
    (453, 'Accessibilità', 'noun', NULL, '{"standard_translation_EN": "Accessibility", "standard_translation_IT": "Accessibilità", "note_culturale": "Possibilità di accesso e utilizzo per tutti."}', 1),
    (454, 'Saavutettavuus', 'noun', NULL, NULL, 2),
    (455, 'Accessibility', 'noun', NULL, NULL, 3),
    (456, 'Algoritmo', 'noun', NULL, '{"standard_translation_EN": "Algorithm", "standard_translation_IT": "Algoritmo", "note_culturale": "Insieme di istruzioni per risolvere un problema."}', 1),
    (457, 'Algoritmi', 'noun', NULL, NULL, 2),
    (458, 'Algorithm', 'noun', NULL, NULL, 3),
    (459, 'Dati personali', 'noun', NULL, '{"standard_translation_EN": "Personal data", "standard_translation_IT": "Dati personali", "note_culturale": "Informazioni che identificano una persona."}', 1),
    (460, 'Henkilötiedot', 'noun', NULL, NULL, 2),
    (461, 'Personal data', 'noun', NULL, NULL, 3),
    (462, 'Crittografia', 'noun', NULL, '{"standard_translation_EN": "Encryption", "standard_translation_IT": "Crittografia", "note_culturale": "Tecnica per proteggere i dati rendendoli illeggibili."}', 1),
    (463, 'Salaus', 'noun', NULL, NULL, 2),
    (464, 'Encryption', 'noun', NULL, NULL, 3),
    (465, 'Phishing', 'noun', NULL, '{"standard_translation_EN": "Phishing", "standard_translation_IT": "Phishing", "note_culturale": "Tentativo di ottenere informazioni sensibili con l''inganno."}', 1),
    (466, 'Huijaus', 'noun', NULL, NULL, 2),
    (467, 'Phishing', 'noun', NULL, NULL, 3),
    (468, 'Impronta digitale', 'noun', NULL, '{"standard_translation_EN": "Digital footprint", "standard_translation_IT": "Impronta digitale", "note_culturale": "Informazioni lasciate online dalle attività di una persona."}', 1),
    (469, 'Digitaalinen jalanjälki', 'noun', NULL, NULL, 2),
    (470, 'Digital footprint', 'noun', NULL, NULL, 3),
    (471, 'Libertà di espressione', 'noun', NULL, '{"standard_translation_EN": "Freedom of speech", "standard_translation_IT": "Libertà di espressione", "note_culturale": "Diritto di esprimere liberamente le proprie opinioni."}', 1),
    (472, 'Sananvapaus', 'noun', NULL, NULL, 2),
    (473, 'Freedom of speech', 'noun', NULL, NULL, 3),
    (474, 'Moderazione dei contenuti', 'noun', NULL, '{"standard_translation_EN": "Content moderation", "standard_translation_IT": "Moderazione dei contenuti", "note_culturale": "Processo di revisione e rimozione di contenuti inappropriati."}', 1),
    (475, 'Sisällön moderointi', 'noun', NULL, NULL, 2),
    (476, 'Content moderation', 'noun', NULL, NULL, 3),
    (477, 'Divario digitale', 'noun', NULL, '{"standard_translation_EN": "Digital divide", "standard_translation_IT": "Divario digitale", "note_culturale": "Differenza di accesso e utilizzo delle tecnologie digitali."}', 1),
    (478, 'Digitaalinen kuilu', 'noun', NULL, NULL, 2),
    (479, 'Digital divide', 'noun', NULL, NULL, 3),
    (480, 'Hacker', 'noun', NULL, '{"standard_translation_EN": "Hacker", "standard_translation_IT": "Hacker", "note_culturale": "Persona che accede illegalmente a sistemi informatici."}', 1),
    (481, 'Hakkeri', 'noun', NULL, NULL, 2),
    (482, 'Hacker', 'noun', NULL, NULL, 3),
    (483, 'Diritto all''oblio', 'noun', NULL, '{"standard_translation_EN": "Right to be forgotten", "standard_translation_IT": "Diritto all''oblio", "note_culturale": "Diritto di far rimuovere informazioni personali da internet."}', 1),
    (484, 'Oikeus tulla unohdetuksi', 'noun', NULL, NULL, 2),
    (485, 'Right to be forgotten', 'noun', NULL, NULL, 3),
    (486, 'Post verità', 'noun', NULL, '{"standard_translation_EN": "Post-truth", "standard_translation_IT": "Post verità", "note_culturale": "Situazione in cui le emozioni influenzano più dei fatti."}', 1),
    (487, 'Totuudenjälkeinen aika', 'noun', NULL, NULL, 2),
    (488, 'Post-truth', 'noun', NULL, NULL, 3),
    (489, 'Echo chamber', 'noun', NULL, '{"standard_translation_EN": "Echo chamber", "standard_translation_IT": "Echo chamber", "note_culturale": "Ambiente in cui si sentono solo opinioni simili alle proprie."}', 1),
    (490, 'Kaikukammio', 'noun', NULL, NULL, 2),
    (491, 'Echo chamber', 'noun', NULL, NULL, 3),
    (492, 'Troll', 'noun', NULL, '{"standard_translation_EN": "Troll", "standard_translation_IT": "Troll", "note_culturale": "Persona che provoca discussioni online."}', 1),
    (493, 'Trolli', 'noun', NULL, NULL, 2),
    (494, 'Troll', 'noun', NULL, NULL, 3),
    (495, 'Doxing', 'noun', NULL, '{"standard_translation_EN": "Doxing", "standard_translation_IT": "Doxing", "note_culturale": "Rivelare pubblicamente informazioni personali di qualcuno."}', 1),
    (496, 'Doxaus', 'noun', NULL, NULL, 2),
    (497, 'Doxing', 'noun', NULL, NULL, 3),
    (498, 'Catfishing', 'noun', NULL, '{"standard_translation_EN": "Catfishing", "standard_translation_IT": "Catfishing", "note_culturale": "Creare una falsa identità online per ingannare qualcuno."}', 1),
    (499, 'Valeprofiili', 'noun', NULL, NULL, 2),
    (500, 'Catfishing', 'noun', NULL, NULL, 3),
    (501, 'Deepfake', 'noun', NULL, '{"standard_translation_EN": "Deepfake", "standard_translation_IT": "Deepfake", "note_culturale": "Video o audio falsificato con intelligenza artificiale."}', 1),
    (502, 'Deepfake', 'noun', NULL, NULL, 2),
    (503, 'Deepfake', 'noun', NULL, NULL, 3),
    (504, 'Licenza', 'noun', NULL, '{"standard_translation_EN": "License", "standard_translation_IT": "Licenza", "note_culturale": "Autorizzazione ad utilizzare un software o un''opera."}', 1),
    (505, 'Lisenssi', 'noun', NULL, NULL, 2),
    (506, 'License', 'noun', NULL, NULL, 3),
    (507, 'Password', 'noun', NULL, '{"standard_translation_EN": "Password", "standard_translation_IT": "Password", "note_culturale": "Codice segreto per accedere a un account."}', 1),
    (508, 'Salasana', 'noun', NULL, NULL, 2),
    (509, 'Password', 'noun', NULL, NULL, 3),
    (510, 'Verifica', 'noun', NULL, '{"standard_translation_EN": "Verification", "standard_translation_IT": "Verifica", "note_culturale": "Processo per assicurarsi che qualcosa sia vero."}', 1),
    (511, 'Varmistus', 'noun', NULL, NULL, 2),
    (512, 'Verification', 'noun', NULL, NULL, 3),
    (513, 'Anonimato', 'noun', NULL, '{"standard_translation_EN": "Anonymity", "standard_translation_IT": "Anonimato", "note_culturale": "Condizione di non essere identificabile."}', 1),
    (514, 'Anonymiteetti', 'noun', NULL, NULL, 2),
    (515, 'Anonymity', 'noun', NULL, NULL, 3),
    (516, 'Intelligenza artificiale', 'noun', NULL, '{"standard_translation_EN": "Artificial intelligence", "standard_translation_IT": "Intelligenza artificiale", "note_culturale": "Simulazione dell''intelligenza umana nei computer."}', 1),
    (517, 'Tekoäly', 'noun', NULL, NULL, 2),
    (518, 'Artificial intelligence', 'noun', NULL, NULL, 3),
    (519, 'Filter bubble', 'noun', NULL, '{"standard_translation_EN": "Filter bubble", "standard_translation_IT": "Filter bubble", "note_culturale": "Isolamento intellettuale derivante dalla personalizzazione dei risultati di ricerca."}', 1),
    (520, 'Suodatinkuplia', 'noun', NULL, NULL, 2),
    (521, 'Filter bubble', 'noun', NULL, NULL, 3),
    (522, 'Sharenting', 'noun', NULL, '{"standard_translation_EN": "Sharenting", "standard_translation_IT": "Sharenting", "note_culturale": "Condivisione eccessiva di informazioni sui figli da parte dei genitori online."}', 1),
    (523, 'Sharenting', 'noun', NULL, NULL, 2),
    (524, 'Sharenting', 'noun', NULL, NULL, 3),
    (525, 'Open source', 'noun', NULL, '{"standard_translation_EN": "Open source", "standard_translation_IT": "Open source", "note_culturale": "Software il cui codice sorgente è disponibile e modificabile da tutti."}', 1),
    (526, 'Avoin lähdekoodi', 'noun', NULL, NULL, 2),
    (527, 'Open source', 'noun', NULL, NULL, 3),
    (528, 'famiglia', 'noun', NULL, '{"standard_translation_EN": "family", "standard_translation_IT": "famiglia", "note_culturale": "Concetto universale di unità sociale."}', 1),
    (529, 'perhe', 'noun', NULL, NULL, 2),
    (530, 'family', 'noun', NULL, NULL, 3),
    (531, 'genitore', 'noun', NULL, '{"standard_translation_EN": "parent", "standard_translation_IT": "genitore", "note_culturale": "Responsabile della cura dei figli."}', 1),
    (532, 'vanhempi', 'noun', NULL, NULL, 2),
    (533, 'parent', 'noun', NULL, NULL, 3),
    (534, 'figlio', 'noun', NULL, '{"standard_translation_EN": "child", "standard_translation_IT": "figlio", "note_culturale": "Membro giovane della famiglia."}', 1),
    (535, 'lapsi', 'noun', NULL, NULL, 2)
ON CONFLICT DO NOTHING;
SELECT setval('lemma_lemma_id_seq', 535);

INSERT INTO morpho_form (surface_form, grammar_json, lemma_id) VALUES
    ('Monte', NULL, 1),
    ('Tunturi', NULL, 2),
    ('Peak', NULL, 3),
    ('alloggio', NULL, 4),
    ('huoneisto', NULL, 5),
    ('flat', NULL, 6),
    ('pigione', NULL, 7),
    ('vuokramaksu', NULL, 8),
    ('rental', NULL, 9),
    ('fee', NULL, 9),
    ('fattura', NULL, 10),
    ('veloitus', NULL, 11),
    ('invoice', NULL, 12),
    ('macchina', NULL, 13),
    ('per', NULL, 13),
    ('lavare', NULL, 13),
    ('pyykinpesukone', NULL, 14),
    ('washing', NULL, 15),
    ('machine', NULL, 15),
    ('washer', NULL, 15),
    ('frigo', NULL, 16),
    ('kylmäkaappi', NULL, 17),
    ('fridge', NULL, 18),
    ('cucina', NULL, 19),
    ('hella', NULL, 20),
    ('cooker', NULL, 21),
    ('desco', NULL, 22),
    ('lauta', NULL, 23),
    ('board', NULL, 24),
    ('seggiola', NULL, 25),
    ('istuin', NULL, 26),
    ('seat', NULL, 27),
    ('giaciglio', NULL, 28),
    ('vuode', NULL, 29),
    ('cot', NULL, 30),
    ('guanciale', NULL, 31),
    ('päänalunen', NULL, 32),
    ('cushion', NULL, 33),
    ('coltre', NULL, 34),
    ('viltti', NULL, 35),
    ('cover', NULL, 36),
    ('vetro', NULL, 37),
    ('ruutu', NULL, 38),
    ('pane', NULL, 39),
    ('uscio', NULL, 40),
    ('portti', NULL, 41),
    ('gate', NULL, 42),
    ('granata', NULL, 43),
    ('harja', NULL, 44),
    ('brush', NULL, 45),
    ('folletto', NULL, 46),
    ('pölynimuri', NULL, 47),
    ('vacuum', NULL, 48),
    ('cleaner', NULL, 48),
    ('hoover', NULL, 48),
    ('panno', NULL, 49),
    ('pesusieni', NULL, 50),
    ('cloth', NULL, 51),
    ('sapone', NULL, 52),
    ('saippua', NULL, 53),
    ('soap', NULL, 54),
    ('telo', NULL, 55),
    ('käsipyyhe', NULL, 56),
    ('cloth', NULL, 57),
    ('setola', NULL, 58),
    ('harja', NULL, 59),
    ('brush', NULL, 60),
    ('vetro', NULL, 61),
    ('heijastin', NULL, 62),
    ('glass', NULL, 63),
    ('Pulire', NULL, 64),
    ('Scopare', NULL, 64),
    ('Harjata', NULL, 65),
    ('Pyyhkiä', NULL, 65),
    ('Clean', NULL, 66),
    ('Brush', NULL, 66),
    ('Pesukone', NULL, 67),
    ('Pyykkikone', NULL, 67),
    ('Filo', NULL, 68),
    ('per', NULL, 68),
    ('stendere', NULL, 68),
    ('Asciugatoio', NULL, 68),
    ('Pyykkiteline', NULL, 69),
    ('Kuivaustanko', NULL, 69),
    ('Drying', NULL, 70),
    ('rack', NULL, 70),
    ('Clothes', NULL, 70),
    ('horse', NULL, 70),
    ('Stanza', NULL, 71),
    ('da', NULL, 71),
    ('Luogo', NULL, 71),
    ('per', NULL, 71),
    ('cucinare', NULL, 71),
    ('Ruuanlaittotila', NULL, 72),
    ('Kokkaushuone', NULL, 72),
    ('Cooking', NULL, 73),
    ('area', NULL, 73),
    ('Food', NULL, 73),
    ('preparation', NULL, 73),
    ('room', NULL, 73),
    ('Fornello', NULL, 74),
    ('Apparecchio', NULL, 74),
    ('per', NULL, 74),
    ('cuocere', NULL, 74),
    ('Liesi', NULL, 75),
    ('Paistouuni', NULL, 75),
    ('Stove', NULL, 76),
    ('Cooker', NULL, 76),
    ('Casseruola', NULL, 77),
    ('Recipiente', NULL, 77),
    ('per', NULL, 77),
    ('cucinare', NULL, 77),
    ('Pata', NULL, 78),
    ('Keittoastia', NULL, 78),
    ('Saucepan', NULL, 79),
    ('Cooking', NULL, 79),
    ('vessel', NULL, 79),
    ('Stoviglie', NULL, 80),
    ('Piatto', NULL, 80),
    ('piano', NULL, 80),
    ('Astiat', NULL, 81),
    ('Ruokalautanen', NULL, 81),
    ('Dishes', NULL, 82),
    ('Dinner', NULL, 82),
    ('Mestoli', NULL, 83),
    ('Forchetta', NULL, 83),
    ('Aterimet', NULL, 84),
    ('Haarukka', NULL, 84),
    ('Silverware', NULL, 85),
    ('Forks', NULL, 85),
    ('Salotto', NULL, 86),
    ('Stanza', NULL, 86),
    ('da', NULL, 86),
    ('giorno', NULL, 86),
    ('Oleskeluhuone', NULL, 87),
    ('Lounge', NULL, 88),
    ('Sitting', NULL, 88),
    ('room', NULL, 88),
    ('Canapè', NULL, 89),
    ('Letto', NULL, 89),
    ('da', NULL, 89),
    ('giorno', NULL, 89),
    ('Levitettävä', NULL, 90),
    ('sänky', NULL, 90),
    ('Istuin', NULL, 90),
    ('Couch', NULL, 91),
    ('Setee', NULL, 91),
    ('Lume', NULL, 92),
    ('Apparecchio', NULL, 92),
    ('illuminante', NULL, 92),
    ('Valaisin', NULL, 93),
    ('Valo', NULL, 93),
    ('Light', NULL, 94),
    ('Lighting', NULL, 94),
    ('fixture', NULL, 94),
    ('Stanza', NULL, 95),
    ('da', NULL, 95),
    ('letto', NULL, 95),
    ('Camera', NULL, 95),
    ('Nukkumahuone', NULL, 96),
    ('Kamari', NULL, 96),
    ('Sleeping', NULL, 97),
    ('room', NULL, 97),
    ('Chamber', NULL, 97),
    ('Guardaroba', NULL, 98),
    ('Stipo', NULL, 98),
    ('Pukeutumishuone', NULL, 99),
    ('Komero', NULL, 99),
    ('Closet', NULL, 100),
    ('Cupboard', NULL, 100),
    ('rifiuti', NULL, 101),
    ('jätteet', NULL, 102),
    ('trash', NULL, 103),
    ('di', NULL, 104),
    ('casa', NULL, 104),
    ('koti', NULL, 105),
    ('house', NULL, 106),
    ('straccio', NULL, 107),
    ('per', NULL, 107),
    ('pavimenti', NULL, 107),
    ('lattiarätti', NULL, 108),
    ('floor', NULL, 109),
    ('cloth', NULL, 109),
    ('saponetta', NULL, 110),
    ('pesuaine', NULL, 111),
    ('cleanser', NULL, 112),
    ('Preparare', NULL, 113),
    ('Cuocere', NULL, 113),
    ('Valmistaa', NULL, 114),
    ('Keittää', NULL, 114),
    ('Prepare', NULL, 115),
    ('Bake', NULL, 115),
    ('Vassoio', NULL, 116),
    ('Stoviglia', NULL, 116),
    ('Tarjotin', NULL, 117),
    ('Astiat', NULL, 117),
    ('Tray', NULL, 118),
    ('Dishes', NULL, 118),
    ('Lavare', NULL, 119),
    ('Igienizzare', NULL, 119),
    ('Pestä', NULL, 120),
    ('Desinfioida', NULL, 120),
    ('Wash', NULL, 121),
    ('Sanitize', NULL, 121),
    ('Harja', NULL, 122),
    ('Työkalu', NULL, 122),
    ('Imuri', NULL, 123),
    ('Sähkölaite', NULL, 123),
    ('Appendere', NULL, 124),
    ('Asciugare', NULL, 124),
    ('Kuivata', NULL, 125),
    ('Pyykkinaru', NULL, 125),
    ('Dry', NULL, 126),
    ('Clothesline', NULL, 126),
    ('Stenditoio', NULL, 127),
    ('Filo', NULL, 127),
    ('per', NULL, 127),
    ('stendere', NULL, 127),
    ('Kuivausteline', NULL, 128),
    ('Vaaterekki', NULL, 128),
    ('Biancheria', NULL, 129),
    ('da', NULL, 129),
    ('letto', NULL, 129),
    ('Copriletto', NULL, 129),
    ('Pussilakana', NULL, 130),
    ('Aluslakana', NULL, 130),
    ('Bedding', NULL, 131),
    ('Bedclothes', NULL, 131),
    ('Punta', NULL, 132),
    ('Arpione', NULL, 132),
    ('Piikki', NULL, 133),
    ('Keihäs', NULL, 133),
    ('Prong', NULL, 134),
    ('Spike', NULL, 134),
    ('Lama', NULL, 135),
    ('Taglierina', NULL, 135),
    ('Terä', NULL, 136),
    ('Puukko', NULL, 136),
    ('Blade', NULL, 137),
    ('Cutter', NULL, 137),
    ('Mestolo', NULL, 138),
    ('Paletta', NULL, 138),
    ('Kauha', NULL, 139),
    ('Lastalla', NULL, 139),
    ('Ladle', NULL, 140),
    ('Scoop', NULL, 140),
    ('Tegame', NULL, 141),
    ('Saltapasta', NULL, 141),
    ('Liesikupu', NULL, 142),
    ('Wokkipannu', NULL, 142),
    ('Skillet', NULL, 143),
    ('Wok', NULL, 143),
    ('Stuzzichino', NULL, 144),
    ('Alkupala', NULL, 145),
    ('Appetizer', NULL, 146),
    ('Trattoria', NULL, 147),
    ('Ruokapaikka', NULL, 148),
    ('Eatery', NULL, 149),
    ('Carta', NULL, 150),
    ('Menu', NULL, 151),
    ('List', NULL, 152),
    ('Servitore', NULL, 153),
    ('Hovimestari', NULL, 154),
    ('Server', NULL, 155),
    ('Ricevuta', NULL, 156),
    ('Acquisti', NULL, 157),
    ('alimentari', NULL, 157),
    ('Ruokaostokset', NULL, 158),
    ('Grocery', NULL, 159),
    ('shopping', NULL, 159),
    ('Food', NULL, 159),
    ('shopping', NULL, 159),
    ('Market', NULL, 160),
    ('Ruokakauppa', NULL, 161),
    ('Grocery', NULL, 162),
    ('store', NULL, 162),
    ('Componente', NULL, 163),
    ('Aine', NULL, 164),
    ('Component', NULL, 165),
    ('Preparazione', NULL, 166),
    ('Ohje', NULL, 167),
    ('Instructions', NULL, 168),
    ('Allergia', NULL, 169),
    ('Allergia', NULL, 170),
    ('Allergy', NULL, 171),
    ('Zucchero', NULL, 172),
    ('del', NULL, 172),
    ('latte', NULL, 172),
    ('Maitosokeri', NULL, 173),
    ('Milk', NULL, 174),
    ('sugar', NULL, 174),
    ('Proteina', NULL, 175),
    ('del', NULL, 175),
    ('grano', NULL, 175),
    ('Viljaproteiini', NULL, 176),
    ('Wheat', NULL, 177),
    ('protein', NULL, 177),
    ('Alimentazione', NULL, 178),
    ('vegetale', NULL, 178),
    ('Kasvisruokavalio', NULL, 179),
    ('Plant-based', NULL, 180),
    ('diet', NULL, 180),
    ('Miscela', NULL, 181),
    ('Drinkki', NULL, 182),
    ('Mixed', NULL, 183),
    ('drink', NULL, 183),
    ('Bionda', NULL, 184),
    ('Bisse', NULL, 185),
    ('Brew', NULL, 186),
    ('Rosso', NULL, 187),
    ('Punaviini', NULL, 188),
    ('Red', NULL, 189),
    ('Chef', NULL, 190),
    ('Keittäjä', NULL, 191),
    ('Chef', NULL, 192),
    ('Espresso', NULL, 193),
    ('Espresso', NULL, 194),
    ('Espresso', NULL, 195),
    ('cesta', NULL, 196),
    ('kärry', NULL, 197),
    ('shopping', NULL, 198),
    ('cart', NULL, 198),
    ('trolley', NULL, 198),
    ('promozione', NULL, 199),
    ('alennus', NULL, 200),
    ('promotion', NULL, 201),
    ('termine', NULL, 202),
    ('viimeinen', NULL, 203),
    ('käyttöpäivä', NULL, 203),
    ('parasta', NULL, 203),
    ('ennen', NULL, 203),
    ('expiration', NULL, 204),
    ('date', NULL, 204),
    ('best', NULL, 204),
    ('before', NULL, 204),
    ('date', NULL, 204),
    ('intolleranza', NULL, 205),
    ('yliherkkyys', NULL, 206),
    ('intolerance', NULL, 207),
    ('intolleranza', NULL, 208),
    ('al', NULL, 208),
    ('glutine', NULL, 208),
    ('gluteeniallergia', NULL, 209),
    ('celiac', NULL, 210),
    ('disease', NULL, 210),
    ('gluten', NULL, 210),
    ('intolerance', NULL, 210),
    ('banconiere', NULL, 211),
    ('tiskinhoitaja', NULL, 212),
    ('barkeep', NULL, 213),
    ('organico', NULL, 214),
    ('ekologinen', NULL, 215),
    ('ecological', NULL, 216),
    ('gustare', NULL, 217),
    ('kokeilla', NULL, 218),
    ('to', NULL, 219),
    ('taste', NULL, 219),
    ('to', NULL, 219),
    ('sample', NULL, 219),
    ('cuoco', NULL, 220),
    ('cook', NULL, 221),
    ('assaggiatore', NULL, 222),
    ('di', NULL, 222),
    ('vini', NULL, 222),
    ('viinituntija', NULL, 223),
    ('wine', NULL, 224),
    ('steward', NULL, 224),
    ('assaggio', NULL, 225),
    ('maistajaiset', NULL, 226),
    ('wine', NULL, 227),
    ('tasting', NULL, 227),
    ('sampling', NULL, 227),
    ('chilometro', NULL, 228),
    ('zero', NULL, 228),
    ('prodotti', NULL, 228),
    ('locali', NULL, 228),
    ('paikallinen', NULL, 229),
    ('tuote', NULL, 229),
    ('local', NULL, 230),
    ('produce', NULL, 230),
    ('locally', NULL, 230),
    ('sourced', NULL, 230),
    ('food', NULL, 230),
    ('Senza', NULL, 231),
    ('glutine', NULL, 231),
    ('Gluten', NULL, 231),
    ('free', NULL, 231),
    ('Ilman', NULL, 232),
    ('gluteenia', NULL, 232),
    ('No', NULL, 233),
    ('gluten', NULL, 233),
    ('Birra', NULL, 234),
    ('artigianale', NULL, 234),
    ('Birra', NULL, 234),
    ('speciale', NULL, 234),
    ('Pienpanimo', NULL, 235),
    ('olut', NULL, 235),
    ('Käsityöläisolut', NULL, 235),
    ('Craft', NULL, 236),
    ('beer', NULL, 236),
    ('Microbrew', NULL, 236),
    ('Comandare', NULL, 237),
    ('Pyytää', NULL, 238),
    ('To', NULL, 239),
    ('order', NULL, 239),
    ('To', NULL, 239),
    ('request', NULL, 239),
    ('Cucinare', NULL, 240),
    ('Valmistaa', NULL, 241),
    ('Sorseggiare', NULL, 242),
    ('Nauttia', NULL, 243),
    ('To', NULL, 244),
    ('drink', NULL, 244),
    ('To', NULL, 244),
    ('sip', NULL, 244),
    ('Saldare', NULL, 245),
    ('Suorittaa', NULL, 246),
    ('To', NULL, 247),
    ('pay', NULL, 247),
    ('To', NULL, 247),
    ('settle', NULL, 247),
    ('bottega', NULL, 248),
    ('liike', NULL, 249),
    ('store', NULL, 250),
    ('ufficio', NULL, 251),
    ('postale', NULL, 251),
    ('postikonttori', NULL, 252),
    ('post', NULL, 253),
    ('office', NULL, 253),
    ('mailing', NULL, 253),
    ('center', NULL, 253),
    ('istituto', NULL, 254),
    ('di', NULL, 254),
    ('credito', NULL, 254),
    ('rahalaitos', NULL, 255),
    ('financial', NULL, 256),
    ('institution', NULL, 256),
    ('comune', NULL, 257),
    ('kaupungintalo', NULL, 258),
    ('town', NULL, 259),
    ('hall', NULL, 259),
    ('city', NULL, 259),
    ('hall', NULL, 259),
    ('parafarmacia', NULL, 260),
    ('lääke', NULL, 261),
    ('drugstore', NULL, 262),
    ('mediateca', NULL, 263),
    ('kirjahuone', NULL, 264),
    ('book', NULL, 265),
    ('collection', NULL, 265),
    ('studio', NULL, 266),
    ('työtila', NULL, 267),
    ('workplace', NULL, 268),
    ('fiera', NULL, 269),
    ('markkinat', NULL, 270),
    ('fair', NULL, 271),
    ('caffè', NULL, 272),
    ('kahvila', NULL, 273),
    ('cafe', NULL, 274),
    ('autostazione', NULL, 275),
    ('asema-alue', NULL, 276),
    ('terminal', NULL, 277),
    ('clinica', NULL, 278),
    ('klinikka', NULL, 279),
    ('clinic', NULL, 280),
    ('istituto', NULL, 281),
    ('oppilaitos', NULL, 282),
    ('academy', NULL, 283),
    ('giardino', NULL, 284),
    ('pubblico', NULL, 284),
    ('viheralue', NULL, 285),
    ('public', NULL, 286),
    ('garden', NULL, 286),
    ('multisala', NULL, 287),
    ('leffateatteri', NULL, 288),
    ('movie', NULL, 289),
    ('theater', NULL, 289),
    ('auditorium', NULL, 290),
    ('näyttämö', NULL, 291),
    ('playhouse', NULL, 292),
    ('vasca', NULL, 293),
    ('allas', NULL, 294),
    ('swimming', NULL, 295),
    ('pool', NULL, 295),
    ('pool', NULL, 295),
    ('centro', NULL, 296),
    ('fitness', NULL, 296),
    ('treenisali', NULL, 297),
    ('fitness', NULL, 298),
    ('center', NULL, 298),
    ('tintoria', NULL, 299),
    ('pyykkipalvelu', NULL, 300),
    ('laundromat', NULL, 301),
    ('agenzia', NULL, 302),
    ('di', NULL, 302),
    ('viaggi', NULL, 302),
    ('tour', NULL, 302),
    ('operator', NULL, 302),
    ('matkanjärjestäjä', NULL, 303),
    ('travel', NULL, 304),
    ('agency', NULL, 304),
    ('tour', NULL, 304),
    ('operator', NULL, 304),
    ('palazzo', NULL, 305),
    ('di', NULL, 305),
    ('giustizia', NULL, 305),
    ('tribunale', NULL, 305),
    ('tuomioistuin', NULL, 306),
    ('court', NULL, 307),
    ('of', NULL, 307),
    ('law', NULL, 307),
    ('caserma', NULL, 308),
    ('dei', NULL, 308),
    ('pompieri', NULL, 308),
    ('distaccamento', NULL, 308),
    ('dei', NULL, 308),
    ('vigili', NULL, 308),
    ('del', NULL, 308),
    ('fuoco', NULL, 308),
    ('palokunta', NULL, 309),
    ('fire', NULL, 310),
    ('station', NULL, 310),
    ('firehouse', NULL, 310),
    ('commissariato', NULL, 311),
    ('di', NULL, 311),
    ('polizia', NULL, 311),
    ('questura', NULL, 311),
    ('poliisilaitos', NULL, 312),
    ('police', NULL, 313),
    ('station', NULL, 313),
    ('precinct', NULL, 313),
    ('scalo', NULL, 314),
    ('aeroportuale', NULL, 314),
    ('lentoasema', NULL, 315),
    ('airfield', NULL, 316),
    ('tempio', NULL, 317),
    ('temppeli', NULL, 318),
    ('chapel', NULL, 319),
    ('area', NULL, 320),
    ('di', NULL, 320),
    ('sosta', NULL, 320),
    ('parkkipaikka', NULL, 321),
    ('parking', NULL, 322),
    ('lot', NULL, 322),
    ('car', NULL, 322),
    ('park', NULL, 322),
    ('slargo', NULL, 323),
    ('tori', NULL, 324),
    ('plaza', NULL, 325),
    ('vigili', NULL, 326),
    ('del', NULL, 326),
    ('fuoco', NULL, 326),
    ('pompieri', NULL, 326),
    ('palomiehet', NULL, 327),
    ('questura', NULL, 328),
    ('centro', NULL, 329),
    ('commerciale', NULL, 329),
    ('galleria', NULL, 329),
    ('commerciale', NULL, 329),
    ('kauppakeskus', NULL, 330),
    ('shopping', NULL, 331),
    ('mall', NULL, 331),
    ('shopping', NULL, 331),
    ('center', NULL, 331),
    ('barbiere', NULL, 332),
    ('parturiliike', NULL, 333),
    ('barber', NULL, 334),
    ('shop', NULL, 334),
    ('Affetto', NULL, 335),
    ('Kiintymys', NULL, 336),
    ('Affection', NULL, 337),
    ('Gioia', NULL, 338),
    ('Ilo', NULL, 339),
    ('Joy', NULL, 340),
    ('Malinconia', NULL, 341),
    ('Murhe', NULL, 342),
    ('Sorrow', NULL, 343),
    ('Ira', NULL, 344),
    ('Raivo', NULL, 345),
    ('Wrath', NULL, 346),
    ('Timore', NULL, 347),
    ('Kauhu', NULL, 348),
    ('Dread', NULL, 349),
    ('Stupore', NULL, 350),
    ('Hämmästys', NULL, 351),
    ('Amazement', NULL, 352),
    ('Preoccupazione', NULL, 353),
    ('Huoli', NULL, 354),
    ('Worry', NULL, 355),
    ('Ottimismo', NULL, 356),
    ('Usko', NULL, 357),
    ('Optimism', NULL, 358),
    ('Frustrazione', NULL, 359),
    ('Turhautuminen', NULL, 360),
    ('Frustration', NULL, 361),
    ('Comprensione', NULL, 362),
    ('Myötätunto', NULL, 363),
    ('Understanding', NULL, 364),
    ('Entusiasmo', NULL, 365),
    ('Kiihko', NULL, 366),
    ('Enthusiasm', NULL, 367),
    ('Pentimento', NULL, 368),
    ('Harmitus', NULL, 369),
    ('Remorse', NULL, 370),
    ('Credenza', NULL, 371),
    ('Usko', NULL, 372),
    ('Belief', NULL, 373),
    ('Invidia', NULL, 374),
    ('Kateus', NULL, 375),
    ('Envy', NULL, 376),
    ('Appagamento', NULL, 377),
    ('Mielihyvä', NULL, 378),
    ('Contentment', NULL, 379),
    ('Vanto', NULL, 380),
    ('Kunnioitus', NULL, 381),
    ('Dignity', NULL, 382),
    ('Isolamento', NULL, 383),
    ('Eristäminen', NULL, 384),
    ('Isolation', NULL, 385),
    ('Vivacità', NULL, 386),
    ('Kiihkeys', NULL, 387),
    ('Excitement', NULL, 388),
    ('Inquietudine', NULL, 389),
    ('Levottomuus', NULL, 390),
    ('Concern', NULL, 391),
    ('Riconoscenza', NULL, 392),
    ('Arvostus', NULL, 393),
    ('Thankfulness', NULL, 394),
    ('Allegria', NULL, 395),
    ('Onni', NULL, 396),
    ('Happiness', NULL, 397),
    ('Esasperazione', NULL, 398),
    ('Ärtymys', NULL, 399),
    ('Exasperation', NULL, 400),
    ('Rimpianto', NULL, 401),
    ('Kaiho', NULL, 402),
    ('Longing', NULL, 403),
    ('Accettazione', NULL, 404),
    ('Hyväksyminen', NULL, 405),
    ('Acceptance', NULL, 406),
    ('Tranquillità', NULL, 407),
    ('Rauhallisuus', NULL, 408),
    ('Tranquility', NULL, 409),
    ('Gelosia', NULL, 410),
    ('Mustasukkaisuus', NULL, 411),
    ('Jealousy', NULL, 412),
    ('Pentimento', NULL, 413),
    ('Regret', NULL, 414),
    ('Stima', NULL, 415),
    ('Kunnioitus', NULL, 416),
    ('Esteem', NULL, 417),
    ('Avversione', NULL, 418),
    ('Aversion', NULL, 419),
    ('Etichetta', NULL, 420),
    ('digitale', NULL, 420),
    ('Verkkokäyttäytyminen', NULL, 421),
    ('Online', NULL, 422),
    ('etiquette', NULL, 422),
    ('Riservatezza', NULL, 423),
    ('Salassapito', NULL, 424),
    ('Confidentiality', NULL, 425),
    ('Bullismo', NULL, 426),
    ('online', NULL, 426),
    ('Verkkokiusaaminen', NULL, 427),
    ('Online', NULL, 428),
    ('bullying', NULL, 428),
    ('Identità', NULL, 429),
    ('digitale', NULL, 429),
    ('Profilo', NULL, 429),
    ('online', NULL, 429),
    ('Digitaalinen', NULL, 430),
    ('identiteetti', NULL, 430),
    ('Verkkoprofiili', NULL, 430),
    ('Digital', NULL, 431),
    ('identity', NULL, 431),
    ('Online', NULL, 431),
    ('profile', NULL, 431),
    ('Fake', NULL, 432),
    ('news', NULL, 432),
    ('Notizie', NULL, 432),
    ('false', NULL, 432),
    ('Väärät', NULL, 433),
    ('uutiset', NULL, 433),
    ('Fake', NULL, 434),
    ('news', NULL, 434),
    ('False', NULL, 434),
    ('news', NULL, 434),
    ('Autorizzazione', NULL, 435),
    ('Lupa', NULL, 436),
    ('Permission', NULL, 437),
    ('Responsabilità', NULL, 438),
    ('digitale', NULL, 438),
    ('Dovere', NULL, 438),
    ('online', NULL, 438),
    ('Digitaalinen', NULL, 439),
    ('vastuu', NULL, 439),
    ('Verkkotehtävä', NULL, 439),
    ('Digital', NULL, 440),
    ('responsibility', NULL, 440),
    ('Online', NULL, 440),
    ('duty', NULL, 440),
    ('Diritto', NULL, 441),
    ('d''autore', NULL, 441),
    ('Tekijän', NULL, 442),
    ('oikeudet', NULL, 442),
    ('Author''s', NULL, 443),
    ('rights', NULL, 443),
    ('Hate', NULL, 444),
    ('speech', NULL, 444),
    ('Incitamento', NULL, 444),
    ('all''odio', NULL, 444),
    ('Vihaan', NULL, 445),
    ('yllyttäminen', NULL, 445),
    ('Hate', NULL, 446),
    ('speech', NULL, 446),
    ('Incitement', NULL, 446),
    ('to', NULL, 446),
    ('hatred', NULL, 446),
    ('Sicurezza', NULL, 447),
    ('informatica', NULL, 447),
    ('Protezione', NULL, 447),
    ('dati', NULL, 447),
    ('Datensuoja', NULL, 448),
    ('Data', NULL, 449),
    ('protection', NULL, 449),
    ('Chiarezza', NULL, 450),
    ('Selkeys', NULL, 451),
    ('Clarity', NULL, 452),
    ('Fruibilità', NULL, 453),
    ('Käytettävyys', NULL, 454),
    ('Usability', NULL, 455),
    ('Sequenza', NULL, 456),
    ('logica', NULL, 456),
    ('Looginen', NULL, 457),
    ('sarja', NULL, 457),
    ('Logical', NULL, 458),
    ('sequence', NULL, 458),
    ('Dati', NULL, 459),
    ('personali', NULL, 459),
    ('Informazioni', NULL, 459),
    ('personali', NULL, 459),
    ('Henkilökohtaiset', NULL, 460),
    ('tiedot', NULL, 460),
    ('Personal', NULL, 461),
    ('data', NULL, 461),
    ('Personal', NULL, 461),
    ('information', NULL, 461),
    ('Cifratura', NULL, 462),
    ('Koodaus', NULL, 463),
    ('Coding', NULL, 464),
    ('Truffa', NULL, 465),
    ('online', NULL, 465),
    ('Verkkopetos', NULL, 466),
    ('Online', NULL, 467),
    ('scam', NULL, 467),
    ('Impronta', NULL, 468),
    ('digitale', NULL, 468),
    ('Traccia', NULL, 468),
    ('online', NULL, 468),
    ('Digitaalinen', NULL, 469),
    ('jalanjälki', NULL, 469),
    ('Verkkotunniste', NULL, 469),
    ('Digital', NULL, 470),
    ('footprint', NULL, 470),
    ('Online', NULL, 470),
    ('trace', NULL, 470),
    ('Libertà', NULL, 471),
    ('di', NULL, 471),
    ('espressione', NULL, 471),
    ('Diritto', NULL, 471),
    ('di', NULL, 471),
    ('parola', NULL, 471),
    ('Ilmaisunvapaus', NULL, 472),
    ('Freedom', NULL, 473),
    ('of', NULL, 473),
    ('speech', NULL, 473),
    ('Freedom', NULL, 473),
    ('of', NULL, 473),
    ('expression', NULL, 473),
    ('Moderazione', NULL, 474),
    ('dei', NULL, 474),
    ('contenuti', NULL, 474),
    ('Controllo', NULL, 474),
    ('dei', NULL, 474),
    ('contenuti', NULL, 474),
    ('Sisällön', NULL, 475),
    ('moderointi', NULL, 475),
    ('Sisällön', NULL, 475),
    ('valvonta', NULL, 475),
    ('Content', NULL, 476),
    ('moderation', NULL, 476),
    ('Content', NULL, 476),
    ('control', NULL, 476),
    ('Divario', NULL, 477),
    ('digitale', NULL, 477),
    ('Disuguaglianza', NULL, 477),
    ('digitale', NULL, 477),
    ('Digitaalinen', NULL, 478),
    ('kuilu', NULL, 478),
    ('Digitaalinen', NULL, 478),
    ('epätasa-arvo', NULL, 478),
    ('Digital', NULL, 479),
    ('divide', NULL, 479),
    ('Digital', NULL, 479),
    ('inequality', NULL, 479),
    ('Pirata', NULL, 480),
    ('informatico', NULL, 480),
    ('Tietomurtoilija', NULL, 481),
    ('Computer', NULL, 482),
    ('pirate', NULL, 482),
    ('Diritto', NULL, 483),
    ('all''oblio', NULL, 483),
    ('Rimozione', NULL, 483),
    ('dati', NULL, 483),
    ('Oikeus', NULL, 484),
    ('tulla', NULL, 484),
    ('unohdetuksi', NULL, 484),
    ('Tietojen', NULL, 484),
    ('poisto', NULL, 484),
    ('Right', NULL, 485),
    ('to', NULL, 485),
    ('be', NULL, 485),
    ('forgotten', NULL, 485),
    ('Data', NULL, 485),
    ('removal', NULL, 485),
    ('Post', NULL, 486),
    ('verità', NULL, 486),
    ('Emozioni', NULL, 486),
    ('>', NULL, 486),
    ('fatti', NULL, 486)
ON CONFLICT DO NOTHING;

COMMIT;