-- seed_03_3_lemma.sql - Author: Stefania Julin
-- lemma part 3/3 (533 rows) + morpho_form (830 rows)
BEGIN;

INSERT INTO lemma (lemma_id, text_root, grammatical_category, frequency_rank, interference_json, variant_id) VALUES
    (1071, 'graduation ceremony', 'noun', NULL, NULL, 3),
    (1072, 'tassa universitaria', 'noun', NULL, '{"standard_translation_EN": "tuition fee", "standard_translation_IT": "tassa universitaria", "note_culturale": "Le tasse universitarie variano a seconda dell''università."}', 1),
    (1073, 'lukukausimaksu', 'noun', NULL, NULL, 2),
    (1074, 'tuition fee', 'noun', NULL, NULL, 3),
    (1075, 'esame di ammissione', 'noun', NULL, '{"standard_translation_EN": "entrance exam", "standard_translation_IT": "esame di ammissione", "note_culturale": "L''esame di ammissione è necessario per entrare in alcune università."}', 1),
    (1076, 'pääsykoe', 'noun', NULL, NULL, 2),
    (1077, 'entrance exam', 'noun', NULL, NULL, 3),
    (1078, 'tirocinio', 'noun', NULL, '{"standard_translation_EN": "internship", "standard_translation_IT": "tirocinio", "note_culturale": "Il tirocinio è un''esperienza lavorativa formativa."}', 1),
    (1079, 'harjoittelu', 'noun', NULL, NULL, 2),
    (1080, 'internship', 'noun', NULL, NULL, 3),
    (1081, 'area studio', 'noun', NULL, '{"standard_translation_EN": "study area", "standard_translation_IT": "area studio", "note_culturale": "Le aree studio sono spazi dedicati allo studio."}', 1),
    (1082, 'opiskelualue', 'noun', NULL, NULL, 2),
    (1083, 'study area', 'noun', NULL, NULL, 3),
    (1084, 'sessione d''esame', 'noun', NULL, '{"standard_translation_EN": "exam period", "standard_translation_IT": "sessione d''esame", "note_culturale": "La sessione d''esame è un periodo intenso per gli studenti."}', 1),
    (1085, 'tenttikausi', 'noun', NULL, NULL, 2),
    (1086, 'exam period', 'noun', NULL, NULL, 3),
    (1087, 'libri di testo', 'noun', NULL, '{"standard_translation_EN": "textbooks", "standard_translation_IT": "libri di testo", "note_culturale": "I libri di testo sono essenziali per lo studio."}', 1),
    (1088, 'oppikirjat', 'noun', NULL, NULL, 2),
    (1089, 'textbooks', 'noun', NULL, NULL, 3),
    (1090, 'verbalizzare', 'verb', NULL, '{"standard_translation_EN": "to record a grade", "standard_translation_IT": "verbalizzare", "note_culturale": "Verbalizzare un esame significa registrare ufficialmente il voto."}', 1),
    (1091, 'kirjata arvosana', 'verb', NULL, NULL, 2),
    (1092, 'to record a grade', 'verb', NULL, NULL, 3),
    (1093, 'sessione straordinaria', 'noun', NULL, '{"standard_translation_EN": "resit exam", "standard_translation_IT": "sessione straordinaria", "note_culturale": "La sessione straordinaria è un''opportunità per rifare un esame."}', 1),
    (1094, 'uusintatentti', 'noun', NULL, NULL, 2),
    (1095, 'resit exam', 'noun', NULL, NULL, 3),
    (1096, 'bibliotecario', 'noun', NULL, '{"standard_translation_EN": "librarian", "standard_translation_IT": "bibliotecario", "note_culturale": "Il bibliotecario aiuta a trovare i libri."}', 1),
    (1097, 'kirjastonhoitaja', 'noun', NULL, NULL, 2),
    (1098, 'librarian', 'noun', NULL, NULL, 3),
    (1099, 'dottorato', 'noun', NULL, '{"standard_translation_EN": "PhD", "standard_translation_IT": "dottorato", "note_culturale": "Il dottorato è il livello più alto di istruzione universitaria."}', 1),
    (1100, 'tohtorintutkinto', 'noun', NULL, NULL, 2),
    (1101, 'PhD', 'noun', NULL, NULL, 3),
    (1102, 'tesina', 'noun', NULL, '{"standard_translation_EN": "essay", "standard_translation_IT": "tesina", "note_culturale": "La tesina è un compito scritto su un argomento specifico."}', 1),
    (1103, 'esseet', 'noun', NULL, NULL, 2),
    (1104, 'essay', 'noun', NULL, NULL, 3),
    (1105, 'copiare', 'verb', NULL, '{"standard_translation_EN": "to cheat", "standard_translation_IT": "copiare", "note_culturale": "Copiare durante un esame è vietato."}', 1),
    (1106, 'lunttaaminen', 'verb', NULL, NULL, 2),
    (1107, 'to cheat', 'verb', NULL, NULL, 3),
    (1108, 'spiegare', 'verb', NULL, '{"standard_translation_EN": "to explain", "standard_translation_IT": "spiegare", "note_culturale": "Il professore deve spiegare bene i concetti."}', 1),
    (1109, 'selittää', 'verb', NULL, NULL, 2),
    (1110, 'to explain', 'verb', NULL, NULL, 3),
    (1111, 'ripassare', 'verb', NULL, '{"standard_translation_EN": "to revise", "standard_translation_IT": "ripassare", "note_culturale": "È importante ripassare prima di un esame."}', 1),
    (1112, 'kerrata', 'verb', NULL, NULL, 2),
    (1113, 'to revise', 'verb', NULL, NULL, 3),
    (1114, 'prezzo', 'noun', NULL, '{"standard_translation_EN": "price", "standard_translation_IT": "prezzo", "note_culturale": "Il prezzo è l''ammontare di denaro necessario per acquistare un bene o servizio."}', 1),
    (1115, 'hinta', 'noun', NULL, NULL, 2),
    (1116, 'price', 'noun', NULL, NULL, 3),
    (1117, 'sconto', 'noun', NULL, '{"standard_translation_EN": "discount", "standard_translation_IT": "sconto", "note_culturale": "Uno sconto è una riduzione del prezzo originale."}', 1),
    (1118, 'alennus', 'noun', NULL, NULL, 2),
    (1119, 'discount', 'noun', NULL, NULL, 3),
    (1120, 'pagamento', 'noun', NULL, '{"standard_translation_EN": "payment", "standard_translation_IT": "pagamento", "note_culturale": "Il pagamento è l''atto di dare denaro per beni o servizi."}', 1),
    (1121, 'maksu', 'noun', NULL, NULL, 2),
    (1122, 'payment', 'noun', NULL, NULL, 3),
    (1123, 'bilancio', 'noun', NULL, '{"standard_translation_EN": "budget", "standard_translation_IT": "bilancio", "note_culturale": "Un bilancio è un piano finanziario per un periodo di tempo."}', 1),
    (1124, 'budjetti', 'noun', NULL, NULL, 2),
    (1125, 'budget', 'noun', NULL, NULL, 3),
    (1126, 'risparmio', 'noun', NULL, '{"standard_translation_EN": "saving", "standard_translation_IT": "risparmio", "note_culturale": "Il risparmio è la parte di reddito non spesa."}', 1),
    (1127, 'säästö', 'noun', NULL, NULL, 2),
    (1128, 'saving', 'noun', NULL, NULL, 3),
    (1129, 'meno', 'noun', NULL, NULL, 2),
    (1130, 'expense', 'noun', NULL, NULL, 3),
    (1131, 'reddito', 'noun', NULL, '{"standard_translation_EN": "income", "standard_translation_IT": "reddito", "note_culturale": "Il reddito è l''ammontare di denaro che si riceve."}', 1),
    (1132, 'tulot', 'noun', NULL, NULL, 2),
    (1133, 'income', 'noun', NULL, NULL, 3),
    (1134, 'tassa', 'noun', NULL, '{"standard_translation_EN": "tax", "standard_translation_IT": "tassa", "note_culturale": "Una tassa è un pagamento obbligatorio al governo."}', 1),
    (1135, 'vero', 'noun', NULL, NULL, 2),
    (1136, 'tax', 'noun', NULL, NULL, 3),
    (1137, 'valuta', 'noun', NULL, '{"standard_translation_EN": "currency", "standard_translation_IT": "valuta", "note_culturale": "La valuta è il sistema di denaro in uso in un particolare paese."}', 1),
    (1138, 'valuutta', 'noun', NULL, NULL, 2),
    (1139, 'currency', 'noun', NULL, NULL, 3),
    (1140, 'inflazione', 'noun', NULL, '{"standard_translation_EN": "inflation", "standard_translation_IT": "inflazione", "note_culturale": "L''inflazione è l''aumento generale dei prezzi e la diminuzione del potere d''acquisto."}', 1),
    (1141, 'inflaatio', 'noun', NULL, NULL, 2),
    (1142, 'inflation', 'noun', NULL, NULL, 3),
    (1143, 'mutuo', 'noun', NULL, '{"standard_translation_EN": "mortgage", "standard_translation_IT": "mutuo", "note_culturale": "Un mutuo è un prestito per acquistare una casa."}', 1),
    (1144, 'asuntolaina', 'noun', NULL, NULL, 2),
    (1145, 'mortgage', 'noun', NULL, NULL, 3),
    (1146, 'investimento', 'noun', NULL, '{"standard_translation_EN": "investment", "standard_translation_IT": "investimento", "note_culturale": "Un investimento è l''impiego di denaro per ottenere un profitto futuro."}', 1),
    (1147, 'sijoitus', 'noun', NULL, NULL, 2),
    (1148, 'investment', 'noun', NULL, NULL, 3),
    (1149, 'carta di credito', 'noun', NULL, '{"standard_translation_EN": "credit card", "standard_translation_IT": "carta di credito", "note_culturale": "Una carta di credito permette di effettuare acquisti a debito."}', 1),
    (1150, 'luottokortti', 'noun', NULL, NULL, 2),
    (1151, 'credit card', 'noun', NULL, NULL, 3),
    (1152, 'bancomat', 'noun', NULL, '{"standard_translation_EN": "ATM", "standard_translation_IT": "bancomat", "note_culturale": "Un bancomat permette di prelevare contanti."}', 1),
    (1153, 'pankkiautomaatti', 'noun', NULL, NULL, 2),
    (1154, 'ATM', 'noun', NULL, NULL, 3),
    (1155, 'borsa', 'noun', NULL, '{"standard_translation_EN": "stock market", "standard_translation_IT": "borsa", "note_culturale": "La borsa è un mercato dove si comprano e vendono azioni."}', 1),
    (1156, 'pörssi', 'noun', NULL, NULL, 2),
    (1157, 'stock market', 'noun', NULL, NULL, 3),
    (1158, 'debito', 'noun', NULL, '{"standard_translation_EN": "debt", "standard_translation_IT": "debito", "note_culturale": "Il debito è una somma di denaro dovuta."}', 1),
    (1159, 'velka', 'noun', NULL, NULL, 2),
    (1160, 'debt', 'noun', NULL, NULL, 3),
    (1161, 'interesse', 'noun', NULL, '{"standard_translation_EN": "interest", "standard_translation_IT": "interesse", "note_culturale": "L''interesse è il costo del denaro preso in prestito."}', 1),
    (1162, 'korko', 'noun', NULL, NULL, 2),
    (1163, 'interest', 'noun', NULL, NULL, 3),
    (1164, 'assicurazione', 'noun', NULL, '{"standard_translation_EN": "insurance", "standard_translation_IT": "assicurazione", "note_culturale": "L''assicurazione è un contratto per proteggere da rischi finanziari."}', 1),
    (1165, 'vakuutus', 'noun', NULL, NULL, 2),
    (1166, 'insurance', 'noun', NULL, NULL, 3),
    (1167, 'Budget', 'noun', NULL, '{"standard_translation_EN": "Budget", "standard_translation_IT": "Budget", "note_culturale": "Strumento per pianificare entrate e uscite."}', 1),
    (1168, 'Kulu', 'noun', NULL, NULL, 2),
    (1169, 'Guadagno', 'noun', NULL, '{"standard_translation_EN": "Income", "standard_translation_IT": "Guadagno", "note_culturale": "Denaro ricevuto per lavoro o investimenti."}', 1),
    (1170, 'Tulo', 'noun', NULL, NULL, 2),
    (1171, 'Contanti', 'noun', NULL, '{"standard_translation_EN": "Cash", "standard_translation_IT": "Contanti", "note_culturale": "Banconote e monete."}', 1),
    (1172, 'Käteinen', 'noun', NULL, NULL, 2),
    (1173, 'Cash', 'noun', NULL, NULL, 3),
    (1174, 'Tasso di interesse', 'noun', NULL, '{"standard_translation_EN": "Interest rate", "standard_translation_IT": "Tasso di interesse", "note_culturale": "Percentuale applicata a un prestito o investimento."}', 1),
    (1175, 'Interest rate', 'noun', NULL, NULL, 3),
    (1176, 'Saldo', 'noun', NULL, '{"standard_translation_EN": "Balance", "standard_translation_IT": "Saldo", "note_culturale": "Quantità di denaro disponibile in un conto."}', 1),
    (1177, 'Saldo', 'noun', NULL, NULL, 2),
    (1178, 'Balance', 'noun', NULL, NULL, 3),
    (1179, 'Commissione', 'noun', NULL, '{"standard_translation_EN": "Commission", "standard_translation_IT": "Commissione", "note_culturale": "Costo per un servizio finanziario."}', 1),
    (1180, 'Palkkio', 'noun', NULL, NULL, 2),
    (1181, 'Commission', 'noun', NULL, NULL, 3),
    (1182, 'Bilancio familiare', 'noun', NULL, '{"standard_translation_EN": "Family budget", "standard_translation_IT": "Bilancio familiare", "note_culturale": "Pianificazione delle entrate e delle uscite familiari."}', 1),
    (1183, 'Perhebudjetti', 'noun', NULL, NULL, 2),
    (1184, 'Family budget', 'noun', NULL, NULL, 3),
    (1185, 'carta_di_credito', 'noun', NULL, '{"standard_translation_EN": "credit_card", "standard_translation_IT": "carta_di_credito", "note_culturale": "Una carta di credito permette di effettuare acquisti a debito, con pagamento differito."}', 1),
    (1186, 'credit_card', 'noun', NULL, NULL, 3),
    (1187, 'lusso', 'noun', NULL, '{"standard_translation_EN": "luxury", "standard_translation_IT": "lusso", "note_culturale": "Il lusso si riferisce a beni e servizi costosi e non essenziali."}', 1),
    (1188, 'ylellisyys', 'noun', NULL, NULL, 2),
    (1189, 'luxury', 'noun', NULL, NULL, 3),
    (1190, 'voitto', 'noun', NULL, NULL, 2),
    (1191, 'profit', 'noun', NULL, NULL, 3),
    (1192, 'tasso di cambio', 'noun', NULL, '{"standard_translation_EN": "exchange rate", "standard_translation_IT": "tasso di cambio", "note_culturale": "Il tasso di cambio è il valore di una valuta rispetto a un''altra."}', 1),
    (1193, 'valuuttakurssi', 'noun', NULL, NULL, 2),
    (1194, 'exchange rate', 'noun', NULL, NULL, 3),
    (1195, 'portafoglio', 'noun', NULL, '{"standard_translation_EN": "wallet", "standard_translation_IT": "portafoglio", "note_culturale": "Un portafoglio è un oggetto per contenere denaro e carte."}', 1),
    (1196, 'lompakko', 'noun', NULL, NULL, 2),
    (1197, 'wallet', 'noun', NULL, NULL, 3),
    (1198, 'Liquidità', 'noun', NULL, '{"standard_translation_EN": "Liquidity", "standard_translation_IT": "Liquidità", "note_culturale": "La liquidità è la capacità di un''azienda o individuo di far fronte ai propri impegni finanziari a breve termine."}', 1),
    (1199, 'Likviditeetti', 'noun', NULL, NULL, 2),
    (1200, 'Liquidity', 'noun', NULL, NULL, 3),
    (1201, 'Smartphone', 'noun', NULL, '{"standard_translation_EN": "Smartphone", "standard_translation_IT": "Smartphone", "note_culturale": "Dispositivo mobile multifunzione."}', 1),
    (1202, 'Älypuhelin', 'noun', NULL, NULL, 2),
    (1203, 'Smartphone', 'noun', NULL, NULL, 3),
    (1204, 'Social media', 'noun', NULL, '{"standard_translation_EN": "Social media", "standard_translation_IT": "Social media", "note_culturale": "Piattaforme online per la comunicazione."}', 1),
    (1205, 'Sosiaalinen media', 'noun', NULL, NULL, 2),
    (1206, 'Social media', 'noun', NULL, NULL, 3),
    (1207, 'Internet', 'noun', NULL, '{"standard_translation_EN": "Internet", "standard_translation_IT": "Internet", "note_culturale": "Rete globale di computer."}', 1),
    (1208, 'Internet', 'noun', NULL, NULL, 2),
    (1209, 'Internet', 'noun', NULL, NULL, 3),
    (1210, 'Video', 'noun', NULL, '{"standard_translation_EN": "Video", "standard_translation_IT": "Video", "note_culturale": "Registrazione di immagini in movimento."}', 1),
    (1211, 'Video', 'noun', NULL, NULL, 2),
    (1212, 'Video', 'noun', NULL, NULL, 3),
    (1213, 'Messaggio', 'noun', NULL, '{"standard_translation_EN": "Message", "standard_translation_IT": "Messaggio", "note_culturale": "Comunicazione scritta o vocale."}', 1),
    (1214, 'Viesti', 'noun', NULL, NULL, 2),
    (1215, 'Message', 'noun', NULL, NULL, 3),
    (1216, 'Notifica', 'noun', NULL, '{"standard_translation_EN": "Notification", "standard_translation_IT": "Notifica", "note_culturale": "Avviso di un evento o aggiornamento."}', 1),
    (1217, 'Ilmoitus', 'noun', NULL, NULL, 2),
    (1218, 'Notification', 'noun', NULL, NULL, 3),
    (1219, 'Post', 'noun', NULL, '{"standard_translation_EN": "Post", "standard_translation_IT": "Post", "note_culturale": "Contenuto pubblicato online."}', 1),
    (1220, 'Postaus', 'noun', NULL, NULL, 2),
    (1221, 'Post', 'noun', NULL, NULL, 3),
    (1222, 'Live', 'noun', NULL, '{"standard_translation_EN": "Live", "standard_translation_IT": "Live", "note_culturale": "Trasmissione in tempo reale."}', 1),
    (1223, 'Live', 'noun', NULL, NULL, 2),
    (1224, 'Live', 'noun', NULL, NULL, 3),
    (1225, 'Hashtag', 'noun', NULL, '{"standard_translation_EN": "Hashtag", "standard_translation_IT": "Hashtag", "note_culturale": "Parola chiave preceduta da #."}', 1),
    (1226, 'Hashtag', 'noun', NULL, NULL, 2),
    (1227, 'Hashtag', 'noun', NULL, NULL, 3),
    (1228, 'Download', 'noun', NULL, '{"standard_translation_EN": "Download", "standard_translation_IT": "Download", "note_culturale": "Trasferimento di dati da un server a un dispositivo."}', 1),
    (1229, 'Lataus', 'noun', NULL, NULL, 2),
    (1230, 'Download', 'noun', NULL, NULL, 3),
    (1231, 'Upload', 'noun', NULL, '{"standard_translation_EN": "Upload", "standard_translation_IT": "Upload", "note_culturale": "Trasferimento di dati da un dispositivo a un server."}', 1),
    (1232, 'Lähetys', 'noun', NULL, NULL, 2),
    (1233, 'Upload', 'noun', NULL, NULL, 3),
    (1234, 'Streaming', 'noun', NULL, '{"standard_translation_EN": "Streaming", "standard_translation_IT": "Streaming", "note_culturale": "Riproduzione di contenuti multimediali in tempo reale."}', 1),
    (1235, 'Striimaus', 'noun', NULL, NULL, 2),
    (1236, 'Streaming', 'noun', NULL, NULL, 3),
    (1237, 'Podcast', 'noun', NULL, '{"standard_translation_EN": "Podcast", "standard_translation_IT": "Podcast", "note_culturale": "Episodio audio disponibile online."}', 1),
    (1238, 'Podcast', 'noun', NULL, NULL, 2),
    (1239, 'Podcast', 'noun', NULL, NULL, 3),
    (1240, 'App', 'noun', NULL, '{"standard_translation_EN": "App", "standard_translation_IT": "App", "note_culturale": "Programma software per dispositivi mobili."}', 1),
    (1241, 'Sovellus', 'noun', NULL, NULL, 2),
    (1242, 'App', 'noun', NULL, NULL, 3),
    (1243, 'Browser', 'noun', NULL, '{"standard_translation_EN": "Browser", "standard_translation_IT": "Browser", "note_culturale": "Programma per navigare in internet."}', 1),
    (1244, 'Selain', 'noun', NULL, NULL, 2),
    (1245, 'Browser', 'noun', NULL, NULL, 3),
    (1246, 'Cloud', 'noun', NULL, '{"standard_translation_EN": "Cloud", "standard_translation_IT": "Cloud", "note_culturale": "Spazio di archiviazione dati online."}', 1),
    (1247, 'Pilvi', 'noun', NULL, NULL, 2),
    (1248, 'Cloud', 'noun', NULL, NULL, 3),
    (1249, 'Chat', 'noun', NULL, '{"standard_translation_EN": "Chat", "standard_translation_IT": "Chat", "note_culturale": "Conversazione testuale in tempo reale."}', 1),
    (1250, 'Chatti', 'noun', NULL, NULL, 2),
    (1251, 'Chat', 'noun', NULL, NULL, 3),
    (1252, 'Emoji', 'noun', NULL, '{"standard_translation_EN": "Emoji", "standard_translation_IT": "Emoji", "note_culturale": "Simbolo grafico per esprimere emozioni."}', 1),
    (1253, 'Emoji', 'noun', NULL, NULL, 2),
    (1254, 'Emoji', 'noun', NULL, NULL, 3),
    (1255, 'Aggiornamento', 'noun', NULL, '{"standard_translation_EN": "Update", "standard_translation_IT": "Aggiornamento", "note_culturale": "Nuova versione di un software."}', 1),
    (1256, 'Päivitys', 'noun', NULL, NULL, 2),
    (1257, 'Update', 'noun', NULL, NULL, 3),
    (1258, 'Profilo', 'noun', NULL, '{"standard_translation_EN": "Profile", "standard_translation_IT": "Profilo", "note_culturale": "Pagina personale su un social network."}', 1),
    (1259, 'Profiili', 'noun', NULL, NULL, 2),
    (1260, 'Profile', 'noun', NULL, NULL, 3),
    (1261, 'Selfie', 'noun', NULL, '{"standard_translation_EN": "Selfie", "standard_translation_IT": "Selfie", "note_culturale": "Fotografia scattata a se stessi."}', 1),
    (1262, 'Selfie', 'noun', NULL, NULL, 2),
    (1263, 'Selfie', 'noun', NULL, NULL, 3),
    (1264, 'Batteria', 'noun', NULL, '{"standard_translation_EN": "Battery", "standard_translation_IT": "Batteria", "note_culturale": "Dispositivo che fornisce energia elettrica."}', 1),
    (1265, 'Akku', 'noun', NULL, NULL, 2),
    (1266, 'Battery', 'noun', NULL, NULL, 3),
    (1267, 'Like', 'noun', NULL, '{"standard_translation_EN": "Like", "standard_translation_IT": "Like", "note_culturale": "Reazione positiva a un contenuto sui social media."}', 1),
    (1268, 'Tykkäys', 'noun', NULL, NULL, 2),
    (1269, 'Like', 'noun', NULL, NULL, 3),
    (1270, 'Account', 'noun', NULL, '{"standard_translation_EN": "Account", "standard_translation_IT": "Account", "note_culturale": "Spazio personale online."}', 1),
    (1271, 'Tili', 'noun', NULL, NULL, 2),
    (1272, 'Account', 'noun', NULL, NULL, 3),
    (1273, 'Memoria', 'noun', NULL, '{"standard_translation_EN": "Memory", "standard_translation_IT": "Memoria", "note_culturale": "Spazio per salvare dati."}', 1),
    (1274, 'Muisti', 'noun', NULL, NULL, 2),
    (1275, 'Memory', 'noun', NULL, NULL, 3),
    (1276, 'Seguire', 'verb', NULL, '{"standard_translation_EN": "Follow", "standard_translation_IT": "Seguire", "note_culturale": "Ricevere aggiornamenti da un utente o pagina."}', 1),
    (1277, 'Seurata', 'verb', NULL, NULL, 2),
    (1278, 'Follow', 'verb', NULL, NULL, 3),
    (1279, 'Commento', 'noun', NULL, '{"standard_translation_EN": "Comment", "standard_translation_IT": "Commento", "note_culturale": "Opinione o reazione scritta a un contenuto."}', 1),
    (1280, 'Kommentti', 'noun', NULL, NULL, 2),
    (1281, 'Comment', 'noun', NULL, NULL, 3),
    (1282, 'calcio', 'noun', NULL, '{"standard_translation_EN": "football", "standard_translation_IT": "calcio", "note_culturale": "Sport di squadra più popolare in Italia."}', 1),
    (1283, 'jalkapallo', 'noun', NULL, NULL, 2),
    (1284, 'football', 'noun', NULL, NULL, 3),
    (1285, 'chitarra', 'noun', NULL, '{"standard_translation_EN": "guitar", "standard_translation_IT": "chitarra", "note_culturale": "Strumento musicale a corde molto diffuso."}', 1),
    (1286, 'kitara', 'noun', NULL, NULL, 2),
    (1287, 'guitar', 'noun', NULL, NULL, 3),
    (1288, 'elokuva', 'noun', NULL, NULL, 2),
    (1289, 'libro', 'noun', NULL, '{"standard_translation_EN": "book", "standard_translation_IT": "libro", "note_culturale": "Raccolta di fogli stampati e rilegati."}', 1),
    (1290, 'kirja', 'noun', NULL, NULL, 2),
    (1291, 'book', 'noun', NULL, NULL, 3),
    (1292, 'corsa', 'noun', NULL, '{"standard_translation_EN": "running", "standard_translation_IT": "corsa", "note_culturale": "Attività fisica aerobica."}', 1),
    (1293, 'juoksu', 'noun', NULL, NULL, 2),
    (1294, 'running', 'noun', NULL, NULL, 3),
    (1295, 'concerto', 'noun', NULL, '{"standard_translation_EN": "concert", "standard_translation_IT": "concerto", "note_culturale": "Esecuzione pubblica di musica."}', 1),
    (1296, 'konsertti', 'noun', NULL, NULL, 2),
    (1297, 'concert', 'noun', NULL, NULL, 3),
    (1298, 'romanzo', 'noun', NULL, '{"standard_translation_EN": "novel", "standard_translation_IT": "romanzo", "note_culturale": "Opera letteraria in prosa, di ampio respiro."}', 1),
    (1299, 'romaani', 'noun', NULL, NULL, 2),
    (1300, 'novel', 'noun', NULL, NULL, 3),
    (1301, 'nuoto', 'noun', NULL, '{"standard_translation_EN": "swimming", "standard_translation_IT": "nuoto", "note_culturale": "Sport acquatico."}', 1),
    (1302, 'uinti', 'noun', NULL, NULL, 2),
    (1303, 'swimming', 'noun', NULL, NULL, 3),
    (1304, 'fotografia', 'noun', NULL, '{"standard_translation_EN": "photography", "standard_translation_IT": "fotografia", "note_culturale": "Arte di catturare immagini con la luce."}', 1),
    (1305, 'valokuvaus', 'noun', NULL, NULL, 2),
    (1306, 'photography', 'noun', NULL, NULL, 3),
    (1307, 'arte', 'noun', NULL, '{"standard_translation_EN": "art", "standard_translation_IT": "arte", "note_culturale": "Espressione estetica della creatività umana."}', 1),
    (1308, 'taide', 'noun', NULL, NULL, 2),
    (1309, 'art', 'noun', NULL, NULL, 3),
    (1310, 'danza', 'noun', NULL, '{"standard_translation_EN": "dance", "standard_translation_IT": "danza", "note_culturale": "Arte del movimento del corpo a ritmo di musica."}', 1),
    (1311, 'tanssi', 'noun', NULL, NULL, 2),
    (1312, 'dance', 'noun', NULL, NULL, 3),
    (1313, 'viaggio', 'noun', NULL, '{"standard_translation_EN": "travel", "standard_translation_IT": "viaggio", "note_culturale": "Spostamento da un luogo a un altro."}', 1),
    (1314, 'matka', 'noun', NULL, NULL, 2),
    (1315, 'travel', 'noun', NULL, NULL, 3),
    (1316, 'giardinaggio', 'noun', NULL, '{"standard_translation_EN": "gardening", "standard_translation_IT": "giardinaggio", "note_culturale": "Coltivazione di piante a scopo ornamentale o alimentare."}', 1),
    (1317, 'puutarhanhoito', 'noun', NULL, NULL, 2),
    (1318, 'gardening', 'noun', NULL, NULL, 3),
    (1319, 'ruoanlaitto', 'noun', NULL, NULL, 2),
    (1320, 'cooking', 'noun', NULL, NULL, 3),
    (1321, 'scultura', 'noun', NULL, '{"standard_translation_EN": "sculpture", "standard_translation_IT": "scultura", "note_culturale": "Arte di creare forme tridimensionali."}', 1),
    (1322, 'veistos', 'noun', NULL, NULL, 2),
    (1323, 'sculpture', 'noun', NULL, NULL, 3),
    (1324, 'collezionismo', 'noun', NULL, '{"standard_translation_EN": "collecting", "standard_translation_IT": "collezionismo", "note_culturale": "Attività di raccogliere oggetti di interesse."}', 1),
    (1325, 'keräily', 'noun', NULL, NULL, 2),
    (1326, 'collecting', 'noun', NULL, NULL, 3),
    (1327, 'videogiochi', 'noun', NULL, '{"standard_translation_EN": "video games", "standard_translation_IT": "videogiochi", "note_culturale": "Giochi interattivi su dispositivi elettronici."}', 1),
    (1328, 'videopelit', 'noun', NULL, NULL, 2),
    (1329, 'video games', 'noun', NULL, NULL, 3),
    (1330, 'passeggiata', 'noun', NULL, '{"standard_translation_EN": "walk", "standard_translation_IT": "passeggiata", "note_culturale": "Attività rilassante all''aria aperta."}', 1),
    (1331, 'kävely', 'noun', NULL, NULL, 2),
    (1332, 'walk', 'noun', NULL, NULL, 3),
    (1333, 'ascoltare musica', 'verb', NULL, '{"standard_translation_EN": "listen to music", "standard_translation_IT": "ascoltare musica", "note_culturale": "Attività rilassante e piacevole."}', 1),
    (1334, 'kuunnella musiikkia', 'verb', NULL, NULL, 2),
    (1335, 'listen to music', 'verb', NULL, NULL, 3),
    (1336, 'pianoforte', 'noun', NULL, '{"standard_translation_EN": "piano", "standard_translation_IT": "pianoforte", "note_culturale": "Uno strumento musicale a tastiera."}', 1),
    (1337, 'piano', 'noun', NULL, NULL, 2),
    (1338, 'piano', 'noun', NULL, NULL, 3),
    (1339, 'serie TV', 'noun', NULL, '{"standard_translation_EN": "TV series", "standard_translation_IT": "serie TV", "note_culturale": "Un racconto a puntate trasmesso in TV."}', 1),
    (1340, 'televisiosarja', 'noun', NULL, NULL, 2),
    (1341, 'TV series', 'noun', NULL, NULL, 3),
    (1342, 'tennis', 'noun', NULL, '{"standard_translation_EN": "tennis", "standard_translation_IT": "tennis", "note_culturale": "Uno sport praticato con racchetta e pallina."}', 1),
    (1343, 'tennis', 'noun', NULL, NULL, 2),
    (1344, 'tennis', 'noun', NULL, NULL, 3),
    (1345, 'documentario', 'noun', NULL, '{"standard_translation_EN": "documentary", "standard_translation_IT": "documentario", "note_culturale": "Un film che presenta fatti reali."}', 1),
    (1346, 'dokumentti', 'noun', NULL, NULL, 2),
    (1347, 'documentary', 'noun', NULL, NULL, 3),
    (1348, 'poesia', 'noun', NULL, '{"standard_translation_EN": "poetry", "standard_translation_IT": "poesia", "note_culturale": "Un''espressione artistica attraverso le parole."}', 1),
    (1349, 'runous', 'noun', NULL, NULL, 2),
    (1350, 'poetry', 'noun', NULL, NULL, 3),
    (1351, 'arrampicata', 'noun', NULL, '{"standard_translation_EN": "climbing", "standard_translation_IT": "arrampicata", "note_culturale": "Uno sport che consiste nello scalare pareti rocciose."}', 1),
    (1352, 'kiipeily', 'noun', NULL, NULL, 2),
    (1353, 'climbing', 'noun', NULL, NULL, 3),
    (1354, 'band', 'noun', NULL, '{"standard_translation_EN": "band", "standard_translation_IT": "band", "note_culturale": "Un gruppo di musicisti che suonano insieme."}', 1),
    (1355, 'bändi', 'noun', NULL, NULL, 2),
    (1356, 'band', 'noun', NULL, NULL, 3),
    (1357, 'thriller', 'noun', NULL, '{"standard_translation_EN": "thriller", "standard_translation_IT": "thriller", "note_culturale": "Un film che tiene lo spettatore con il fiato sospeso."}', 1),
    (1358, 'trilleri', 'noun', NULL, NULL, 2),
    (1359, 'thriller', 'noun', NULL, NULL, 3),
    (1360, 'saggio', 'noun', NULL, '{"standard_translation_EN": "essay", "standard_translation_IT": "saggio", "note_culturale": "Un testo che espone un''opinione su un argomento."}', 1),
    (1361, 'esse', 'noun', NULL, NULL, 2),
    (1362, 'dj', 'noun', NULL, '{"standard_translation_EN": "DJ", "standard_translation_IT": "dj", "note_culturale": "Una persona che seleziona e mixa musica."}', 1),
    (1363, 'DJ', 'noun', NULL, NULL, 2),
    (1364, 'DJ', 'noun', NULL, NULL, 3),
    (1365, 'fantasy', 'noun', NULL, '{"standard_translation_EN": "fantasy", "standard_translation_IT": "fantasy", "note_culturale": "Un genere che include elementi magici e immaginari."}', 1),
    (1366, 'fantasia', 'noun', NULL, NULL, 2),
    (1367, 'fantasy', 'noun', NULL, NULL, 3),
    (1368, 'biografia', 'noun', NULL, '{"standard_translation_EN": "biography", "standard_translation_IT": "biografia", "note_culturale": "La storia della vita di una persona."}', 1),
    (1369, 'elämäkerta', 'noun', NULL, NULL, 2),
    (1370, 'biography', 'noun', NULL, NULL, 3),
    (1371, 'commedia', 'noun', NULL, '{"standard_translation_EN": "comedy", "standard_translation_IT": "commedia", "note_culturale": "Genere cinematografico umoristico."}', 1),
    (1372, 'komedia', 'noun', NULL, NULL, 2),
    (1373, 'comedy', 'noun', NULL, NULL, 3),
    (1374, 'jazz', 'noun', NULL, '{"standard_translation_EN": "jazz", "standard_translation_IT": "jazz", "note_culturale": "Genere musicale caratterizzato dall''improvvisazione."}', 1),
    (1375, 'jazz', 'noun', NULL, NULL, 2),
    (1376, 'jazz', 'noun', NULL, NULL, 3),
    (1377, 'animazione', 'noun', NULL, '{"standard_translation_EN": "animation", "standard_translation_IT": "animazione", "note_culturale": "Tecnica cinematografica che crea l''illusione del movimento."}', 1),
    (1378, 'animaatio', 'noun', NULL, NULL, 2),
    (1379, 'animation', 'noun', NULL, NULL, 3),
    (1380, 'karaoke', 'noun', NULL, '{"standard_translation_EN": "karaoke", "standard_translation_IT": "karaoke", "note_culturale": "Divertimento canoro su basi musicali preregistrate."}', 1),
    (1381, 'karaoke', 'noun', NULL, NULL, 2),
    (1382, 'karaoke', 'noun', NULL, NULL, 3),
    (1383, 'fumetto', 'noun', NULL, '{"standard_translation_EN": "comic book", "standard_translation_IT": "fumetto", "note_culturale": "Storia narrata attraverso immagini e testo."}', 1),
    (1384, 'sarjakuva', 'noun', NULL, NULL, 2),
    (1385, 'comic book', 'noun', NULL, NULL, 3),
    (1386, 'nuvola', 'noun', NULL, '{"standard_translation_EN": "cloud", "standard_translation_IT": "nuvola", "note_culturale": "Le nuvole possono portare pioggia o neve."}', 1),
    (1387, 'neve', 'noun', NULL, '{"standard_translation_EN": "snow", "standard_translation_IT": "neve", "note_culturale": "La neve cade in inverno."}', 1),
    (1388, 'lumi', 'noun', NULL, NULL, 2),
    (1389, 'snow', 'noun', NULL, NULL, 3),
    (1390, 'mese', 'noun', NULL, '{"standard_translation_EN": "month", "standard_translation_IT": "mese", "note_culturale": "Ci sono dodici mesi in un anno."}', 1),
    (1391, 'kuukausi', 'noun', NULL, NULL, 2),
    (1392, 'month', 'noun', NULL, NULL, 3),
    (1393, 'anno', 'noun', NULL, '{"standard_translation_EN": "year", "standard_translation_IT": "anno", "note_culturale": "Un anno ha 365 giorni (o 366 negli anni bisestili)."}', 1),
    (1394, 'vuosi', 'noun', NULL, NULL, 2),
    (1395, 'year', 'noun', NULL, NULL, 3),
    (1396, 'settimana', 'noun', NULL, '{"standard_translation_EN": "week", "standard_translation_IT": "settimana", "note_culturale": "La settimana ha sette giorni, da lunedì a domenica."}', 1),
    (1397, 'viikko', 'noun', NULL, NULL, 2),
    (1398, 'week', 'noun', NULL, NULL, 3),
    (1399, 'giorno', 'noun', NULL, '{"standard_translation_EN": "day", "standard_translation_IT": "giorno", "note_culturale": "Il giorno inizia con l''alba e finisce con il tramonto."}', 1),
    (1400, 'päivä', 'noun', NULL, NULL, 2),
    (1401, 'day', 'noun', NULL, NULL, 3),
    (1402, 'ora', 'noun', NULL, '{"standard_translation_EN": "hour", "standard_translation_IT": "ora", "note_culturale": "Un giorno ha 24 ore."}', 1),
    (1403, 'tunti', 'noun', NULL, NULL, 2),
    (1404, 'hour', 'noun', NULL, NULL, 3),
    (1405, 'appuntamento', 'noun', NULL, '{"standard_translation_EN": "appointment", "standard_translation_IT": "appuntamento", "note_culturale": "È importante arrivare in orario agli appuntamenti."}', 1),
    (1406, 'tapaaminen', 'noun', NULL, NULL, 2),
    (1407, 'appointment', 'noun', NULL, NULL, 3),
    (1408, 'calendario', 'noun', NULL, '{"standard_translation_EN": "calendar", "standard_translation_IT": "calendario", "note_culturale": "Il calendario aiuta a tenere traccia degli appuntamenti."}', 1),
    (1409, 'kalenteri', 'noun', NULL, NULL, 2),
    (1410, 'calendar', 'noun', NULL, NULL, 3),
    (1411, 'previsioni', 'noun', NULL, '{"standard_translation_EN": "forecast", "standard_translation_IT": "previsioni", "note_culturale": "Le previsioni del tempo ci dicono che tempo farà."}', 1),
    (1412, 'ennuste', 'noun', NULL, NULL, 2),
    (1413, 'forecast', 'noun', NULL, NULL, 3),
    (1414, 'temperatura', 'noun', NULL, '{"standard_translation_EN": "temperature", "standard_translation_IT": "temperatura", "note_culturale": "La temperatura si misura in gradi Celsius o Fahrenheit."}', 1),
    (1415, 'lämpötila', 'noun', NULL, NULL, 2),
    (1416, 'temperature', 'noun', NULL, NULL, 3),
    (1417, 'stagione', 'noun', NULL, '{"standard_translation_EN": "season", "standard_translation_IT": "stagione", "note_culturale": "Le stagioni sono primavera, estate, autunno e inverno."}', 1),
    (1418, 'vuodenaika', 'noun', NULL, NULL, 2),
    (1419, 'season', 'noun', NULL, NULL, 3),
    (1420, 'nebbia', 'noun', NULL, '{"standard_translation_EN": "fog", "standard_translation_IT": "nebbia", "note_culturale": "La nebbia riduce la visibilità."}', 1),
    (1421, 'sumu', 'noun', NULL, NULL, 2),
    (1422, 'fog', 'noun', NULL, NULL, 3),
    (1423, 'umidità', 'noun', NULL, '{"standard_translation_EN": "humidity", "standard_translation_IT": "umidità", "note_culturale": "L''umidità rende l''aria appiccicosa."}', 1),
    (1424, 'kosteus', 'noun', NULL, NULL, 2),
    (1425, 'humidity', 'noun', NULL, NULL, 3),
    (1426, 'fulmine', 'noun', NULL, '{"standard_translation_EN": "lightning", "standard_translation_IT": "fulmine", "note_culturale": "Il fulmine è una scarica elettrica durante un temporale."}', 1),
    (1427, 'salama', 'noun', NULL, NULL, 2),
    (1428, 'lightning', 'noun', NULL, NULL, 3),
    (1429, 'programmare', 'verb', NULL, '{"standard_translation_EN": "schedule", "standard_translation_IT": "programmare", "note_culturale": "Devo programmare una riunione."}', 1),
    (1430, 'ohjelmoida', 'verb', NULL, NULL, 2),
    (1431, 'posticipare', 'verb', NULL, '{"standard_translation_EN": "postpone", "standard_translation_IT": "posticipare", "note_culturale": "Dobbiamo posticipare l''appuntamento a causa del maltempo."}', 1),
    (1432, 'siirtää', 'verb', NULL, NULL, 2),
    (1433, 'postpone', 'verb', NULL, NULL, 3),
    (1434, 'piovoso', 'adjective', NULL, '{"standard_translation_EN": "rainy", "standard_translation_IT": "piovoso", "note_culturale": "Un giorno piovoso è perfetto per stare in casa."}', 1),
    (1435, 'sateinen', 'adjective', NULL, NULL, 2),
    (1436, 'rainy', 'adjective', NULL, NULL, 3),
    (1437, 'soleggiato', 'adjective', NULL, '{"standard_translation_EN": "sunny", "standard_translation_IT": "soleggiato", "note_culturale": "Una giornata soleggiata è ideale per un picnic."}', 1),
    (1438, 'aurinkoinen', 'adjective', NULL, NULL, 2),
    (1439, 'sunny', 'adjective', NULL, NULL, 3),
    (1440, 'nuvoloso', 'adjective', NULL, '{"standard_translation_EN": "cloudy", "standard_translation_IT": "nuvoloso", "note_culturale": "Un cielo nuvoloso può presagire pioggia."}', 1),
    (1441, 'pilvinen', 'adjective', NULL, NULL, 2),
    (1442, 'cloudy', 'adjective', NULL, NULL, 3),
    (1443, 'rimandare', 'verb', NULL, '{"standard_translation_EN": "postpone", "standard_translation_IT": "rimandare", "note_culturale": "A volte è necessario rimandare un appuntamento."}', 1),
    (1444, 'prevedere', 'verb', NULL, '{"standard_translation_EN": "predict", "standard_translation_IT": "prevedere", "note_culturale": "È difficile prevedere il futuro con certezza."}', 1),
    (1445, 'ennustaa', 'verb', NULL, NULL, 2),
    (1446, 'predict', 'verb', NULL, NULL, 3),
    (1447, 'Autobus', 'noun', NULL, '{"standard_translation_EN": "Bus", "standard_translation_IT": "Autobus", "note_culturale": "Mezzo di trasporto urbano ed extraurbano."}', 1),
    (1448, 'Bussi', 'noun', NULL, NULL, 2),
    (1449, 'Bus', 'noun', NULL, NULL, 3),
    (1450, 'Treno', 'noun', NULL, '{"standard_translation_EN": "Train", "standard_translation_IT": "Treno", "note_culturale": "Mezzo di trasporto su rotaie."}', 1),
    (1451, 'Juna', 'noun', NULL, NULL, 2),
    (1452, 'Train', 'noun', NULL, NULL, 3),
    (1453, 'Metro', 'noun', NULL, '{"standard_translation_EN": "Subway", "standard_translation_IT": "Metro", "note_culturale": "Mezzo di trasporto sotterraneo."}', 1),
    (1454, 'Metro', 'noun', NULL, NULL, 2),
    (1455, 'Subway', 'noun', NULL, NULL, 3),
    (1456, 'Bicicletta', 'noun', NULL, '{"standard_translation_EN": "Bicycle", "standard_translation_IT": "Bicicletta", "note_culturale": "Mezzo di trasporto a pedali."}', 1),
    (1457, 'Polkupyörä', 'noun', NULL, NULL, 2),
    (1458, 'Bicycle', 'noun', NULL, NULL, 3),
    (1459, 'Biglietto', 'noun', NULL, '{"standard_translation_EN": "Ticket", "standard_translation_IT": "Biglietto", "note_culturale": "Documento per viaggiare."}', 1),
    (1460, 'Lippu', 'noun', NULL, NULL, 2),
    (1461, 'Ticket', 'noun', NULL, NULL, 3),
    (1462, 'Fermata', 'noun', NULL, '{"standard_translation_EN": "Bus Stop", "standard_translation_IT": "Fermata", "note_culturale": "Luogo dove l''autobus si ferma."}', 1),
    (1463, 'Pysäkki', 'noun', NULL, NULL, 2),
    (1464, 'Bus Stop', 'noun', NULL, NULL, 3),
    (1465, 'Abbonamento', 'noun', NULL, '{"standard_translation_EN": "Season ticket", "standard_translation_IT": "Abbonamento", "note_culturale": "Biglietto valido per un periodo."}', 1),
    (1466, 'Kausilippu', 'noun', NULL, NULL, 2),
    (1467, 'Season ticket', 'noun', NULL, NULL, 3),
    (1468, 'Binario', 'noun', NULL, '{"standard_translation_EN": "Platform", "standard_translation_IT": "Binario", "note_culturale": "Punto di accesso al treno."}', 1),
    (1469, 'Laituri', 'noun', NULL, NULL, 2),
    (1470, 'Platform', 'noun', NULL, NULL, 3),
    (1471, 'Convalidare', 'verb', NULL, '{"standard_translation_EN": "Validate", "standard_translation_IT": "Convalidare", "note_culturale": "Azione per rendere valido il biglietto."}', 1),
    (1472, 'Leimata', 'verb', NULL, NULL, 2),
    (1473, 'Validate', 'verb', NULL, NULL, 3),
    (1474, 'Ritardo', 'noun', NULL, '{"standard_translation_EN": "Delay", "standard_translation_IT": "Ritardo", "note_culturale": "Arrivo in orario successivo a quello previsto."}', 1),
    (1475, 'Myöhästyminen', 'noun', NULL, NULL, 2),
    (1476, 'Delay', 'noun', NULL, NULL, 3),
    (1477, 'Sciopero', 'noun', NULL, '{"standard_translation_EN": "Strike", "standard_translation_IT": "Sciopero", "note_culturale": "Interruzione del servizio per protesta."}', 1),
    (1478, 'Lakko', 'noun', NULL, NULL, 2),
    (1479, 'Strike', 'noun', NULL, NULL, 3),
    (1480, 'Bagaglio', 'noun', NULL, '{"standard_translation_EN": "Luggage", "standard_translation_IT": "Bagaglio", "note_culturale": "Oggetti personali trasportati durante un viaggio."}', 1),
    (1481, 'Matkatavarat', 'noun', NULL, NULL, 2),
    (1482, 'Luggage', 'noun', NULL, NULL, 3),
    (1483, 'Controllore', 'noun', NULL, '{"standard_translation_EN": "Ticket inspector", "standard_translation_IT": "Controllore", "note_culturale": "Persona che controlla i biglietti."}', 1),
    (1484, 'Konduktööri', 'noun', NULL, NULL, 2),
    (1485, 'Ticket inspector', 'noun', NULL, NULL, 3),
    (1486, 'Prenotare', 'verb', NULL, '{"standard_translation_EN": "Book", "standard_translation_IT": "Prenotare", "note_culturale": "Assicurarsi un posto su un mezzo di trasporto."}', 1),
    (1487, 'Varata', 'verb', NULL, NULL, 2),
    (1488, 'Taxi', 'noun', NULL, '{"standard_translation_EN": "Taxi", "standard_translation_IT": "Taxi", "note_culturale": "Auto a noleggio con conducente."}', 1),
    (1489, 'Taksi', 'noun', NULL, NULL, 2),
    (1490, 'Taxi', 'noun', NULL, NULL, 3),
    (1491, 'Autista', 'noun', NULL, '{"standard_translation_EN": "Driver", "standard_translation_IT": "Autista", "note_culturale": "Persona che guida un veicolo."}', 1),
    (1492, 'Kuljettaja', 'noun', NULL, NULL, 2),
    (1493, 'Driver', 'noun', NULL, NULL, 3),
    (1494, 'Traffico', 'noun', NULL, '{"standard_translation_EN": "Traffic", "standard_translation_IT": "Traffico", "note_culturale": "Congestione di veicoli."}', 1),
    (1495, 'Liikenne', 'noun', NULL, NULL, 2),
    (1496, 'Traffic', 'noun', NULL, NULL, 3),
    (1497, 'Itinerario', 'noun', NULL, '{"standard_translation_EN": "Route", "standard_translation_IT": "Itinerario", "note_culturale": "Percorso di un viaggio."}', 1),
    (1498, 'Reitti', 'noun', NULL, NULL, 2),
    (1499, 'Route', 'noun', NULL, NULL, 3),
    (1500, 'Vagone', 'noun', NULL, '{"standard_translation_EN": "Carriage", "standard_translation_IT": "Vagone", "note_culturale": "Parte del treno dove siedono i passeggeri."}', 1),
    (1501, 'Vaunu', 'noun', NULL, NULL, 2),
    (1502, 'Carriage', 'noun', NULL, NULL, 3),
    (1503, 'Capolinea', 'noun', NULL, '{"standard_translation_EN": "Terminus", "standard_translation_IT": "Capolinea", "note_culturale": "Ultima fermata di un mezzo di trasporto."}', 1),
    (1504, 'Päätepysäkki', 'noun', NULL, NULL, 2),
    (1505, 'Terminus', 'noun', NULL, NULL, 3),
    (1506, 'Coincidenza', 'noun', NULL, '{"standard_translation_EN": "Connection", "standard_translation_IT": "Coincidenza", "note_culturale": "Cambio di mezzo di trasporto per proseguire il viaggio."}', 1),
    (1507, 'Jatköyhteys', 'noun', NULL, NULL, 2),
    (1508, 'Connection', 'noun', NULL, NULL, 3),
    (1509, 'Pedaggio', 'noun', NULL, '{"standard_translation_EN": "Toll", "standard_translation_IT": "Pedaggio", "note_culturale": "Costo per l''utilizzo di una strada o autostrada."}', 1),
    (1510, 'Tiemaksu', 'noun', NULL, NULL, 2),
    (1511, 'Toll', 'noun', NULL, NULL, 3),
    (1512, 'Circonvallazione', 'noun', NULL, '{"standard_translation_EN": "Bypass", "standard_translation_IT": "Circonvallazione", "note_culturale": "Strada che aggira un centro abitato."}', 1),
    (1513, 'Ohikulkutie', 'noun', NULL, NULL, 2),
    (1514, 'Bypass', 'noun', NULL, NULL, 3),
    (1515, 'Pysäköinti', 'noun', NULL, NULL, 2),
    (1516, 'Parking', 'noun', NULL, NULL, 3),
    (1517, 'Corsia preferenziale', 'noun', NULL, '{"standard_translation_EN": "Bus lane", "standard_translation_IT": "Corsia preferenziale", "note_culturale": "Corsia riservata agli autobus."}', 1),
    (1518, 'Bussikaista', 'noun', NULL, NULL, 2),
    (1519, 'Bus lane', 'noun', NULL, NULL, 3),
    (1520, 'Linea', 'noun', NULL, '{"standard_translation_EN": "Line", "standard_translation_IT": "Linea", "note_culturale": "Indica il percorso specifico di un mezzo pubblico."}', 1),
    (1521, 'Linja', 'noun', NULL, NULL, 2),
    (1522, 'Line', 'noun', NULL, NULL, 3),
    (1523, 'Controllo', 'noun', NULL, '{"standard_translation_EN": "Inspection", "standard_translation_IT": "Controllo", "note_culturale": "Verifica dei biglietti."}', 1),
    (1524, 'Tarkastus', 'noun', NULL, NULL, 2),
    (1525, 'Inspection', 'noun', NULL, NULL, 3),
    (1526, 'Trip', 'noun', NULL, NULL, 3),
    (1527, 'Hotel', 'noun', NULL, '{"standard_translation_EN": "Hotel", "standard_translation_IT": "Hotel", "note_culturale": "Struttura ricettiva per turisti."}', 1),
    (1528, 'Hotelli', 'noun', NULL, NULL, 2),
    (1529, 'Hotel', 'noun', NULL, NULL, 3),
    (1530, 'Turismo', 'noun', NULL, '{"standard_translation_EN": "Tourism", "standard_translation_IT": "Turismo", "note_culturale": "Attività di viaggio per piacere."}', 1),
    (1531, 'Turismi', 'noun', NULL, NULL, 2),
    (1532, 'Tourism', 'noun', NULL, NULL, 3),
    (1533, 'Mappa', 'noun', NULL, '{"standard_translation_EN": "Map", "standard_translation_IT": "Mappa", "note_culturale": "Rappresentazione grafica di un luogo."}', 1),
    (1534, 'Kartta', 'noun', NULL, NULL, 2),
    (1535, 'Map', 'noun', NULL, NULL, 3),
    (1536, 'Valigia', 'noun', NULL, '{"standard_translation_EN": "Suitcase", "standard_translation_IT": "Valigia", "note_culturale": "Contenitore per trasportare effetti personali."}', 1),
    (1537, 'Matkalaukku', 'noun', NULL, NULL, 2),
    (1538, 'Suitcase', 'noun', NULL, NULL, 3),
    (1539, 'Vacanze', 'noun', NULL, '{"standard_translation_EN": "Vacation", "standard_translation_IT": "Vacanze", "note_culturale": "Periodo di riposo dal lavoro."}', 1),
    (1540, 'Loma', 'noun', NULL, NULL, 2),
    (1541, 'Vacation', 'noun', NULL, NULL, 3),
    (1542, 'Museo', 'noun', NULL, '{"standard_translation_EN": "Museum", "standard_translation_IT": "Museo", "note_culturale": "Luogo di esposizione di opere d''arte."}', 1),
    (1543, 'Museo', 'noun', NULL, NULL, 2),
    (1544, 'Museum', 'noun', NULL, NULL, 3),
    (1545, 'Guida turistica', 'noun', NULL, '{"standard_translation_EN": "Tour guide", "standard_translation_IT": "Guida turistica", "note_culturale": "Persona che accompagna i turisti."}', 1),
    (1546, 'Opas', 'noun', NULL, NULL, 2),
    (1547, 'Tour guide', 'noun', NULL, NULL, 3),
    (1548, 'Spiaggia', 'noun', NULL, '{"standard_translation_EN": "Beach", "standard_translation_IT": "Spiaggia", "note_culturale": "Area costiera con sabbia o ciottoli."}', 1),
    (1549, 'Ranta', 'noun', NULL, NULL, 2),
    (1550, 'Beach', 'noun', NULL, NULL, 3),
    (1551, 'Bagaglio a mano', 'noun', NULL, '{"standard_translation_EN": "Carry-on luggage", "standard_translation_IT": "Bagaglio a mano", "note_culturale": "Bagaglio che si porta con sé in aereo."}', 1),
    (1552, 'Käsmatkatavarat', 'noun', NULL, NULL, 2),
    (1553, 'Carry-on luggage', 'noun', NULL, NULL, 3),
    (1554, 'Prenotazione', 'noun', NULL, '{"standard_translation_EN": "Reservation", "standard_translation_IT": "Prenotazione", "note_culturale": "Azione di riservare un servizio."}', 1),
    (1555, 'Varaus', 'noun', NULL, NULL, 2),
    (1556, 'Reservation', 'noun', NULL, NULL, 3),
    (1557, 'Reittisuunnitelma', 'noun', NULL, NULL, 2),
    (1558, 'Itinerary', 'noun', NULL, NULL, 3),
    (1559, 'Alloggio', 'noun', NULL, '{"standard_translation_EN": "Accommodation", "standard_translation_IT": "Alloggio", "note_culturale": "Luogo dove si pernotta durante un viaggio."}', 1),
    (1560, 'Majoitus', 'noun', NULL, NULL, 2),
    (1561, 'Accommodation', 'noun', NULL, NULL, 3),
    (1562, 'Escursione', 'noun', NULL, '{"standard_translation_EN": "Excursion", "standard_translation_IT": "Escursione", "note_culturale": "Breve viaggio per svago."}', 1),
    (1563, 'Retki', 'noun', NULL, NULL, 2),
    (1564, 'Excursion', 'noun', NULL, NULL, 3),
    (1565, 'Volo diretto', 'noun', NULL, '{"standard_translation_EN": "Direct flight", "standard_translation_IT": "Volo diretto", "note_culturale": "Volo senza cambi di aereo."}', 1),
    (1566, 'Suora lento', 'noun', NULL, NULL, 2),
    (1567, 'Direct flight', 'noun', NULL, NULL, 3),
    (1568, 'Cambio valuta', 'noun', NULL, '{"standard_translation_EN": "Currency exchange", "standard_translation_IT": "Cambio valuta", "note_culturale": "Servizio per convertire denaro."}', 1),
    (1569, 'Valuutanvaihto', 'noun', NULL, NULL, 2),
    (1570, 'Currency exchange', 'noun', NULL, NULL, 3),
    (1571, 'Volo', 'noun', NULL, '{"standard_translation_EN": "Flight", "standard_translation_IT": "Volo", "note_culturale": "Spostamento tramite aeroplano."}', 1),
    (1572, 'Lento', 'noun', NULL, NULL, 2),
    (1573, 'Flight', 'noun', NULL, NULL, 3),
    (1574, 'Vacanza', 'noun', NULL, '{"standard_translation_EN": "Vacation", "standard_translation_IT": "Vacanza", "note_culturale": "Periodo di riposo dal lavoro o studio."}', 1),
    (1575, 'Passaporto', 'noun', NULL, '{"standard_translation_EN": "Passport", "standard_translation_IT": "Passaporto", "note_culturale": "Documento per viaggiare all''estero."}', 1),
    (1576, 'Passi', 'noun', NULL, NULL, 2),
    (1577, 'Passport', 'noun', NULL, NULL, 3),
    (1578, 'Dogana', 'noun', NULL, '{"standard_translation_EN": "Customs", "standard_translation_IT": "Dogana", "note_culturale": "Ufficio di controllo delle merci."}', 1),
    (1579, 'Tulli', 'noun', NULL, NULL, 2),
    (1580, 'Customs', 'noun', NULL, NULL, 3),
    (1581, 'Area di servizio', 'noun', NULL, '{"standard_translation_EN": "Service area", "standard_translation_IT": "Area di servizio", "note_culturale": "Luogo di sosta lungo le autostrade."}', 1),
    (1582, 'Huoltoasema', 'noun', NULL, NULL, 2),
    (1583, 'Service area', 'noun', NULL, NULL, 3),
    (1584, 'Souvenir', 'noun', NULL, '{"standard_translation_EN": "Souvenir", "standard_translation_IT": "Souvenir", "note_culturale": "Oggetto acquistato come ricordo di un viaggio."}', 1),
    (1585, 'Matkamuisto', 'noun', NULL, NULL, 2),
    (1586, 'Souvenir', 'noun', NULL, NULL, 3),
    (1587, 'Destinazione', 'noun', NULL, '{"standard_translation_EN": "Destination", "standard_translation_IT": "Destinazione", "note_culturale": "Luogo dove si intende arrivare."}', 1),
    (1588, 'Kohde', 'noun', NULL, NULL, 2),
    (1589, 'Destination', 'noun', NULL, NULL, 3),
    (1590, 'Oleskelu', 'noun', NULL, NULL, 2),
    (1591, 'Stay', 'noun', NULL, NULL, 3),
    (1592, 'Attrazione', 'noun', NULL, '{"standard_translation_EN": "Attraction", "standard_translation_IT": "Attrazione", "note_culturale": "Qualcosa che attrae i turisti."}', 1),
    (1593, 'Nähtävyys', 'noun', NULL, NULL, 2),
    (1594, 'Attraction', 'noun', NULL, NULL, 3),
    (1595, 'Rimborso', 'noun', NULL, '{"standard_translation_EN": "Refund", "standard_translation_IT": "Rimborso", "note_culturale": "Restituzione di denaro."}', 1),
    (1596, 'Korvaus', 'noun', NULL, NULL, 2),
    (1597, 'Refund', 'noun', NULL, NULL, 3),
    (1598, 'Crociera', 'noun', NULL, '{"standard_translation_EN": "Cruise", "standard_translation_IT": "Crociera", "note_culturale": "Viaggio per mare a scopo turistico."}', 1),
    (1599, 'Risteily', 'noun', NULL, NULL, 2),
    (1600, 'Cruise', 'noun', NULL, NULL, 3),
    (1601, 'Visto', 'noun', NULL, '{"standard_translation_EN": "Visa", "standard_translation_IT": "Visto", "note_culturale": "Documento per entrare in un paese."}', 1),
    (1602, 'Viisumi', 'noun', NULL, NULL, 2),
    (1603, 'Visa', 'noun', NULL, NULL, 3)
ON CONFLICT DO NOTHING;
SELECT setval('lemma_lemma_id_seq', 1603);

INSERT INTO morpho_form (surface_form, grammar_json, lemma_id) VALUES
    ('koe', NULL, 1020),
    ('test', NULL, 1021),
    ('corso', NULL, 1022),
    ('oppitunti', NULL, 1023),
    ('class', NULL, 1024),
    ('refettorio', NULL, 1025),
    ('cafeteria', NULL, 1027),
    ('scambio', NULL, 1028),
    ('culturale', NULL, 1028),
    ('opiskelijavaihto', NULL, 1029),
    ('exchange', NULL, 1030),
    ('program', NULL, 1030),
    ('docente', NULL, 1031),
    ('opettaja', NULL, 1032),
    ('teacher', NULL, 1033),
    ('elaborato', NULL, 1034),
    ('tutkielma', NULL, 1035),
    ('dissertation', NULL, 1036),
    ('note', NULL, 1037),
    ('registrarsi', NULL, 1040),
    ('rekisteröityä', NULL, 1041),
    ('to', NULL, 1042),
    ('enroll', NULL, 1042),
    ('to', NULL, 1042),
    ('register', NULL, 1042),
    ('semestre', NULL, 1043),
    ('term', NULL, 1045),
    ('lezioni', NULL, 1046),
    ('private', NULL, 1046),
    ('private', NULL, 1048),
    ('lessons', NULL, 1048),
    ('fuori', NULL, 1049),
    ('corso', NULL, 1049),
    ('in', NULL, 1049),
    ('ritardo', NULL, 1049),
    ('jäljessä', NULL, 1050),
    ('opinnoista', NULL, 1050),
    ('overdue', NULL, 1051),
    ('(studies)', NULL, 1051),
    ('behind', NULL, 1051),
    ('schedule', NULL, 1051),
    ('novellino', NULL, 1052),
    ('fresher', NULL, 1054),
    ('diploma', NULL, 1055),
    ('borsa', NULL, 1058),
    ('di', NULL, 1058),
    ('studio', NULL, 1058),
    ('sussidio', NULL, 1058),
    ('stipendi', NULL, 1059),
    ('grant', NULL, 1060),
    ('classe', NULL, 1061),
    ('esercizio', NULL, 1064),
    ('task', NULL, 1065),
    ('immatricolazione', NULL, 1066),
    ('enrollment', NULL, 1068),
    ('sessione', NULL, 1069),
    ('di', NULL, 1069),
    ('laurea', NULL, 1069),
    ('cerimonia', NULL, 1069),
    ('di', NULL, 1069),
    ('laurea', NULL, 1069),
    ('graduation', NULL, 1071),
    ('ceremony', NULL, 1071),
    ('commencement', NULL, 1071),
    ('tassa', NULL, 1072),
    ('universitaria', NULL, 1072),
    ('retta', NULL, 1072),
    ('tuition', NULL, 1074),
    ('fee', NULL, 1074),
    ('esame', NULL, 1075),
    ('di', NULL, 1075),
    ('ammissione', NULL, 1075),
    ('test', NULL, 1075),
    ('di', NULL, 1075),
    ('ingresso', NULL, 1075),
    ('entrance', NULL, 1077),
    ('exam', NULL, 1077),
    ('admission', NULL, 1077),
    ('test', NULL, 1077),
    ('stage', NULL, 1078),
    ('traineeship', NULL, 1080),
    ('area', NULL, 1081),
    ('studio', NULL, 1081),
    ('zona', NULL, 1081),
    ('studio', NULL, 1081),
    ('study', NULL, 1083),
    ('area', NULL, 1083),
    ('sessione', NULL, 1084),
    ('d''esame', NULL, 1084),
    ('periodo', NULL, 1084),
    ('d''esame', NULL, 1084),
    ('exam', NULL, 1086),
    ('period', NULL, 1086),
    ('libri', NULL, 1087),
    ('di', NULL, 1087),
    ('testo', NULL, 1087),
    ('manuali', NULL, 1087),
    ('coursebooks', NULL, 1089),
    ('registrare', NULL, 1090),
    ('il', NULL, 1090),
    ('voto', NULL, 1090),
    ('kirjata', NULL, 1091),
    ('arvosana', NULL, 1091),
    ('to', NULL, 1092),
    ('record', NULL, 1092),
    ('a', NULL, 1092),
    ('grade', NULL, 1092),
    ('to', NULL, 1092),
    ('register', NULL, 1092),
    ('a', NULL, 1092),
    ('mark', NULL, 1092),
    ('sessione', NULL, 1093),
    ('straordinaria', NULL, 1093),
    ('appello', NULL, 1093),
    ('straordinario', NULL, 1093),
    ('resit', NULL, 1095),
    ('exam', NULL, 1095),
    ('retake', NULL, 1095),
    ('exam', NULL, 1095),
    ('addetto', NULL, 1096),
    ('alla', NULL, 1096),
    ('biblioteca', NULL, 1096),
    ('PhD', NULL, 1099),
    ('doctorate', NULL, 1101),
    ('saggio', NULL, 1102),
    ('breve', NULL, 1102),
    ('paper', NULL, 1104),
    ('imbrogliare', NULL, 1105),
    ('to', NULL, 1107),
    ('cheat', NULL, 1107),
    ('to', NULL, 1107),
    ('copy', NULL, 1107),
    ('chiarire', NULL, 1108),
    ('to', NULL, 1110),
    ('explain', NULL, 1110),
    ('to', NULL, 1110),
    ('clarify', NULL, 1110),
    ('rivedere', NULL, 1111),
    ('to', NULL, 1113),
    ('revise', NULL, 1113),
    ('to', NULL, 1113),
    ('review', NULL, 1113),
    ('costo', NULL, 1114),
    ('kustannus', NULL, 1115),
    ('cost', NULL, 1116),
    ('ribasso', NULL, 1117),
    ('hinnanalennus', NULL, 1118),
    ('reduction', NULL, 1119),
    ('versamento', NULL, 1120),
    ('suoritus', NULL, 1121),
    ('remittance', NULL, 1122),
    ('preventivo', NULL, 1123),
    ('talousarvio', NULL, 1124),
    ('estimate', NULL, 1125),
    ('economia', NULL, 1126),
    ('taloudellisuus', NULL, 1127),
    ('economy', NULL, 1128),
    ('kustannus', NULL, 1129),
    ('cost', NULL, 1130),
    ('guadagno', NULL, 1131),
    ('ansiot', NULL, 1132),
    ('earnings', NULL, 1133),
    ('imposta', NULL, 1134),
    ('maksu', NULL, 1135),
    ('levy', NULL, 1136),
    ('moneta', NULL, 1137),
    ('rahayksikkö', NULL, 1138),
    ('money', NULL, 1139),
    ('aumento', NULL, 1140),
    ('dei', NULL, 1140),
    ('prezzi', NULL, 1140),
    ('hintojen', NULL, 1141),
    ('nousu', NULL, 1141),
    ('price', NULL, 1142),
    ('increase', NULL, 1142),
    ('prestito', NULL, 1143),
    ('ipotecario', NULL, 1143),
    ('kiinnityslaina', NULL, 1144),
    ('home', NULL, 1145),
    ('loan', NULL, 1145),
    ('impiego', NULL, 1146),
    ('di', NULL, 1146),
    ('capitale', NULL, 1146),
    ('pääomasijoitus', NULL, 1147),
    ('capital', NULL, 1148),
    ('carta', NULL, 1149),
    ('di', NULL, 1149),
    ('credito', NULL, 1149),
    ('carta', NULL, 1149),
    ('di', NULL, 1149),
    ('pagamento', NULL, 1149),
    ('maksukortti', NULL, 1150),
    ('credit', NULL, 1151),
    ('card', NULL, 1151),
    ('payment', NULL, 1151),
    ('card', NULL, 1151),
    ('sportello', NULL, 1152),
    ('automatico', NULL, 1152),
    ('otto', NULL, 1153),
    ('cash', NULL, 1154),
    ('machine', NULL, 1154),
    ('mercato', NULL, 1155),
    ('azionario', NULL, 1155),
    ('osakemarkkinat', NULL, 1156),
    ('stock', NULL, 1157),
    ('market', NULL, 1157),
    ('share', NULL, 1157),
    ('market', NULL, 1157),
    ('passivo', NULL, 1158),
    ('velvoite', NULL, 1159),
    ('liability', NULL, 1160),
    ('tasso', NULL, 1161),
    ('tuotto', NULL, 1162),
    ('rate', NULL, 1163),
    ('polizza', NULL, 1164),
    ('turva', NULL, 1165),
    ('policy', NULL, 1166),
    ('Bilancio', NULL, 1167),
    ('Menot', NULL, 1168),
    ('Entrata', NULL, 1169),
    ('Ansio', NULL, 1170),
    ('Denaro', NULL, 1171),
    ('contante', NULL, 1171),
    ('Raha', NULL, 1172),
    ('Money', NULL, 1173),
    ('Tasso', NULL, 1174),
    ('di', NULL, 1174),
    ('interesse', NULL, 1174),
    ('Interesse', NULL, 1174),
    ('Interest', NULL, 1175),
    ('rate', NULL, 1175),
    ('Interest', NULL, 1175),
    ('Rimanenza', NULL, 1176),
    ('Jäännös', NULL, 1177),
    ('Remainder', NULL, 1178),
    ('Tariffa', NULL, 1179),
    ('Maksu', NULL, 1180),
    ('Fee', NULL, 1181),
    ('Bilancio', NULL, 1182),
    ('familiare', NULL, 1182),
    ('Economia', NULL, 1182),
    ('domestica', NULL, 1182),
    ('Kotitalous', NULL, 1183),
    ('Family', NULL, 1184),
    ('budget', NULL, 1184),
    ('Household', NULL, 1184),
    ('finances', NULL, 1184),
    ('carta', NULL, 1185),
    ('card', NULL, 1186),
    ('sfarzo', NULL, 1187),
    ('loisto', NULL, 1188),
    ('opulence', NULL, 1189),
    ('tuotto', NULL, 1190),
    ('gain', NULL, 1191),
    ('tasso', NULL, 1192),
    ('di', NULL, 1192),
    ('cambio', NULL, 1192),
    ('cambio', NULL, 1192),
    ('valutario', NULL, 1192),
    ('vaihtokurssi', NULL, 1193),
    ('exchange', NULL, 1194),
    ('rate', NULL, 1194),
    ('currency', NULL, 1194),
    ('rate', NULL, 1194),
    ('borsellino', NULL, 1195),
    ('kukkaro', NULL, 1196),
    ('purse', NULL, 1197),
    ('Disponibilità', NULL, 1198),
    ('finanziaria', NULL, 1198),
    ('Rahoitusasema', NULL, 1199),
    ('Financial', NULL, 1200),
    ('availability', NULL, 1200),
    ('Cellulare', NULL, 1201),
    ('Puhelin', NULL, 1202),
    ('Cellphone', NULL, 1203),
    ('Social', NULL, 1204),
    ('media', NULL, 1204),
    ('Social', NULL, 1204),
    ('network', NULL, 1204),
    ('Sosiaalinen', NULL, 1205),
    ('media', NULL, 1205),
    ('Some', NULL, 1205),
    ('Social', NULL, 1206),
    ('media', NULL, 1206),
    ('Social', NULL, 1206),
    ('network', NULL, 1206),
    ('Rete', NULL, 1207),
    ('Verkko', NULL, 1208),
    ('Web', NULL, 1209),
    ('Filmato', NULL, 1210),
    ('Elokuva', NULL, 1211),
    ('Clip', NULL, 1212),
    ('SMS', NULL, 1213),
    ('Tekstiviesti', NULL, 1214),
    ('Text', NULL, 1215),
    ('Avviso', NULL, 1216),
    ('Varoitus', NULL, 1217),
    ('Alert', NULL, 1218),
    ('Pubblicazione', NULL, 1219),
    ('Julkaisu', NULL, 1220),
    ('Update', NULL, 1221),
    ('Diretta', NULL, 1222),
    ('Suora', NULL, 1223),
    ('lähetys', NULL, 1223),
    ('Streaming', NULL, 1224),
    ('Etichetta', NULL, 1225),
    ('Tunniste', NULL, 1226),
    ('Tag', NULL, 1227),
    ('Scaricamento', NULL, 1228),
    ('Imurointi', NULL, 1229),
    ('DL', NULL, 1230),
    ('Caricamento', NULL, 1231),
    ('Tallennus', NULL, 1232),
    ('UP', NULL, 1233),
    ('Riproduzione', NULL, 1234),
    ('in', NULL, 1234),
    ('diretta', NULL, 1234),
    ('Suoratoisto', NULL, 1235),
    ('Broadcasting', NULL, 1236),
    ('Trasmissione', NULL, 1237),
    ('audio', NULL, 1237),
    ('Äänitallenne', NULL, 1238),
    ('Audio', NULL, 1239),
    ('show', NULL, 1239),
    ('Applicazione', NULL, 1240),
    ('App', NULL, 1241),
    ('Sovellusohjelma', NULL, 1241),
    ('Application', NULL, 1242),
    ('Navigatore', NULL, 1243),
    ('Nettiselain', NULL, 1244),
    ('Web', NULL, 1245),
    ('Nuvola', NULL, 1246),
    ('Verkkotallennus', NULL, 1247),
    ('Online', NULL, 1248),
    ('storage', NULL, 1248),
    ('Conversazione', NULL, 1249),
    ('online', NULL, 1249),
    ('Verkkokeskustelu', NULL, 1250),
    ('Online', NULL, 1251),
    ('conversation', NULL, 1251),
    ('Emoticon', NULL, 1252),
    ('Hymiö', NULL, 1253),
    ('Emoticon', NULL, 1254),
    ('Update', NULL, 1255),
    ('Uusin', NULL, 1256),
    ('versio', NULL, 1256),
    ('Upgrade', NULL, 1257),
    ('Account', NULL, 1258),
    ('Tili', NULL, 1259),
    ('Account', NULL, 1260),
    ('Autoritratto', NULL, 1261),
    ('Omakuva', NULL, 1262),
    ('Self-portrait', NULL, 1263),
    ('Accumulatore', NULL, 1264),
    ('Paristo', NULL, 1265),
    ('Cell', NULL, 1266),
    ('Mi', NULL, 1267),
    ('piace', NULL, 1267),
    ('Peukku', NULL, 1268),
    ('Thumbs', NULL, 1269),
    ('up', NULL, 1269),
    ('Profilo', NULL, 1270),
    ('Käyttäjätili', NULL, 1271),
    ('Profile', NULL, 1272),
    ('Spazio', NULL, 1273),
    ('Tallennustila', NULL, 1274),
    ('Storage', NULL, 1275),
    ('Iscriversi', NULL, 1276),
    ('Tilata', NULL, 1277),
    ('Subscribe', NULL, 1278),
    ('Feedback', NULL, 1279),
    ('Palaute', NULL, 1280),
    ('Feedback', NULL, 1281),
    ('pallone', NULL, 1282),
    ('futis', NULL, 1283),
    ('soccer', NULL, 1284),
    ('strumento', NULL, 1285),
    ('musicale', NULL, 1285),
    ('soitin', NULL, 1286),
    ('musical', NULL, 1287),
    ('instrument', NULL, 1287),
    ('leffa', NULL, 1288),
    ('volume', NULL, 1289),
    ('teos', NULL, 1290),
    ('volume', NULL, 1291),
    ('jogging', NULL, 1292),
    ('lenkkeily', NULL, 1293),
    ('jogging', NULL, 1294),
    ('spettacolo', NULL, 1295),
    ('musicale', NULL, 1295),
    ('musiikkiesitys', NULL, 1296),
    ('musical', NULL, 1297),
    ('performance', NULL, 1297),
    ('narrativa', NULL, 1298),
    ('kertomus', NULL, 1299),
    ('fiction', NULL, 1300),
    ('piscina', NULL, 1301),
    ('uima-allas', NULL, 1302),
    ('pool', NULL, 1303),
    ('scatto', NULL, 1304),
    ('kuvaaminen', NULL, 1305),
    ('shooting', NULL, 1306),
    ('creatività', NULL, 1307),
    ('luovuus', NULL, 1308),
    ('creativity', NULL, 1309),
    ('ballo', NULL, 1310),
    ('tanssiminen', NULL, 1311),
    ('ball', NULL, 1312),
    ('escursione', NULL, 1313),
    ('retki', NULL, 1314),
    ('trip', NULL, 1315),
    ('orticoltura', NULL, 1316),
    ('puutarhaviljely', NULL, 1317),
    ('horticulture', NULL, 1318),
    ('gastronomia', NULL, 1319),
    ('gastronomy', NULL, 1320),
    ('modellazione', NULL, 1321),
    ('muotoilu', NULL, 1322),
    ('modeling', NULL, 1323),
    ('raccolta', NULL, 1324),
    ('kokoelma', NULL, 1325),
    ('gathering', NULL, 1326),
    ('gaming', NULL, 1327),
    ('pelaaminen', NULL, 1328),
    ('video', NULL, 1329),
    ('games', NULL, 1329),
    ('gaming', NULL, 1329),
    ('camminata', NULL, 1330),
    ('lenkki', NULL, 1331),
    ('stroll', NULL, 1332),
    ('ascoltare', NULL, 1333),
    ('musica', NULL, 1333),
    ('sentire', NULL, 1333),
    ('musica', NULL, 1333),
    ('kuunnella', NULL, 1334),
    ('musiikkia', NULL, 1334),
    ('kuunnella', NULL, 1334),
    ('säveliä', NULL, 1334),
    ('listen', NULL, 1335),
    ('to', NULL, 1335),
    ('music', NULL, 1335),
    ('hear', NULL, 1335),
    ('music', NULL, 1335),
    ('piano', NULL, 1336),
    ('flyygeli', NULL, 1337),
    ('grand', NULL, 1338),
    ('serie', NULL, 1339),
    ('TV', NULL, 1339),
    ('fiction', NULL, 1339),
    ('sarja', NULL, 1340),
    ('TV', NULL, 1341),
    ('series', NULL, 1341),
    ('series', NULL, 1341),
    ('sport', NULL, 1342),
    ('con', NULL, 1342),
    ('la', NULL, 1342),
    ('racchetta', NULL, 1342),
    ('mailapeli', NULL, 1343),
    ('racket', NULL, 1344),
    ('sport', NULL, 1344),
    ('film', NULL, 1345),
    ('non', NULL, 1345),
    ('di', NULL, 1345),
    ('finzione', NULL, 1345),
    ('tietofilmi', NULL, 1346),
    ('non-fiction', NULL, 1347),
    ('film', NULL, 1347),
    ('componimento', NULL, 1348),
    ('poetico', NULL, 1348),
    ('runoelma', NULL, 1349),
    ('poem', NULL, 1350),
    ('scalata', NULL, 1351),
    ('vuorikiipeily', NULL, 1352),
    ('mountaineering', NULL, 1353),
    ('gruppo', NULL, 1354),
    ('musicale', NULL, 1354),
    ('yhtye', NULL, 1355),
    ('musical', NULL, 1356),
    ('group', NULL, 1356),
    ('film', NULL, 1357),
    ('di', NULL, 1357),
    ('suspense', NULL, 1357),
    ('jännityselokuva', NULL, 1358),
    ('suspense', NULL, 1359),
    ('film', NULL, 1359),
    ('articolo', NULL, 1360),
    ('artikkeli', NULL, 1361),
    ('disc', NULL, 1362),
    ('jockey', NULL, 1362),
    ('levyjuontaja', NULL, 1363),
    ('disc', NULL, 1364),
    ('jockey', NULL, 1364),
    ('genere', NULL, 1365),
    ('fantastico', NULL, 1365),
    ('fantasiagenre', NULL, 1366),
    ('fantastic', NULL, 1367),
    ('genre', NULL, 1367),
    ('vita', NULL, 1368),
    ('scritta', NULL, 1368),
    ('elämäntarina', NULL, 1369),
    ('life', NULL, 1370),
    ('story', NULL, 1370),
    ('film', NULL, 1371),
    ('divertente', NULL, 1371),
    ('hauska', NULL, 1372),
    ('elokuva', NULL, 1372),
    ('funny', NULL, 1373),
    ('movie', NULL, 1373),
    ('musica', NULL, 1374),
    ('jazzmusiikki', NULL, 1375),
    ('music', NULL, 1376),
    ('cartone', NULL, 1377),
    ('animato', NULL, 1377),
    ('piirroselokuva', NULL, 1378),
    ('cartoon', NULL, 1379),
    ('cantare', NULL, 1380),
    ('su', NULL, 1380),
    ('basi', NULL, 1380),
    ('musicali', NULL, 1380),
    ('karaoke-laulu', NULL, 1381),
    ('singalong', NULL, 1382),
    ('graphic', NULL, 1383),
    ('novel', NULL, 1383),
    ('graafinen', NULL, 1384),
    ('romaani', NULL, 1384),
    ('comic', NULL, 1385),
    ('book', NULL, 1385),
    ('graphic', NULL, 1385),
    ('novel', NULL, 1385),
    ('nembo', NULL, 1386),
    ('fiocchi', NULL, 1387),
    ('lumisade', NULL, 1388),
    ('snowfall', NULL, 1389),
    ('trenta', NULL, 1390),
    ('giorni', NULL, 1390),
    ('kalenterikuukausi', NULL, 1391),
    ('calendar', NULL, 1392),
    ('dodici', NULL, 1393),
    ('mesi', NULL, 1393),
    ('kalenterivuosi', NULL, 1394),
    ('twelve', NULL, 1395),
    ('months', NULL, 1395),
    ('sette', NULL, 1396),
    ('giorni', NULL, 1396),
    ('seitsemän', NULL, 1397),
    ('päivää', NULL, 1397),
    ('seven', NULL, 1398),
    ('days', NULL, 1398),
    ('ventiquattro', NULL, 1399),
    ('ore', NULL, 1399),
    ('vuorokausi', NULL, 1400),
    ('twenty-four', NULL, 1401),
    ('hours', NULL, 1401),
    ('sessanta', NULL, 1402),
    ('minuti', NULL, 1402),
    ('kuusikymmentä', NULL, 1403),
    ('minuuttia', NULL, 1403),
    ('sixty', NULL, 1404),
    ('minutes', NULL, 1404),
    ('incontro', NULL, 1405),
    ('sovitus', NULL, 1406),
    ('meeting', NULL, 1407),
    ('agenda', NULL, 1408),
    ('aikataulu', NULL, 1409),
    ('schedule', NULL, 1410),
    ('meteo', NULL, 1411),
    ('sääennuste', NULL, 1412),
    ('weather', NULL, 1413),
    ('grado', NULL, 1414),
    ('aste', NULL, 1415),
    ('degree', NULL, 1416),
    ('periodo', NULL, 1417),
    ('dell''anno', NULL, 1417),
    ('vuoden', NULL, 1418),
    ('aika', NULL, 1418),
    ('time', NULL, 1419),
    ('of', NULL, 1419),
    ('year', NULL, 1419),
    ('foschia', NULL, 1420),
    ('usva', NULL, 1421),
    ('mist', NULL, 1422),
    ('vapore', NULL, 1423),
    ('acqueo', NULL, 1423),
    ('vesihöyry', NULL, 1424),
    ('moisture', NULL, 1425),
    ('saetta', NULL, 1426),
    ('ukkonen', NULL, 1427),
    ('thunderbolt', NULL, 1428),
    ('pianificare', NULL, 1429),
    ('suunnitella', NULL, 1430),
    ('rimandare', NULL, 1431),
    ('lykätä', NULL, 1432),
    ('delay', NULL, 1433),
    ('umido', NULL, 1434),
    ('kostea', NULL, 1435),
    ('wet', NULL, 1436),
    ('radioso', NULL, 1437),
    ('valoisa', NULL, 1438),
    ('bright', NULL, 1439),
    ('coperto', NULL, 1440),
    ('samea', NULL, 1441),
    ('overcast', NULL, 1442),
    ('posticipare', NULL, 1443),
    ('anticipare', NULL, 1444),
    ('arvioida', NULL, 1445),
    ('forecast', NULL, 1446),
    ('Bus', NULL, 1447),
    ('Linja-auto', NULL, 1448),
    ('Motorbus', NULL, 1449),
    ('Convoglio', NULL, 1450),
    ('Valtatie', NULL, 1451),
    ('Railway', NULL, 1452),
    ('Metropolitana', NULL, 1453),
    ('Metrojuna', NULL, 1454),
    ('Underground', NULL, 1455),
    ('Bici', NULL, 1456),
    ('Pyörä', NULL, 1457),
    ('Bike', NULL, 1458),
    ('Titolo', NULL, 1459),
    ('di', NULL, 1459),
    ('viaggio', NULL, 1459),
    ('Matkalippu', NULL, 1460),
    ('Pass', NULL, 1461),
    ('Sosta', NULL, 1462),
    ('Pysähdyspaikka', NULL, 1463),
    ('Bus', NULL, 1464),
    ('Stop', NULL, 1464),
    ('Stop', NULL, 1464),
    ('Tessera', NULL, 1465),
    ('Sarjalippu', NULL, 1466),
    ('Season', NULL, 1467),
    ('ticket', NULL, 1467),
    ('Pass', NULL, 1467),
    ('Piattaforma', NULL, 1468),
    ('Raide', NULL, 1469),
    ('Track', NULL, 1470),
    ('Timbrare', NULL, 1471),
    ('Vahvistaa', NULL, 1472),
    ('Stamp', NULL, 1473),
    ('Tardo', NULL, 1474),
    ('Viivästys', NULL, 1475),
    ('Lateness', NULL, 1476),
    ('Protesta', NULL, 1477),
    ('Työtaistelu', NULL, 1478),
    ('Walkout', NULL, 1479),
    ('Valigia', NULL, 1480),
    ('Laukku', NULL, 1481),
    ('Baggage', NULL, 1482),
    ('Verificatore', NULL, 1483),
    ('Lipuntarkastaja', NULL, 1484),
    ('Ticket', NULL, 1485),
    ('inspector', NULL, 1485),
    ('Conductor', NULL, 1485),
    ('Riservare', NULL, 1486),
    ('Ajanvaraus', NULL, 1487),
    ('Tassì', NULL, 1488),
    ('Henkilöauto', NULL, 1489),
    ('Cab', NULL, 1490),
    ('Conducente', NULL, 1491),
    ('Ajaja', NULL, 1492),
    ('Chauffeur', NULL, 1493),
    ('Congestione', NULL, 1494),
    ('Ruuhka', NULL, 1495),
    ('Congestion', NULL, 1496),
    ('Percorso', NULL, 1497),
    ('Matkareitti', NULL, 1498),
    ('Itinerary', NULL, 1499),
    ('Carrozza', NULL, 1500),
    ('Junavaunu', NULL, 1501),
    ('Wagon', NULL, 1502),
    ('Terminal', NULL, 1503),
    ('Pääteasema', NULL, 1504),
    ('End', NULL, 1505),
    ('of', NULL, 1505),
    ('the', NULL, 1505),
    ('line', NULL, 1505),
    ('Cambio', NULL, 1506),
    ('Vaihto', NULL, 1507),
    ('Transfer', NULL, 1508),
    ('Tariffa', NULL, 1509),
    ('autostradale', NULL, 1509),
    ('Tullimaksu', NULL, 1510),
    ('Highway', NULL, 1511),
    ('fee', NULL, 1511),
    ('Tangenziale', NULL, 1512),
    ('Kehä', NULL, 1513),
    ('Ring', NULL, 1514),
    ('road', NULL, 1514),
    ('Parkki', NULL, 1515),
    ('Car', NULL, 1516),
    ('park', NULL, 1516),
    ('Corsia', NULL, 1517),
    ('preferenziale', NULL, 1517),
    ('Corsia', NULL, 1517),
    ('riservata', NULL, 1517),
    ('Erityiskaista', NULL, 1518),
    ('Bus', NULL, 1519),
    ('lane', NULL, 1519),
    ('Reserved', NULL, 1519),
    ('lane', NULL, 1519),
    ('Percorso', NULL, 1520),
    ('Reitti', NULL, 1521),
    ('Route', NULL, 1522),
    ('Verifica', NULL, 1523),
    ('Valvonta', NULL, 1524),
    ('Check', NULL, 1525),
    ('Journey', NULL, 1526),
    ('Albergo', NULL, 1527),
    ('Majatalo', NULL, 1528),
    ('Inn', NULL, 1529),
    ('Vacanza', NULL, 1530),
    ('Matkailu', NULL, 1531),
    ('Vacationing', NULL, 1532),
    ('Pianta', NULL, 1533),
    ('Opaskartta', NULL, 1534),
    ('Chart', NULL, 1535),
    ('Bagaglio', NULL, 1536),
    ('Laukku', NULL, 1537),
    ('Luggage', NULL, 1538),
    ('Ferie', NULL, 1539),
    ('Lomat', NULL, 1540),
    ('Holiday', NULL, 1541),
    ('Pinacoteca', NULL, 1542),
    ('Taidemuseo', NULL, 1543),
    ('Gallery', NULL, 1544),
    ('Guida', NULL, 1545),
    ('turistica', NULL, 1545),
    ('Accompagnatore', NULL, 1545),
    ('Matkaopas', NULL, 1546),
    ('Tour', NULL, 1547),
    ('guide', NULL, 1547),
    ('Escort', NULL, 1547),
    ('Lido', NULL, 1548),
    ('Hiekkaranta', NULL, 1549),
    ('Shore', NULL, 1550),
    ('Bagaglio', NULL, 1551),
    ('a', NULL, 1551),
    ('mano', NULL, 1551),
    ('Borsa', NULL, 1551),
    ('da', NULL, 1551),
    ('viaggio', NULL, 1551),
    ('Käsimatkatavara', NULL, 1552),
    ('Carry-on', NULL, 1553),
    ('luggage', NULL, 1553),
    ('Hand', NULL, 1553),
    ('luggage', NULL, 1553),
    ('Riserva', NULL, 1554),
    ('Tilaus', NULL, 1555),
    ('Booking', NULL, 1556),
    ('Matkasuunnitelma', NULL, 1557),
    ('Route', NULL, 1558),
    ('Sistemazione', NULL, 1559),
    ('Asunto', NULL, 1560),
    ('Lodging', NULL, 1561),
    ('Gita', NULL, 1562),
    ('Matka', NULL, 1563),
    ('Outing', NULL, 1564),
    ('Volo', NULL, 1565),
    ('diretto', NULL, 1565),
    ('Volo', NULL, 1565),
    ('senza', NULL, 1565),
    ('scali', NULL, 1565),
    ('Suora', NULL, 1566),
    ('lento', NULL, 1566),
    ('Nonstop-lento', NULL, 1566),
    ('Direct', NULL, 1567),
    ('flight', NULL, 1567),
    ('Nonstop', NULL, 1567),
    ('flight', NULL, 1567),
    ('Cambio', NULL, 1568),
    ('valuta', NULL, 1568),
    ('Ufficio', NULL, 1568),
    ('cambi', NULL, 1568),
    ('Rahanvaihto', NULL, 1569),
    ('Currency', NULL, 1570),
    ('exchange', NULL, 1570),
    ('Money', NULL, 1570),
    ('exchange', NULL, 1570),
    ('Viaggio', NULL, 1571),
    ('aereo', NULL, 1571),
    ('Lentomatka', NULL, 1572),
    ('Air', NULL, 1573),
    ('travel', NULL, 1573),
    ('Ferie', NULL, 1574),
    ('Documento', NULL, 1575),
    ('di', NULL, 1575),
    ('viaggio', NULL, 1575),
    ('Matkustusasiakirja', NULL, 1576),
    ('Travel', NULL, 1577),
    ('document', NULL, 1577),
    ('Ufficio', NULL, 1578),
    ('doganale', NULL, 1578),
    ('Tullitoimisto', NULL, 1579),
    ('Border', NULL, 1580),
    ('control', NULL, 1580),
    ('Area', NULL, 1581),
    ('di', NULL, 1581),
    ('servizio', NULL, 1581),
    ('Autogrill', NULL, 1581),
    ('Liikenneasema', NULL, 1582),
    ('Service', NULL, 1583),
    ('area', NULL, 1583),
    ('Rest', NULL, 1583),
    ('area', NULL, 1583),
    ('Ricordo', NULL, 1584),
    ('Muistoesine', NULL, 1585),
    ('Memento', NULL, 1586),
    ('Meta', NULL, 1587),
    ('Määränpää', NULL, 1588),
    ('Goal', NULL, 1589),
    ('Viipyminen', NULL, 1590),
    ('Residence', NULL, 1591),
    ('Luogo', NULL, 1592),
    ('d''interesse', NULL, 1592),
    ('Vetonaula', NULL, 1593),
    ('Sight', NULL, 1594),
    ('Restituzione', NULL, 1595),
    ('Hyvitys', NULL, 1596),
    ('Reimbursement', NULL, 1597),
    ('Viaggio', NULL, 1598),
    ('in', NULL, 1598),
    ('nave', NULL, 1598),
    ('Laivamatka', NULL, 1599),
    ('Sea', NULL, 1600),
    ('voyage', NULL, 1600),
    ('Permesso', NULL, 1601),
    ('d''ingresso', NULL, 1601),
    ('Maahantulolupa', NULL, 1602),
    ('Entry', NULL, 1603),
    ('permit', NULL, 1603)
ON CONFLICT DO NOTHING;

COMMIT;